### ISSUE TITLE
Successfully connecting to heroku from localhost:8080 but getting errors when connecting from gh-pages

### ISSUE THREAD

**Issue by rchezrutt88** [ga-wdi-boston/group-project#100]
We were getting this error:
```
XMLHttpRequest cannot load https://evening-depths-31503.herokuapp.com/sign-in. The 'Access-Control-Allow-Origin' header has a value 'http://localhost:8080' that is not equal to the supplied origin. Origin 'http://insert-squad-name.github.io' is therefore not allowed access.
```
We had hard coded the environment variable to allow requests from our gh-page in the .env, unignored the .env file (yeah, yeah, we know...) and pushed it to heroku—but no dice. In consultation with @J-Weeks help, we finally tried the heroku tool belt command ```heroku config:set GITHUB_IO_URL=http://insert-squad-name.github.io/group-project-front-end/```.

It worked. It was awesome. 

I wonder if the reasons why we needed to do this could have been made clearer while we were covering express.

**Comment by gaand** [comment]
Google CORS.
