### ISSUE TITLE
Filebucket folder structure

### ISSUE THREAD

**Issue by Benjamski** [ga-wdi-boston/group-project#104]
Quick question on requirements:

For Filebucket, is it a requirement to have users' files organized into folders?

**Comment by laurenfazah** [comment]
@gaand can you weigh in?

**Comment by J-Weeks** [comment]
@Benjamski Can you describe a bit more?

**Comment by cuprous** [comment]
@J-Weeks 

File system does not necessarily imply the presence of folders, e.g., [m-files](https://www.m-files.com/en). So in all seriousness, do we **have** to represent a folder structure to the end users, or would sorting based on tagging or some other metadata satisfy the prompt?

**Comment by rdelvallej32** [comment]
^ What he said

**Comment by J-Weeks** [comment]
Folder structure

**Comment by cuprous** [comment]
Thanks for the clarification.
