### ISSUE TITLE
Would like to have discussion about our Database Structure

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/group-project#105]
We have some questions about the best approach to our database. 

We want to have users have many locations; we're unsure if we should have two separate Documents, with locations containing a _owner_id, and then query that collection by _owner_id for GET requests. 

OR if the location document should be contained within the user document (We feel this is the better option, but we're not sure if it meets the requirements.)

**Comment by J-Weeks** [comment]
Lou, what is the difference between SQL and noSQL?  You're first one sounds very relational, your second one seems to be on the right track, please expand on the idea though.

**Comment by gaand** [comment]
Let's chat briefly

**Comment by louarnos** [comment]
We decided we are going to nest the location documents in the users document as an array of locations. Will research sub-documents in the mongo documentation. Talked about having a separate controller to deal with location actions.
