### ISSUE TITLE
Updating array inside subdocument

### ISSUE THREAD

**Issue by susandaiute** [ga-wdi-boston/group-project#109]
We have Users which have subdocument arrays of Locations.  If we have

```
const update = (req, res, next) => {
  let name = req.body.location.name;
  console.log( User.findById({ "_id": req.body.user.id}));
  User.findByIdAndUpdate(
    { "_id": req.body.user.id, "locations._id": req.body.location.id },
    {
      '$set': {
          'locations.': { "name": name }
      }
  })
    .then(() => res.sendStatus(200))
    .catch(err => next(err));
};
```
to, for example, update the name of a location  (one of three created locations) then the name patch is successful and we get a 200 response, but the other two locations are deleted.

We also tried 

```
$set {
  "locations.$": { "name": name }}
```
which returns the error:

{"error":{"message":"The positional operator did not find the match needed from the query. Unexpanded update: locations.$","error":{"name":"MongoError","message":"The positional operator did not find the match needed from the query. Unexpanded update: locations.$","ok":0,"errmsg":"The positional operator did not find the match needed from the query. Unexpanded update: locations.$","code":16837}}}

and

```
'$set': {
          'locations.$.name': { "name": name }
      }
  ```
which returns the error:

{"error":{"message":"Cast to string failed for value \"[object Object]\" at path \"name\"","error":{"message":"Cast to string failed for value \"[object Object]\" at path \"name\"","name":"CastError","kind":"string","value":{"name":"test change name"},"path":"name"}}}~/wdi/projects/bucket-list/bucket_backend (patch)$

**Comment by gaand** [comment]
Does the update preserve the other attributes for the location that remains?

**Comment by susandaiute** [comment]
Yes

**Comment by gaand** [comment]
Weird.  

I think your close with that last one.  I did a search and found this: http://mongoblog.tumblr.com/post/21792332279/updating-one-element-in-an-array

I think this is likely to solve your problem:

```diff
'$set': {
-   'locations.$.name': { "name": name }
+   'locations.$.name': name
}
```

**Comment by susandaiute** [comment]
Thank you! Olivia is actually working on this part, but she just got home from some cross country travel so we'll point her this way when she's ready.

**Comment by gaand** [comment]
@susandaiute Okay.  If it does fix it, please close with a comment.

**Comment by louarnos** [comment]
@gaand. I tried what you have above and continued to get the same error. I am able to get it to work with:
```
const update = (req, res, next) => {
  let change = req.body.location.change;
  let field = req.body.location.field;
  User.findById(req.body.user.id).then( function (user) {
    let match = false;
    user.locations.forEach( function (location) {
      console.log(location._id);
      console.log(req.body.location.id);
      if(location._id == req.body.location.id) {
        console.log(location.field);
        console.log(change);
        location[field] = change;
        match = true;
        console.log(match);
      }
    });
    if(match) {
      return user.save();
    }else {
      return next();
    }
  })
    .then(user => res.json({ user }))
    .catch(err => next(err));
};
```
But it uses == as opposed to ===. When I use === I get:

```
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (/Users/louisarnos/wdi/projects/group-project/bucket_backend/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/Users/louisarnos/wdi/projects/group-project/bucket_backend/node_modules/express/lib/response.js:163:12)
    at ServerResponse.json (/Users/louisarnos/wdi/projects/group-project/bucket_backend/node_modules/express/lib/response.js:249:15)
    at /Users/louisarnos/wdi/projects/group-project/bucket_backend/app/controllers/locations.js:63:23
    at process._tickCallback (node.js:369:9)
```

**Comment by RDegnen** [comment]
maybe this will help? http://stackoverflow.com/questions/7042340/node-js-error-cant-set-headers-after-they-are-sent

**Comment by gaand** [comment]
Rereading the first message, why did you use `User.findByIdAndUpdate`?

This may have been part of the problem.

**Comment by gaand** [comment]
Oh, and you should cast the `.id` field to an ObjectId so that `===` works.

Also, I think the forEach may always generate that error if no match is found.

**Comment by louarnos** [comment]
@gaand Ok, I've made some progress. I can update a name with this:
```
const update = (req, res, next) => {
  let change = req.body.location.change;
  let field = req.body.location.field;
  User.update(
    {"_id" : mongoose.Types.ObjectId(req.body.user.id),
    "locations._id" : mongoose.Types.ObjectId(req.body.location.id) },
    {$set : {'locations.$.name': change}})
    .then(user => res.json({ user }))
    .catch(err => next(err));
};
```
I'd like to be able to update a location's values dynamically determined by data passed to the ajax call. I tried using string interpolation in the $set method, but it doesn't seem to like that. Here is my code:

```
const update = (req, res, next) => {
  let change = req.body.location.change;
  let field = req.body.location.field;
  User.update(
    {"_id" : mongoose.Types.ObjectId(req.body.user.id),
    "locations._id" : mongoose.Types.ObjectId(req.body.location.id) },
    {$set : {`locations.$.${field}`: change}})
    .then(user => res.json({ user }))
    .catch(err => next(err));
};
```
When I do this I get a syntax error saying:

```
{$set : {`locations.$.${field}`: change}})
             ^^^^^^^^^^^^^^^

SyntaxError: Unexpected template string
```

**Comment by gaand** [comment]
Yes.  The following is fragment is equivalent to what you're trying:

```js
{"locations.$." + field: change}
```

Is it clear why that doesn't work?

You can dynamically construct what you want, but not quite as inline as you tried.

I think that's a separate issue from this one.

**Comment by louarnos** [comment]
That still gives me an unexpected token error. If you'd like me to open a separate issue I can do that.

**Comment by gaand** [comment]
If you put in the code I wrote, yes it should give that error.  It's not valid JavaScript.  Please open a separate issue about why and what to do instead.
