### ISSUE TITLE
mystery debugger

### ISSUE THREAD

**Issue by V4Vince** [ga-wdi-boston/group-project#111]
When loading my localhost:8080 page, it pauses for a debugger even though we didn't use a debugger. The debugger is located in a ```bundle.js``` file. 
The error reads: ```/* WEBPACK VAR INJECTION */}.call(exports, __webpack_require__(2)))```

I'm the only one in my group having this issue.

**Comment by laurenfazah** [comment]
You may have added a debugger through Chrome. In the sources tab in the developer console, are any lines marked with a blue arrow? Untick them if so. If not, we can debug further.

**Comment by Benjamski** [comment]
@V4Vince I ran into this same issue today. Look for the blue marker lauren mentioned.

**Comment by laurenfazah** [comment]
Aka something like this:

![screen shot 2016-05-16 at 9 25 37 am](https://cloud.githubusercontent.com/assets/8062679/15290692/3e582e22-1b48-11e6-9ee7-875ba5cd09b8.png)

**Comment by V4Vince** [comment]
Works. Thanks @Benjamski @laurenfazah !
