### ISSUE TITLE
Modelling question

### ISSUE THREAD

**Issue by sjf125** [ga-wdi-boston/group-project#119]
Is there any reason why orders shouldnt also be nested under a user document, as carts currently are for us?  Is there any reason/utility to have orders be a separate collection, but not carts?

**Comment by laurenfazah** [comment]
Could you describe the differences between carts and orders? What you're storing for each?

**Comment by sjf125** [comment]
We're storing the same thing - though orders need to be separate to store a collection of line items as one order.  Nevermind!  Just had a rubber duck moment.
