### ISSUE TITLE
Project Deliverables Review

### ISSUE THREAD

**Issue by philschoof** [ga-wdi-boston/group-project#125]
Any chance we can go over the deliverables with a consultant today to make sure we're on track?

**Comment by gaand** [comment]
Please go through 

- https://github.com/ga-wdi-boston/group-project#technical-requirements
- https://github.com/ga-wdi-boston/group-project#necessary-deliverables

If you believe that you've achieved what's there, then a consultant will meet with you.

If you have questions, please try to ask them here.

**Comment by soynog** [comment]
Hi Antony,

Always good to check, but yes we've gone through the deliverables list. We're still working on our READMEs and haven't deployed yet, but otherwise we believe we're meeting all of the deliverables.

**Comment by gaand** [comment]
That great. 

So you just want an unofficial confirmation?

**Comment by soynog** [comment]
Yes please!

**Comment by J-Weeks** [comment]
After you are fully deployed I would be happy to review

**Comment by soynog** [comment]
We were hoping to make some nice but not necessary stylistic improvements before deploying, but wanted to be sure we're meeting all requirements before embarking on that... Someone can't just take a few minutes to go through the app with us?

**Comment by J-Weeks** [comment]
It doesn't technically meet deliverables before it is deployed.  Plus there are (may be) other steps you need to take or change once it is deployed. I want to make sure that if you don't spend a ton of time on styles, ect and hit some major deployment issues that require lots or time or code changes.

**Comment by philschoof** [comment]
Thanks Jason - we'll let you know once we've deployed. Should I close this issue?

**Comment by gaand** [comment]
Please.  And reopen after you deploy.

**Comment by philschoof** [comment]
Hey @J-Weeks, we have successfully deployed. Let me know when you have a few minutes. Thanks!

**Comment by J-Weeks** [comment]
Nice, keep working. What room are you in I'll be up before the end of the day.

**Comment by philschoof** [comment]
in the dug out at the moment. we can meet you wherever.

**Comment by philschoof** [comment]
Had review - aside from one error that only occurs on my computer we're good.
