### ISSUE TITLE
Also having trouble deploying Back end to Heroku

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/group-project#128]
I followed the directions here: https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction.

Currently when I visited the url in my browser I see: 

> An error occurred in the application and your page could not be served. Please try again in a few moments.
> 
> If you are the application owner, check your logs for details.

My logs say:

``` bash
2016-05-18T15:20:28.097252+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=cryptic-brushlands-42769.herokuapp.com request_id=75ba9061-ad5c-474d-8b09-46599b1cc57b fwd="74.118.24.163" dyno= connect= service= status=503 bytes=
```

Halp!

**Comment by J-Weeks** [comment]
What does your error say? Have you tried to google this error message?

**Comment by laurenfazah** [comment]
Check out the latest comments at #127

**Comment by louarnos** [comment]
Successfully deployed by creating a Procfile and following https://scotch.io/tutorials/use-mongodb-with-a-node-application-on-heroku. Get 404s when logging in, so opening a new issue.
