### ISSUE TITLE
Ecommerce: Promises and ajax

### ISSUE THREAD

**Issue by modularjon** [ga-wdi-boston/group-project#137]
While trying to integrating stripe, I'm a little unsure about using a self created promise, or whether to rely on the .then method for ajax, or whether there is a hybridization between the two I should be using. The idea is that the whole chain starts from an event handler named onPurchaseSubmit that first sends an ajax post to our orders controller, gets a response (success or failure), then uses response to send info to stripe, then uses stripe's response to patch the order.

**Comment by modularjon** [comment]
@jrhorn424 @berziiii

**Comment by berziiii** [comment]
Which one of the three options from above have you tried? I believe all three options could work but you should choose one and if you run into issues, we debug.

**Comment by modularjon** [comment]
I'm heading down the ajax only route. I'll leave this open for the moment in case I run into anything.

**Comment by berziiii** [comment]
```js
api.profile.create = () => {
  return new Promise((resolve, reject) => {
    $.ajax({
      url: ...,
      data: ...,
      success: (response) => {
        resolve(response);
      },
      error: (error) => {
        reject(error);
      },
    });
  });
};

api.profile.create().then().catch();
```

I'd advise something along these lines...

**Comment by berziiii** [comment]
```js
api.nameOfFunction = () => {
  return new Promise((resolve, reject) => {
    $.ajax({
      url: ...,
      data: ...,
      headers: ...,
      success: (response) => {
        resolve(response);
      },
      error: (error) => {
        reject(error);
      },
    });
  });
};

api.profile.create().then().catch();
```

**Comment by jrhorn424** [comment]
I approve this suggestion. 😄

**Comment by jrhorn424** [comment]
@modularjon Can this be closed for now?
