### ISSUE TITLE
PATCH isn't working for images

### ISSUE THREAD

**Issue by andreasantarl** [ga-wdi-boston/group-project#138]
We are trying to have a profile image and a bucket list item image.  Those image fields are part of our profile and bucket schemas (not a separate schema), but we have custom routes for those patch requests.   For example:

.resources('buckets', { only: ['index', 'show', 'destroy', 'create'] })
.patch('/update-bucket/:id', 'buckets#update')
.patch('/upload-bucket-image/:id', 'buckets#uploadimg')

We make the curl requests and in our front-end we have a UI for the uploads.  The files are only inconsistently saving to our DB, yet we are getting 200 response every time we make our request.   
Can we have a face-to-face with one of you to discuss why we're getting inconsistent results?

Thanks!
Andrea and Lindsey

**Comment by payne-chris-r** [comment]
Whe dey at doe?

**Comment by payne-chris-r** [comment]
Jk. Come to me. There's cereal in the duggie.

**Comment by jrhorn424** [comment]
Please provide client code.

**Comment by andreasantarl** [comment]
We're here!!!

**Comment by andreasantarl** [comment]
$('#multipart-form-data').on('submit', (event) => {
    event.preventDefault();

    let data = new FormData(event.target);

    $.ajax({
      method: 'PATCH',
      url: 'http://localhost:3000/upload-profile-image/57853ff749dbb3105d4344a7',
      headers: {
        Authorization: 'Token token=85Sfel/IjKneyDNLFVaHMG2mMwmLhvRaLkxGGsHofOI=--m7xYvs4MrhcXdTNplWo94LGRBVPdFHRN5uKETg153/A='
      },
      data,
      contentType: false,
      processData: false,
    })
    .done((data) => console.log(data))
    .fail((error) => console.error(error));
  });
});

**Comment by jrhorn424** [comment]
We discussed this afternoon. We found that after an upload was complete, the associated model instance was not being loaded before attempting to update.

```diff
- Foo.update(...)
+ Foo.findOne(...).then((foo) => foo.update(...));
```

In addition, we discussed adding an `Upload`s schema and controller to simplify the coordination of uploading then updating different resources.

```diff
- .resources('buckets', { only: ['index', 'show', 'destroy', 'create'] })
+ .resources('buckets')
- .patch('/update-bucket/:id', 'buckets#update')
- .patch('/upload-bucket-image/:id', 'buckets#uploadimg')
+ .resources('uploads', { only: ['create'] }
```

Then, on the client, something like:

```txt
api.upload.create(...).then((response) => api.profile.update(Object.assign({...}, response))).then(...);
api.upload.create(...).then((response) => api.bucket.update(Object.assign({...}, response))).then(...);
```

**Comment by jrhorn424** [comment]
@andreasantarl Can this be closed?
