### ISSUE TITLE
Dual Modals - HTML not Targeting Separate 

### ISSUE THREAD

**Issue by logicmyth** [ga-wdi-boston/group-project#139]
Ruben and I are creating two modals for the front end. We have different bootstrap ids for both modals. The issue is one modal is not opening with the content we want. It displays the old/other modal's field.

**Comment by berziiii** [comment]
How are the modals being populated? Handlebars? If so, are you clearing the HTML in the template prior to rendering the new information>

**Comment by logicmyth** [comment]
This modals are for sign-in and sign-up. We just have input fields to populate.

**Comment by berziiii** [comment]
Check to make sure all `<div>` have closing `</div>`. Also ensure you're opening the modal through `$('#id-of-modal').modal('show')`. If this doesn't fix it, please provide the code for both of the modals and the event handlers to trigger the modal to open.

**Comment by logicmyth** [comment]
Very accurate response. ty
