### ISSUE TITLE
MongoDB only creating objectID without data in it

### ISSUE THREAD

**Issue by tina513** [ga-wdi-boston/group-project#140]
We have nested array for our survey model, it includes 
```js
Survey [{ 
    query: { 
        type: String
     }, {
    option: { 
         type: String 
    }, { 
    numberOfVotes: { 
          type: Number, 
          default: 0 
    }
}]
```
After we make a create curl request, we are getting like this"
[{query: "meow?", _id: "5785514e9a363632332fde24"},
{_id: "5785514e9a363632332fde23"},
{_id: "5785514e9a363632332fde22"}
]".

We couldn't figure it out at all. Please help~

**Comment by berziiii** [comment]
Look at the above alteration, is this how your schema is structured?

**Comment by tina513** [comment]
No. 
```
const surveySchema = new mongoose.Schema({
      title: {
        type: String,
      },
      questions: [
        [{ query: { type: String}},
         {option: { type: String }, numberOfVotes: { type: Number, default: 0 } }
        ]
      ],
      _owner: {
          type: mongoose.Schema.Types.ObjectId,
          ref: 'User',
          required: true,
        }
      },
      {
        timestamps: true,
      });
```

**Comment by tina513** [comment]
And this is what we get:

```
{
_id: "5785514e9a363632332fde21",
updatedAt: "2016-07-12T20:21:34.833Z",
createdAt: "2016-07-12T20:21:34.833Z",
title: "example for new schema",
_owner: "578546fbfc03066b2b7e4cdb",
__v: 0,
questions: [
[
{
query: "meow?",
_id: "5785514e9a363632332fde24"
},
{
_id: "5785514e9a363632332fde23"
},
{
_id: "5785514e9a363632332fde22"
}
],
[
{
query: "testing?",
_id: "5785514e9a363632332fde27"
},
{
_id: "5785514e9a363632332fde26"
},
{
_id: "5785514e9a363632332fde25"
}
]
]
}
```

**Comment by tina513** [comment]
It generated _id for each option, but actual data is missing.

**Comment by berziiii** [comment]
https://github.com/ga-wdi-boston/mongoose-crud/blame/012/solution/models/person.js#L7 to get you started. Then look at the training where we created a new person with the nest properties.

**Comment by berziiii** [comment]
https://github.com/ga-wdi-boston/mongoose-crud/blame/012/solution/README.md#L296 to be even more helpful :).

**Comment by tina513** [comment]
I checked my req.body is send appropriate data, but after create method, it only generate id, but missing field and data. I am not sure whether it's coming from res.json method or other reason.

**Comment by berziiii** [comment]
Does it apprar correct in the mongo data store?

**Comment by tina513** [comment]
No. Mongo database shows the same result I saw on the localhost:3000. It only contains id without field and data. I checked req.body.survey.questions, and I printed out 
```
 [ [ { query: 'meow?' }, { option: 'please', numberOfVotes: 2 }, { option: 'work', numberOfVotes: 3 } ], [ { query: 'testing?' }, { option: 'load', numberOfVotes: 1 }, { option: 'cmaaan', numberOfVotes: 3 } ] ]
```
which is the correct data.

**Comment by tina513** [comment]
I am sure that the problem is caused by controller create function is not making correct instance of the model. client request is fine, and mongo database is missing informations.

**Comment by erinsul** [comment]
Large changes have since been made to our schema, but at any rate, it now works with nested arrays inside, like so: 
const surveySchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
    unique: true
  },
  questions: [questionSchema],
  _owner: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
}, {
  timestamps: true,
  toJSON: { virtuals: true},
});

**Comment by erinsul** [comment]
You can close this whenever you feel like it. Someone. Anyone.
