### ISSUE TITLE
Heroku Deployment Cipher Key

### ISSUE THREAD

**Issue by shkherad** [ga-wdi-boston/group-project#143]
Do we need to make new secrets after deploying on heroku?

Everything works except for POST /sign-in

Nothing changed from local host to that route or the users model but on heroku, error returned:

```
HTTP/1.1 500 Internal Server Error
Server: Cowboy
Connection: keep-alive
X-Powered-By: Express
Access-Control-Allow-Origin: http://localhost:8080
Vary: Origin
Content-Type: application/json; charset=utf-8
Content-Length: 50
Etag: W/"32-f0PDWtN4RNCHOcPLVIwtbw"
Date: Wed, 13 Jul 2016 19:32:09 GMT
Via: 1.1 vegur

{"error":{"message":"Must give cipher-type, key"}}
```

**Comment by shkherad** [comment]
That was after this curl request:

```
curl --include --request POST https://brewtiq-api.herokuapp.com/sign-in \
>   --header "Content-Type: application/json" \
>   --data '{
>     "credentials": {
>       "email": "matt",
>       "password": "p",
>       "password_confirmation": "p"
>     }
>   }'
```

**Comment by shkherad** [comment]
heroku logs on the failed sign in

And corrected curl request that I tried:

```
curl --include --request POST https://brewtiq-api.herokuapp.com/sign-in \
  --header "Content-Type: application/json" \
  --data '{
    "credentials": {
      "email": "shireen@bean.com",
      "password": "p"
    }
  }'
```

curl requst error:

`{"error":{"message":"Must give cipher-type, key"}}`

```
2016-07-13T19:52:50.406562+00:00 app[web.1]: POST /sign-in 500 286.116 ms - 50
2016-07-13T19:52:50.414235+00:00 heroku[router]: at=info method=POST path="/sign-in" host=brewtiq-api.herokuapp.com request_id=17171e7c-2042-4c4e-abd9-9e43763a4118 fwd="157.130.220.250" dyno=web.1 connect=1ms service=294ms status=500 bytes=337
```

**Comment by jrhorn424** [comment]
> Do we need to make new secrets after deploying on heroku?

Yes, but you do need to define them on Heroku, not in the `.env` file. Heroku doesn't use `.env`. You **must**  make a different `SECRET_KEY` on heroku.

**Comment by shkherad** [comment]
SOLUTION:

On Heroku:
set SECRET_KEY = <insert secret key from .env file to the value>

Same above curl request now returns a successful sign in

Thanks @jrhorn424

**Comment by jrhorn424** [comment]
You're the one that figured it out. All I did was inspect the users controller code to make sure that was indeed the thing generating the error. Good work. :+1:
