### ISSUE TITLE
Clarification: Admin actions count as user actions?

### ISSUE THREAD

**Issue by shkherad** [ga-wdi-boston/group-project#144]
Our group just wants clarification:

If an admin (which is a type of user) performs all the CRUD actions, does that count as fulfilling the requirement for a user performing all 5 actions?

In more detail:
Right now our general user can index, show, update, create, but the general user can't delete anything. (We don't want to allow a general user to be ale to delete anything from our database)

 We are working on an admin page and that user (signed in as an admin) is able to delete products, fulfilling that action requirement.

Our team just wants to clarify that this is an appropriate way of fulfilling all user actions.

**Comment by jrhorn424** [comment]
Yes, that meets the mentioned requirement.

**Comment by shkherad** [comment]
Great. Thank you
