### ISSUE TITLE
.save() isn't actually saving the item...

### ISSUE THREAD

**Issue by erinsul** [ga-wdi-boston/group-project#145]
So! I suspect this has something to do with the fact that I am trying to save a subdocument (that is a subdocument, of another subdocument of the main document).

According to the mongoose docs online, if you're saving an embedded doc, you need to call save on the parent document, not the subdocument.

My current code looks like this (it's not hooked up to a front end, just using a command line script at the moment):

```js
const update = (surveyId, questionId, answerId, userId) => {
  Survey.findById(surveyId)
  .then((survey) => {
    return survey.questions.id(questionId);
  })
  .then((question) => {
    return question.answers.id(answerId);
  })
  .then((answer) => {
    answer.votes.push( { userId } );
    console.log(answer);
    answer.save();
  })
  .then(done)
  .catch(console.error);
};
```

At the console.log, the answer that's logged shows the inserted vote. However, it doesn't seem to persist, since it can't be found when I then "get" that survey again.

Is the problem that I'm not saving the top-level parent, the survey?

I'm not 100% sure how to return to the survey to call it to save it...

**Comment by berziiii** [comment]
Can you please provide the controller code for updating the answer with the new user_id?

**Comment by berziiii** [comment]
I feel you need to reference the links I shared yesterday about `$push` to add an object to an array in mongoose. While you're using .push, I don't believe you're using it the correct way that mongoose expects to save it to the mongodb store.

**Comment by erinsul** [comment]
I was following the instructions on the mongoose documentation for updating subdocuments because I'm specifically dealing with a subdocument.

http://mongoosejs.com/docs/subdocs.html

I looked at your instructions from yesterday, but I don't know how to use that to get far enough into the subdocument tree mess to actually access votes to push to it.

**Comment by erinsul** [comment]
Okay something just worked but I don't know what. Cool. :/

**Comment by jrhorn424** [comment]
Wouldn't the parent document in this case be `Survey` instead of `answer`?

```js
const update = (surveyId, questionId, answerId, userId) => {
  Survey.findById(surveyId) // <= Initial schema
  // ...
  .then((answer) => {
  // ...
    answer.save(); // answer is a subdocument?
  })
  .then(done)
  .catch(console.error);
};
```

**Comment by erinsul** [comment]
I'm guessing that has to be the case.

So I messed up and wrote some code that got it to save once, but apparently didn't pay enough attention and now I can't find it again.

Yeah. I'm just struggling to figure out how to call survey.save because survey is a thing that was accessed not where I need it.

**Comment by jrhorn424** [comment]
See how you have survey in scope in your first then-function?

```js
  Survey.findById(surveyId)
  .then((survey) => {
```

What if you do that thing I asked you never to do and nest your thens inside the first?

If that fixes the problem, we can talk about a better way to write the code.

**Comment by erinsul** [comment]
I'm not sure if I nested them wrong, but it's now telling me [TypeError: survey.questions.id(...).then is not a function]

Code looks like this: 
const update = (surveyId, questionId, answerId, userId) => {
  Survey.findById(surveyId)
  .then((survey) => {
    survey.questions.id(questionId)
    .then((question) => {
      return question.answers.id(answerId);
    })
    .then((answer) => {
      answer.votes.push( { userId } );
      console.log(answer);
    })
    survey.save();
  })
  .then(done)
  .catch(console.error);
};

**Comment by jrhorn424** [comment]
That means `.id` does not return a Promise. That means it's probably not asynchronous. That means my earlier assumption was incorrect. http://mongoosejs.com/docs/api.html#types_documentarray_MongooseDocumentArray.id

**Comment by jrhorn424** [comment]
It also means you didn't have to have multiple `then`s in the first place. A lot of your code is synchronous so it can go inside one `.then`.

**Comment by jrhorn424** [comment]
Happy to elaborate if you like. This is a fun wrinkle.

**Comment by erinsul** [comment]
So I rewrote it to be mostly synchronous. It definitely does the same thing as it was doing before, but it still isn't appearing to save the survey.

const update = (surveyId, questionId, answerId, userId) => {
  Survey.findById(surveyId)
  .then((survey) => {
    let question = survey.questions.id(questionId);
    let answer = question.answers.id(answerId);
    answer.votes.push( { userId } );
    console.log(answer);
    survey.save();
  })
  .then(done)
  .catch(console.error);
};

The console.log answer showed the same as it did before : 
{ updatedAt: Wed Jul 13 2016 16:02:09 GMT-0400 (EDT),
  createdAt: Wed Jul 13 2016 16:02:09 GMT-0400 (EDT),
  text: 'dunno',
  _id: 57869e415bb0ae1dea5dec87,
  votes: [ { userId: '88888888' } ] }

But it still isn't showing up on the record on localhost:3000

**Comment by erinsul** [comment]
Wait. There's a very strange problem right now.

Very different problem.

I will return shortly with an update. I screwed up the schema type somewhere along the line.

**Comment by erinsul** [comment]
It won't save it because it's sending the wrong data? The schema somehow doesn't recognize it, I think. At any rate, I'm sending a user Id, and it is giving me the error 
[CastError: Cast to ObjectId failed for value "[object Object]" at path "votes"]
.

The schema: const answerSchema = new mongoose.Schema({
  text: {
    type: String,
  },
  votes: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
}, {
  toJSON: { virtuals: true},
});


The current code: 
const update = (surveyId, questionId, answerId, userId) => {
  Survey.findById(surveyId)
  .then((survey) => {
    let question = survey.questions.id(questionId);
    let answer = question.answers.id(answerId);
    answer.votes.push( { userId } );
    survey.save();
  })
  .then(done)
  .catch(console.error);
};

**Comment by erinsul** [comment]
I thought maybe it's not working because it can't recognize the item I'm passing as a User Id?

But I tried switching the schema type to be a Number, and then String, and it still gave me the same error about being unable to cast the object object.

**Comment by jrhorn424** [comment]
Come see me when you're ready.

---

Use fenced code blocks to paste code. Fenced code blocks begin with three backticks (or grave accents – &nbsp;&grave;&nbsp;) and are followed by the filetype. In this case, you probably want `js`. So you'd begin a code block with (&nbsp;&grave;&grave;&grave;js&nbsp;). Fenced code blocks are closed with three more backticks, with no filetype specifier (  &nbsp;&grave;&grave;&grave;&nbsp; ).

Use a single backtick to do an inline code snippet. It must begin and end with one backtick, and you cannot specify a filetype. `like this`

**Comment by jrhorn424** [comment]
> It won't save it because it's sending the wrong data? The schema somehow doesn't recognize it, I think. At any rate, I'm sending a user Id, and it is giving me the error

Can I see the data you're sending? You can inspect in your network tab to see request payload.

**Comment by erinsul** [comment]
So as soon as I went to talk to Antony, I re-instated some of the code, and somehow, it worked. On the first try. I felt quite foolish, and I'm still not sure what is different than all of our attempts. But at any rate, here's the final code in total, pushing User Id references into votes arrays.

The schema: 
const answerSchema = new mongoose.Schema({
  text: {
    type: String,
  },
  votes: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
    }],
}, {
  toJSON: { virtuals: true},
});

The command-line script:
const update = (surveyId, questionId, answerId, userId) => {
    Survey.findById(surveyId)
    .then((survey) => {
      let question = survey.questions.id(questionId);
      let answer = question.answers.id(answerId);
      answer.votes.push(userId);
      console.log('answer is ', answer);
      return survey.save();
  })
  .catch(console.error)
  .then(done)
  ;
};

**Comment by erinsul** [comment]
Anyway, since it's working now for whatever odd, unknown reasons, I'm going to close this issue.

**Comment by jrhorn424** [comment]
Thanks for the writeup! I don't notice any difference either. Did you happen to restart your server or mongo at any point?

As I stated previously, **please format** your comments appropriately, especially code blocks.

As promised (:laughing:), here are notes from our earlier conversation:

1. We weren't receiving error messages since we weren't returning within `then` and
1. Hanging connections were occurring because `done` was in wrong place, it should have come after `catch`.
