### ISSUE TITLE
Display background video on loop 

### ISSUE THREAD

**Issue by RoobScoobs** [ga-wdi-boston/group-project#146]
Hey guys, 

I wanted to insert via html a short mp4 that could continually run on the home screen. 

Similar to what this website shows: 
http://jhumbrac.github.io/test/

``` html
<video autoplay loop muted id="bike-ride">
   <source src="bikeride.mp4" type="video/mp4; codecs="H.264, AAC"">
</video>
```
I have the video stored on my desktop and I took the codecs from the file information. I can inspect the element on the home-page but it doesn't show up.

**Comment by berziiii** [comment]
What is the container width/height holding the video? You either have to have it in a container with the width/height you desired and have the width/height on the video be 100% OR you do inline styling on the video to have it be the dimensions you desire.

**Comment by berziiii** [comment]
Is this resolved @RoobScoobs? If so, please provide the solution and close. Thanks.

**Comment by RoobScoobs** [comment]
Sorry, haven't resolved just yet

**Comment by jrhorn424** [comment]
> I have the video stored on my desktop

What folder is it in? Can it be found?

**Comment by jrhorn424** [comment]
Also, Chrome **cannot** play mp4s **encoded with H.264**. You need to have two videos and specify multiple sources. They will be tried in order. So you can start with `src` pointing to an `mp4` then have another `src` pointing to a `.mov` instead.

If `.mov` doesn't work, you might need another format.

**Comment by berziiii** [comment]
I second @jhorn424 comments! ^ @RoobScoobs

**Comment by RoobScoobs** [comment]
Seems like I should be able to play the video with the current codecs? 

The documentation says: "The MP4 container format with the H.264 video codec and the AAC audio codec is natively supported by desktop/mobile Internet Explorer, Safari and Chrome"

**Comment by jrhorn424** [comment]
Mind providing a link? I'm seeing conflicting stuff about H.264. Last I tried, about a year ago, it didn't work. Best to re-encode the video using Miro or a similar program and avoid altogether though, right?

**Comment by RoobScoobs** [comment]
Yeah sure, https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

Alrighty I'll try doing that just to play it safe

**Comment by jrhorn424** [comment]
@RoobScoobs Is this resolved?

**Comment by gaand** [comment]
@ga-wdi-boston/core Closing after cohort end.
