### ISSUE TITLE
Exceeds Expectations Requirements

### ISSUE THREAD

**Issue by MishaHerscu** [ga-wdi-boston/group-project#149]
I think that the requirement of having no user facing bugs to exceed expectations is too stringent.

In the real world, development and deployment are iterative processes and bugs are uncovered and fixed continuously.

Exceeding expectations should be more about having a breadth and depth that goes beyond the project requirements to a significant degree, meaning more features produced as well as a higher degree of difficulty in the engineering for at least some of the features. Creativity should also be a part of it, as should the professionalism of the client UX.

I know you don't want people biting off more than they can chew and shipping projects that are very buggy and unprofessional, so I do think QA is important. However, the rule should not be that exceeding expectations requires zero user facing bugs. Rather, It should be that the level of QA is very high, with few user facing bugs, and none which render the site unusable or greatly diminish the UX, and it should ultimately be up to the discretion of the teaching staff to determine if a project exceeds expectations despite small bugs.

**Comment by MishaHerscu** [comment]
@jrhorn424

**Comment by gaand** [comment]
@MishaHerscu The number of features you can implement in the time provided is small.  A single user facing bug demonstrates that the level of QA is not high.

**Comment by MishaHerscu** [comment]
@gaand I can see that a single user facing bug in a small project (one that only minimally meets requirements) shows a low level of QA because a high percentage of features have bugs in that scenario. However, as the number of features grows, the importance of one bug should get smaller, if you agree with using the percentage of the UX that is buggy as a metric of QA for the sake of argument.

I think the scenarios are as follows if feature set "A" meets requirements minimally, and additional features are incremental improvements:

* A meets expectations, but certainly does not exceed
* A + B with a buggy B does not exceed because it doesn't really add and introduces bugs
* A + B + C + ...  would exceed if there are no bugs as the features get more complicated and the application grows. *This is the typical exceeds scenario*
* A + B + C + ... + to infinity, with one small UX bug, would exceed because the percentage of the UX that has bugs would go to zero as the feature set goes to infinity *this is the problematic case*

If you agree with that, then, you should also agree that there is a finite point at which a project with one small UX bug still exceeds expectations because, if you agree with the asymptotic argument, then there is actually a finite point where the bugginess percentage is low enough to round to zero, since we are just talking about approaching infinity as there can't actually be infinite features.

Otherwise, you would have to stand by the position that someone submitting 2B+ lines of code that is a superior copy of all of Google and also plays tic tac toe does not exceed, because of a bug in their version of Google+ UX, or something like that.

It seems like the teaching staff (you) should have discretion in where the cutoff is, but it seems hard to argue that any bug has the same importance no matter how big a project is.

**Comment by MishaHerscu** [comment]
A separate clarification - do authentication bugs count as UX bugs?

**Comment by gaand** [comment]
@MishaHerscu If you attempt 27 features in a 3 day sprint, then I believe you are doing it wrong. 

Also, the requirement includes the word obvious.  So, if a button doesn't work, that's obvious.  Buttons should be tested and working.  A subtle bug would not necessarily prevent a team from receiving an exceeds.

I'm not sure what you mean by "authentication bugs".

**Comment by MishaHerscu** [comment]
@gaand Ah okay, that all makes sense.

The auth bug thing is that no normal user would notice a problem, but maybe someone with a curl request could do something that the client would not allow, like access another user's records.

**Comment by gaand** [comment]
Ah, I see. I think the prompt requires ownership of data, so the auth bug would likely prevent meeting expectations.

**Comment by MishaHerscu** [comment]
Ah yeah, that is right.
Thanks,
Misha

**Comment by gaand** [comment]
Closing as moot.
