### ISSUE TITLE
ES6 errors after Npm Install

### ISSUE THREAD

**Issue by natGalynker** [ga-wdi-boston/group-project#153]
Both @cdelsoin and I are having ES6 linter errors. I removed the directories, checked for updates in packages and atom, completely shut down/closed atom before recreating the repos locally and npm installed again. @jordanallain created the repos from the js-template and express-template. It seems really silly but having 40+ linter errors in one file makes it more difficult to fix the errors that are relevant.

errors say:

Use the function form on use strict, then there are 45 other errors in one file saying const is available in ES6(use esversion: 6) or Mozilla JS extensions(use moz)
also does the same for arrow function syntax, let, and object short notation etc.

**Comment by RealWeeks** [comment]
Can you link your repo, the one in question?

**Comment by natGalynker** [comment]
https://github.com/JusticeLeagueAlpha/bucket-list-api. There are also errors in https://github.com/JusticeLeagueAlpha/bucket-list-project but we are currently working on the api.

**Comment by RealWeeks** [comment]
Looks like you're missing some files

**Comment by RealWeeks** [comment]
look at the hidden files that jordan has on his local and the files on the repo.  You can create those same files in the root of your directory or check them out from the template

**Comment by gaand** [comment]
If @jordanallain runs git status in his copy of the repository, does it show untracked dot files?

**Comment by natGalynker** [comment]
@jordanallain  is now having the same errors that we are having. It seems like config is appearing in his root of local but not ours for some reason. when he does git status the only untracked files is .env

**Comment by gaand** [comment]
Did @jordanallain unzip the template then copy the files to a directory?  This would not copy the dot files by default.

**Comment by BenGitsCode** [comment]
@J-Weeks @gaand I hope it's okay I pop in here. I'll remove this if it isn't.

There is a known atom linter [issue](https://github.com/AtomLinter/linter-jshint/issues/237) with not recognizing ES6 syntax.  It sounds like there may be a git issue at play as well, but they're not necessarily connected. 

As far as the ES6 errors, creating a ```.jshintrc``` file in your project root that defines the ES version as 6 as such ```{ "esversion": 6 }``` should resolve the jshint es6 issues in atom. Creating that file in a parent of your working directory will save you from repeating the process per project.

i.e. wdi/project/working directory placing the file in the project directory would fix the jshint issue for development in any children of project.

**Comment by natGalynker** [comment]
Looks like there was a mishap with how the repos were created. We went back and unzipped, and created remote upstreams to ensure all the hidden files came through when local versions were created. A-OK!
