### ISSUE TITLE
Should we be using roles for users?

### ISSUE THREAD

**Issue by jlmitch1989** [ga-wdi-boston/group-project#155]
So we need to setup our ecommerce site where only Admins can create the products on our page. I have been looking at some MongoDB documentation on the subject of adding certain roles to users.  Should we be doing user capabilities this way or making admins completely separate from users?

**Comment by RealWeeks** [comment]
What does the mongo documentation say you should be doing? I don't quite fully understand your question.

**Comment by jlmitch1989** [comment]
Here are the docs, I've been looking at: https://docs.mongodb.com/v2.6/tutorial/add-user-administrator/

We have been trying to figure out how to make our Admins be the only people that can create monsters to display on our ecommerce site.  Then users should only be able to see, select which ones they want, and checkout.  We don't want our users to have the capability to add things to the website.  

So what I'm getting from the docs is that instead of having Admins being separate from users, users can just have certain privileges(such as: read or read/write) for specific collections.  You can set this up by giving certain roles to a user(such as roles: userAdminAnyDatabase).

**Comment by gaand** [comment]
I suggest you add a Boolean attribute to User called admin and disallow admin actions when it's false.

**Comment by jlmitch1989** [comment]
So you're saying we shouldn't have Admin separate from users?

**Comment by jlmitch1989** [comment]
Because as of right now, we have a users model and admin model.  Should we only have a users model with a Boolean attribute to User called admin?

**Comment by RealWeeks** [comment]
Yes, that thing that Antony said.

**Comment by jlmitch1989** [comment]
So when we add this Boolean attribute to user, how are we actually signifying user Admin=true?  Is that something we have to set through scripts for individual users?

**Comment by gaand** [comment]
Usually you create an admin user on the server and set the flag there. In code, only an admin user can make an admin user.  You probably only need one admin for the project.

**Comment by jlmitch1989** [comment]
We added a boolean value to the user schema and deleted the seperate admin schema.
