### ISSUE TITLE
Accessing MonogoDB 

### ISSUE THREAD

**Issue by NatasaPeic** [ga-wdi-boston/group-project#160]
We need to set our admin for our app. Our monogoose schema has boolean value that is set to false by default for everyone that tries to sign up. 

When we worked locally, I was able to set admin through Monogo shell. Once app is deployed, that is gone. 

We have no success in finding how to set up admin on live app. 

I created a user on Monoglab, and accessed it in my terminal, but can't set admin.

I know images shouldn't be posted, but I need to show you how I set it. 

<img width="1133" alt="screen shot 2016-09-07 at 2 41 51 pm" src="https://cloud.githubusercontent.com/assets/19355037/18324198/43f3d794-7509-11e6-90ce-58cd72585c76.png">

```
~/wdi/projects/ecommerce-back (master)$ mongo ds019826.mlab.com:19826/ecommerce-back -u project3-squad2@gmail.com -p 1
MongoDB shell version: 3.2.9
connecting to: ds019826.mlab.com:19826/ecommerce-back

rs-ds019826:PRIMARY> show collections
Cannot use 'commands' readMode, degrading to 'legacy' mode
system.indexes
users
rs-ds019826:PRIMARY> use users
switched to db users
rs-ds019826:PRIMARY> db.users.find();
Error: error: { "$err" : "not authorized for query on users.users", "code" : 13 }

```

**Comment by NatasaPeic** [comment]
This is what I don't understand.

```
Cannot use 'commands' readMode, degrading to 'legacy' mode
```

**Comment by NatasaPeic** [comment]
I created another user with readMode checked. Still no success.

**Comment by RealWeeks** [comment]
have you seen/ tried this: http://docs.mlab.com/connecting/ ?

**Comment by NatasaPeic** [comment]
Made it!!!!!

**Comment by RealWeeks** [comment]
Nice! Please write up a solution and close your issue when ready.

**Comment by NatasaPeic** [comment]
Ok! I accessed through Heroku. MonogoLab add-on. I set our user to ADMIN!!

<img width="774" alt="screen shot 2016-09-07 at 3 25 04 pm" src="https://cloud.githubusercontent.com/assets/19355037/18325493/7541dba6-750f-11e6-94f2-3324aafa51d6.png">
