### ISSUE TITLE
1:1 working with Google API

### ISSUE THREAD

**Issue by natGalynker** [ga-wdi-boston/group-project#161]
Can I get a 1:1 for working with googles API. I have been doing a lot of research on using it but I think I am missing something and am now finding myself confused, I specifically am trying to implement their autocomplete functionality. I have looked at a few JSfiddles and stackoverflows on this issue also and I am not sure what I am missing. It could be as simple as misunderstanding the documentation, I would really appreciate any insight

**Comment by RealWeeks** [comment]
What have you tried so far?

**Comment by natGalynker** [comment]
I have npm installed the google api node module (using --save),

set googleplaces variable to that module

whenever google.maps...etc is being used by communicating with the API I added googlesplaces onto that

In the html I have verified that I have changed the id attached to the input field to pac-input which seems to be dependent in order for the auto complete to work.

I have used this and 2 other JsFiddles as references:

http://jsfiddle.net/QW59W/107/

I have watched the guides on the google places API documentation.
which included a video guide

**Comment by natGalynker** [comment]
here is the video https://developers.google.com/maps/documentation/javascript/places-autocomplete

**Comment by RealWeeks** [comment]
Be specific, when you tried to implement what errors are you getting?

**Comment by jordanallain** [comment]
we're not getting any errors currently

**Comment by natGalynker** [comment]
could this be that we aren't accessing the API KEY properly? I set the key in .env on the api back end

**Comment by RealWeeks** [comment]
@natGalynker That sounds correct to me.  Have you tested in your chrome console to make sure that nothing is happening with the 3rd party API?

**Comment by RealWeeks** [comment]
If nothing is happening then it sounds like the API key is not being accessed.

**Comment by natGalynker** [comment]
We didn't use an API key, but we got it anyway. Thanks Jason!

**Comment by natGalynker** [comment]
It broke when we redeployed. I guess it is not grabbing the key after all. How can I assure that it is? I got an API key from google. set it with:

export GOOGLE_PLACES_API_KEY =<insert key here> in .env 

I tried hardcoding the code into the html, which I know we never want to do, and setting it to GOOGKE_PLACES_API_KEY

with SECRET_KEY and setting to a variable using $TOKEN

I am thinking that is the step that I am missing, setting the the API key to a variable.

**Comment by natGalynker** [comment]
How do I ensure that the API_KEY is getting passed through, since .env gets ignored I have not been able to find any commands that pushes though .env for google api keys

**Comment by J-Weeks** [comment]
Try to heroku GUI.  You can configure your settings in the browser, heroku.com > settings

**Comment by RealWeeks** [comment]
Try this one: http://bfy.tw/7aeC

**Comment by jordanallain** [comment]
we have it set in the back end we are just unable to grab it from the front end, am i missing something in that link?

**Comment by RealWeeks** [comment]
I'm just being terse. There is a Heroku GUI on the site you can also set these things on, try that.

**Comment by natGalynker** [comment]
We had already done that, 4 hours ago at least

**Comment by natGalynker** [comment]
Something is not connecting between the back and the front end. I have the script links which the google docs say to use and add in the API_KEY but when we use those scripts with the API_KEY it is not working. We attempted accessing the variable on the front end, but nothing we have tried has worked.

**Comment by laurenfazah** [comment]
So you're making the API call from the front end? If the API key is set on the back end, your API call should be made by the back end. Some controller action should make the API call and be wired to a route that the front end could call.

**Comment by gaand** [comment]
Closing after end of cohort 013.
