### ISSUE TITLE
upload error after deploy

### ISSUE THREAD

**Issue by EchoXin** [ga-wdi-boston/group-project#162]
Here is the error from console when upload files. and i already set the aws-access-id and key to heroku

POST https://floating-tundra-60505.herokuapp.com/files 500 (Internal Server Error)
Object {readyState: 4, responseText: "{"error":{"message":"Missing required key 'Bucket' in params"}}", responseJSON: Object, status: 500, statusText: "Internal Server Error"}

**Comment by laurenfazah** [comment]
Is `Bucket` set? `Missing required key 'Bucket' in params"}`

**Comment by EchoXin** [comment]
AWS_ACCESS_KEY_ID:  
AWS_SECRET_ACCESS_KEY: 
CLIENT_ORIGIN:  
CLIENT_URL:  
MONGODB_URI:  
S3_BUCKET_NAME:  
SECRET_KEY:            

i think so,  here is the things I set to heroku

**Comment by gaand** [comment]
Please post the code used to set the `Bucket` key.

Also, please post the output of `heroku config:get S3_BUCKET_NAME`.

**Comment by EchoXin** [comment]
heroku config:set AWS_ACCESS_KEY_ID=<ID> AWS_SECRET_ACCESS_KEY=<KEY>

output: echoxin

**Comment by gaand** [comment]
I meant the code in the express api that sets the key `Bucket` in the params object passed to `s3.upload`.

**Comment by EchoXin** [comment]
let params = {
      ACL: 'public-read',
      Bucket: process.env.AWS_S3_BUCKET_NAME,
      ContentType: options.mimetype,
      Key: `${folder}/${basename}${ext}`,
      Body: stream,
    };

**Comment by gaand** [comment]
``` diff
- Bucket: process.env.AWS_S3_BUCKET_NAME,
+ Bucket: process.env.S3_BUCKET_NAME,
```

or 

``` sh
heroku config:set AWS_S3_BUCKET_NAME=echoxin
```

I suggest the latter.

**Comment by EchoXin** [comment]
that  works, thank you so much
