### ISSUE TITLE
One-on-one Request

### ISSUE THREAD

**Issue by viohlet** [ga-wdi-boston/group-project#166]
Hi @jrhorn424 @payne-chris-r @berziiii 

Co'de Grace kindly requests a one-on-one to cover modeling and questions regarding the issues below.
- Multiple databases?
- Mixing SQL and Mongo?
- Facebook/Google signin?
- Deploy front-end to Heroku as well?
- <iframes> embedding websites/YouTube
- Testing Javascript

Thank you for your guidance!

**Comment by jrhorn424** [comment]
I have some surface thoughts I can share here. Would you like to meet Monday morning or do a conference call sooner?

> Multiple databases? Mixing SQL and Mongo?

This is called "polyglot databases" and Martin Fowler has written a lot about their strengths and weaknesses if you'd like to do some reading.

The basic idea is to store relational data in SQL, and store documents in Mongo. When documents need to be related (not every entity has to have a relationship), then you can store the Mongo ID inside a table name that matches your Mongo collection name. Then, when you retrieve those Mongo IDs through SQL, you can query for individual records in your Mongo collection.

We'll need to see your modeling, user stories, and wireframes to provide more specific advice on whether or not it's a good idea for you app.

> Facebook/Google signin?

This is almost always more trouble than it's worth for an MVP, one-week sprint.

> Deploy front-end to Heroku as well?

If you wish, but you'll need to put it behind an express server with a glob route. GitHub Pages will be simpler.

> embedding websites/YouTube

Most of the time I've seen others use plugins for this. Let's talk about your use cases.

> Testing Javascript

Libraries you'll want to look into: Mocha and Chai. Jasmine is also good for front-end testing and may be easier to get started with. However, testing the backend with Jasmine can be painful, so I recommend staying away from it for your API.

**Comment by jrhorn424** [comment]
@viohlet Let us know when you're ready and we'll meet with you. I'd like you to go over my comments with your group first.

**Comment by viohlet** [comment]
Hi @jrhorn424 we are ready anytime this morning. Let us know your availability; we are 2C but can come to you.

**Comment by payne-chris-r** [comment]
@viohlet we're ready for you in Classroom 1 when you're ready to chat about modeling.
