### ISSUE TITLE
chardeemcdennis requests a one-on-one

### ISSUE THREAD

**Issue by knoddin** [ga-wdi-boston/group-project#167]
Hi! We'd like to schedule a one-on-one for Monday to discuss our ERDs and wireframes. Thank you! 
Ben L., James, Will, and Katie

**Comment by jrhorn424** [comment]
You got it! Link them here if you get the chance. Thanks!

**Comment by payne-chris-r** [comment]
@jrhorn424 if you're looking for something to do this afternoon: https://vimeo.com/150549016

**Comment by james-coombs** [comment]
ERD:
![20161015_144856](https://cloud.githubusercontent.com/assets/21044297/19441412/a6d46072-9453-11e6-8673-e3b430b9fa97.jpg)

**Comment by jrhorn424** [comment]
@james-coombs would you mind flipping that? You can just edit your original post.

**Comment by james-coombs** [comment]
Wireframe:
![20161015_162741](https://cloud.githubusercontent.com/assets/21044297/19441574/2352f384-9454-11e6-9976-234ed3b5723f.jpg)

**Comment by payne-chris-r** [comment]
@knoddin who are the sweaters for?!?

**Comment by knoddin** [comment]
@payne-chris-r  you know, turtles

**Comment by jrhorn424** [comment]
Woohoo! That was fun. If you want to share any notes, feel free. I'm going to go ahead and close this, though.
