### ISSUE TITLE
Best place to attach event handlers when using Handlebars?

### ISSUE THREAD

**Issue by rhjones** [ga-wdi-boston/group-project#169]
(Accidentally messaged the whole forum channel on Slack, which prompted a comment from @jrhorn424—decided to move this here in case people are interested and to avoid back-and-forth in the channel.) 

The Spectacles (@JaimeGaribaldo7, @styletab, and I) were talking today about the best place to attach event handlers when using Handlebars templates/partials.

Using something like this:

``` js
$('#sign-up').on('submit', onSignUp);
```

in the `addHandlers()` method in an `events.js` file and running that method from inside `$(() => {...});` in `scripts/index.js` only works if the `#sign-up` element is present in the DOM when the page loads. This works if you're putting every piece of HTML in your `index.html` file, but not if you're using Handlebars to render different views/chunks of HTML on the fly—the event gets attached to nothing, basically.

In my last project, I put a wrapper div in `index.html` and attached all events to that div, like so:

``` js
$('.view').on('submit', '#sign-up', onSignUp);
```

That allowed me to render different Handlebars templates when I wanted/needed to without worrying about broken event handlers. But now I'm looking at [this article](https://www.sitepoint.com/jquery-body-on-document-on/), which suggests that it's fastest (in cases like these) to attach events to `$(document.body)`.\* This surprises me a bit—I would have assumed there'd be a bit of a performance hit to attaching everything to the document body, but maybe not?

Another potential approach is to attach these events immediately after rendering the relevant Handlebars template. This has the benefit of allowing us to register events on the specific target elements we want, rather than attaching a ton of stuff to a parent element. A drawback is that you're no longer able to see all of your event handlers for a particular feature in the same place; instead, they're spread out across different functions in your `ui.js` file for that feature.

Wondering if there's a preferred approach here. 

_(*For people following along: I said `$(document)` in Slack, which is wrong/slower. Sorry!)_

**Comment by gaand** [comment]
Does anything prevent you from rendering the handlebars template that has the id like `#sign-up` and just not showing it until you're ready?  The example seems to be pretty static html that you just want to keep somewhere other than `index.html` or am I missing something?

I'm not claiming this is better, but I'm curious about your perspective.

**Comment by rhjones** [comment]
Only the desire to keep `index.html` clean/not to include a bunch of hidden content. This 100% may be a misguided desire when it comes to static content (it feels tidier, but I don't know that there's any other real benefit), but I think the question still stands for dynamic content—for example, attaching event handlers to links for editing or deleting some record in the database. Those links won't exist until a user has created that record, so I think (?) we'll need to attach an event handler somehow.

**Comment by gaand** [comment]
But why does my suggestion make index.html less clean?  You can have target elements(e.g. an empty div) for the sign up, sign in, change password. and render the handlebars templates on load and put the result into that div.  If that doesn't make sense I'm happy to explain in more detail.

For dynamic content, you'll still have a target for the rendered content and that is where you should attach the handlers (following your proposed scheme - I'm happy to talk through alternatives if yo're interested). jQuery let's you attach handlers with additional scope so if you're using the same target for different data it still might be relatively clean, see: http://api.jquery.com/on/

**Comment by rhjones** [comment]
My thinking was that if you include multiple target divs in `index.html` for different pieces of content, you end up with a bunch of empty divs on the page unrelated to the content you care about during any single particular state—sign up/sign in divs that you don't need after you've already authenticated, etc. I realize this is a very small problem (and perhaps not even a problem) in the grand scheme of things, so thanks for indulging my thought process. We'll plan on doing it the way you suggested for the static pieces, and using selectors with `.on()` for the dynamic bits. Thanks!

**Comment by gaand** [comment]
For the static bits, you could have a single element, e.g. `<div id="static"></div>` and load all of them into it.
