### ISSUE TITLE
lewdFractals requests a one-on-one

### ISSUE THREAD

**Issue by laurenallegra** [ga-wdi-boston/group-project#170]
Hey there, @jrhorn424 @payne-chris-r @berziiii

Hope you all had a nice weekend.

lewdFractlals (Lauren, @bullhead242, @chrxtina, @rosmith76) kindly requests a one-on-one to cover the following topics:

-Clarification on project prompt, regarding "visitors," and a couple of other small things
-Re-deploying to gh-pages: rebasing, redeploying on multiple group-members computers, etc.
-Clarification on virtual properties 

We are available to meet anytime on Monday.

Thank you!
Christina, Robbe, Pete, & Lauren

**Comment by jrhorn424** [comment]
@laurenallegra, @bullhead242, @chrxtina, @rosmith76

Let's meet immediately after lunch. Let us know where you are located.

We'd also like to have a look at your user stories, wireframes, and ERDs. Could you add them here as images or links when you get a moment? Thanks!

**Comment by bullhead242** [comment]
After lunch is great. 1pm?

![img_20161014_174302326](https://cloud.githubusercontent.com/assets/21027137/19444715/9048a92e-945f-11e6-9808-0753c7d73bda.jpg)
![img_20161014_174306915](https://cloud.githubusercontent.com/assets/21027137/19444712/8ffc650a-945f-11e6-8b2a-743a46f92e3d.jpg)
![img_20161014_181546703](https://cloud.githubusercontent.com/assets/21027137/19444713/8fff06ac-945f-11e6-9b1a-64e90cda72e8.jpg)
![img_20161014_181550154](https://cloud.githubusercontent.com/assets/21027137/19444711/8ff88a20-945f-11e6-983b-4c74ac574aba.jpg)

Will upload photos from our work over the weekend shortly. 

Thanks!

**Comment by payne-chris-r** [comment]
You guys good to close this?

**Comment by bullhead242** [comment]
byebye issue

**Comment by laurenallegra** [comment]
Thanks for your help, @berziiii , @jrhorn424 @payne-chris-r !

lewdFractals is very appreciative 👍
