### ISSUE TITLE
Nodemon Crash After Creating Nested Schema

### ISSUE THREAD

**Issue by bullhead242** [ga-wdi-boston/group-project#171]
Good afternoon!

After looking into our "blog" and "post" relationships, we have decided to create a nested `post` schema which occupies the value of the `post:` attribute. 

```
const post = new mongoose.Schema({
  title: String,
  content: String,
  required: true,
});
```

We have referenced the new schema by placing it inside an array in side the model.

```
const blogSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
  },
  post: [post],
  _owner: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
}, {
  timestamps: true,
  toJSON: { virtuals: true },
});
```

We created the nested schema while referencing [a question on StackOverflow](http://stackoverflow.com/questions/15208711/mongoose-subdocuments-vs-nested-schema) contrasting the pros and cons of a nested Schema. 

As soon as we create the nested Schema, however, nodemon crashes and we are unable to test. Nodemon returns an error asking if we used a nested Schema while saying we can only nest refs or arrays which is inconsistent with [the mongoose documentation](http://mongoosejs.com/docs/subdocs.html#altsyntax). With the error and the documentation conflicting (Mongoose requires a node environment), I'm not sure how to troubleshoot. 

Thanks,
Pete

**Comment by bullhead242** [comment]
update

Trying to adapt to nesting a pure array inside of the pre-existing `Blog` schema. This has, at least, stopped breaking the server, but has provided no meaningful progress. 

```
const blogSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
  },
  _owner: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  post: [
    {title: {
        type: String,
        required: true,
      },
      content: {
        type: String,
        required: true
      },
  }]
}, {
  timestamps: true,
  toJSON: { virtuals: true },
});
```

We are trying to `POST` using the above schema, where the only change is around the creation of the 'post' array by using curl. 

```
curl --include --request POST http://localhost:3000/blogs \
  --header "Authorization: Token token=HkVBJoGxrnYtP8jJnBKbk6UVy4JPZJJ6tF0ApRh8xW8=--jxI07TskgnCcluz+nDO0lNYSPuLQtt+2qzvf92Mj5RE=" \
  --header "Content-Type: application/json" \
  --data '{
    "blog": {
      "name": "I am a blog",
      "post": "[title: "this is the post title", content: "content words stuff things"]",
      "_owner": "req.currentUser._id"
    }
  }'
```

The previous request, which was working and could be referenced and added to from our client is very similar with the exception of the added `POST` array. 

```
curl --include --request POST http://localhost:3000/blogs \
  --header "Authorization: Token token=HkVBJoGxrnYtP8jJnBKbk6UVy4JPZJJ6tF0ApRh8xW8=--jxI07TskgnCcluz+nDO0lNYSPuLQtt+2qzvf92Mj5RE=" \
  --header "Content-Type: application/json" \
  --data '{
    "blog": {
      "content": "wordswordwords",
      "title": "shit",
      "_owner": "req.currentUser._id"
    }
  }'
```

Inside the current request, we've tried a number of possible formatting solutions, including changing the quotes inside the array (single-quotes to double-quotes changes the color in the linter) and the arrangement of the braces/ brackets and have no meaningful progress. The error messages are _nearly_ identical: one was titled `unexpected token t` and the other `unexpected token i` but provide identical data otherwise. 

Thanks again,
Pete

**Comment by payne-chris-r** [comment]
@bullhead242 please close if this is resolved.

**Comment by jrhorn424** [comment]
Please make this change:

``` diff
-   post: [
+  posts: [
```

**Comment by jrhorn424** [comment]
You really should also be making your curl request to a posts controller when doing "CRUD" on a post:

``` diff
- curl --include --request POST http://localhost:3000/blogs \
+ curl --include --request POST http://localhost:3000/posts \
```

**Comment by bullhead242** [comment]
Currently working around this issue by formatting the property nesting differently. Will re-open and update if we run into similar issues.
