### ISSUE TITLE
4-on-1 Request: Synergistic Deepities

### ISSUE THREAD

**Issue by kopius** [ga-wdi-boston/group-project#176]
Synergistic Deepities would like to request a meeting with an instructor tomorrow afternoon to demo our FileBucket app. We've taken the prompt in a unique direction, and while we're confident that we will meet expectations, it would be great to get an instructor's eyes on our project before presentation day.

**Comment by jrhorn424** [comment]
Great, thanks @kopiusmaximus.

@berziiii @payne-chris-r I'd like us all to be there to provide our thoughts.

**Comment by kopius** [comment]
@jrhorn424 What time works well for you? How about 2pm?

edit: Just saw your calendar invite. See you at 3:00pm!
