### ISSUE TITLE
[MongoDB] 500 internal server error when adding query to .find() method

### ISSUE THREAD

**Issue by DanielJRaine** [ga-wdi-boston/group-project#177]
When we try to perform an index action, `Task.find( )`, in our case, the server successfully shows us every task in our database, from all users.

As soon as we try to give it a query parameter, it sends us a 500 internal server error.  We have tried MANY iterations of queries, but none of them have solved our problem, and it has gotten to the point where we are running out of new ideas to test.  Our index action currently looks like this:

```
const index = (req, res, next) => {
  Task.find({ _owner: { $eq: req.currentUser._id }})
    .then((tasks) => {
      return res.json({ tasks });
    })
    .catch(err => next(err));
};
```

**Comment by jrhorn424** [comment]
When you say query parameter, do you mean `req.params` or do you mean querying by owner?

**Comment by jrhorn424** [comment]
In any case, please post a copy (or link to) your full controller.

**Comment by DanielJRaine** [comment]
Querying by _owner.  If we pass an empty { } into Task.find( ), it returns everything.

Here's our controller https://github.com/Code-Grace/bucket-list-api/blob/master/app/controllers/tasks.js

**Comment by jrhorn424** [comment]
That query looked surprising. I would have tried this, instead: `Task.find({ _owner:  req.currentUser._id })`

Also, you will continue to get 500s until you fix this line:

```
  { method: authenticate, except: ['index', 'show'] },
```

`currentUser` isn't defined for the `index` action.

**Comment by hantungy** [comment]
We had it like that originally, just like in the examples

```
  let tasks = { _owner: req.currentUser._id };
  Task.find(tasks)
```

We added $eq because we thought it might have been an ObjectId conversion issue. But that doesn't seem to be the case now.

**Comment by jrhorn424** [comment]
Did you make the other change I asked for? Did it work?

**Comment by DanielJRaine** [comment]
I just removed 'index' from our authenticate, except block, and it now works!  Thanks!
