### ISSUE TITLE
[Promises] Not 'catching' errors from failed jQuery AJAX calls?

### ISSUE THREAD

**Issue by tuckyeah** [ga-wdi-boston/group-project#179]
We're currently working on adding some kind of UI indicator for when a user gets an error from the server.

We've promisified our AJAX calls, but it seems that, no matter what, any rejections never make it all the way down the chain to the .catch. 

This is what the signUp AJAX promise looks like (in auth/api.js) 

```
const signUp = function(data) {
  return new Promise((resolve, reject) => {
    return  $.ajax({
      url: app.host + '/sign-up',
      method: 'POST',
      data: data,
      success(data) {
        resolve(data);
      },
      failure(jqxhr) {
        reject(jqxhr);
      }
    });
  });
};
```

And then this is what the promise chain looks like for sign in (in auth/events.js)

```
const onSignUp = function(event) {
  event.preventDefault();
  let signUpData = getFormFields(event.target);
  api.signUp(signUpData)
    .then((data) => {
      console.log('before auto sign-in, data is:', data);
      console.log('and signUpData is:', signUpData);
      return api.signIn(signUpData);
    })
    .then((data) => ui.onSignInSuccess(data))
    .then(api.getAllUsers)
    .then((data) => ui.sidebarSuccess(data))
    .catch(console.error);
};
```

I've tried replacing that `console.error` statement with a custom function, both one in the UI and one in the same document, but none of them ever seem to fire. The only thing I get is a standard rejection from the server, but no custom messages, or no ability to do anything on reject...

Any suggestions?

**Comment by jrhorn424** [comment]
Can I see the definition of `getAllUsers`? I suspect something isn't being returned or resolved there correctly.

Also, try this:

``` diff
-    .then(api.getAllUsers)
+    .then(() => api.getAllUsers())
```

**Comment by jrhorn424** [comment]
Check for `return`s in all the other functions in that chain as well.

**Comment by tuckyeah** [comment]
Interesting!!

We ended up being able to resolve it by changing the way the 'failures' were handled in the AJAX calls:

We replaced the `failure(jqxhr) { reject(jqxhr) }` with the following code:

```
const signUp = function(data) {
  return new Promise((resolve, reject) => {
    return  $.ajax({
      url: app.host + '/sign-up',
      method: 'POST',
      data: data,
      success(data) {
        resolve(data);
      },
      error(jqxhr, textStatus, errorThrown) {
        reject({
          jqxhr: jqxhr,
          textStatus: textStatus,
          errorThrown: errorThrown
        });
      }
    });
  });
};
```

This did resolve all of our issues at present, but we'll take a peek at the getAllUsers just in case :)

Thanks!
