### ISSUE TITLE
Collaborate with designer(s) 

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/group-project#182]
If there's a UXDI cohort at the same time, or graduating slightly earlier, assign some designers to groups.

**Comment by gaand** [comment]
I'm not sure we should "assign" a designer.  Natasha has expressed interest in having her students work with our developers, but we may want to limit it to an optional activity.

**Comment by jrhorn424** [comment]
We've discussed this multiple times. In any case, I don't believe this should be tracked here. There is an ongoing discussion at `meta` or `instructors`.
