### ISSUE TITLE
Survey prompt Clarification

### ISSUE THREAD

**Issue by jdaly04** [ga-wdi-boston/group-project#184]
Our squad wants to be 100% certain on requirements as we're building out our development process. We've checked closed issues and are not seeing anything particularly helpful. 

Our main questions regard data collection from survey responses. 
1) Are they any requirements in terms of what's done with the data collected from survey responses or is that open to our squad's interpretation / decisions? 
2) Related to the first question, do you need to be authenticated (signed in) to respond to a survey, or is that entirely our decision as well? We think no, that would then require us to have CRUD actions for 3 categories (Survey, User, SurveyTakers) which seems large in scope.

Our squad is in the front lobby by Front Lines should you want to talk in person about this.

Thank you! 
Squad 1 (Julia, Ryan, Joel)

**Comment by neugierige** [comment]
Hi Julia. I had interpreted [the prompt](https://github.com/ga-wdi-boston/group-project/blob/master/prompts.md#survey) to mean that if a user is the creator of surveys, he/she should be able to log in and see a list of all the surveys he/she has conducted, and subsequently view the results presented in a logical and readable way (i.e. a list of responses under each question). 

As for your 2nd question, I think you answered your own question!

**Comment by BenGitsCode** [comment]
Hey squad,

I think you've answered both of your questions as you asked them, particularly the second, so let's start there. Does that make more sense to the user? I think so. In fact, I think requiring a sign in to respond to a survey would be the best way to get less responses. Speaking for myself here, but if I need to create an account for even a 2 minute survey, I won't bother with it.

I think the technical requirements and necessary deliverables [here](https://github.com/ga-wdi-boston/group-project#necessary deliverables) clear that up well, but please reread them carefully and feel free to ask another question if anything there is unclear. 

You need CRUD actions for at least one model, which model is totally up to you.

**Comment by jdaly04** [comment]
Awesome! Thank you both for your input. We've decided to stick with:
1) Voting / Answering a survey does NOT require authentication.
2) A user that has created a survey can view associated responses. 

Thanks for the input @neugierige @BenGitsCode 

cc @jbuzzanco @RpRoderick

**Comment by payne-chris-r** [comment]
Agreed with your resolution, please close this when you get a chance since it sounds like it's been resolved!
