### ISSUE TITLE
Group having Rebase and merging problems

### ISSUE THREAD

**Issue by Sphilippe7** [ga-wdi-boston/group-project#185]
Can an instructor give us a quick 5min display of the proper way to rebase and merge. We are trying to get our project workflow together.

**Comment by BenGitsCode** [comment]
[please review this](https://github.com/ga-wdi-boston/project-issue-tracker-guide#how-to-use-the-issue-tracker)

**Comment by akradin** [comment]
Alright so we have been working for the past hour or so on getting our work flow down so we can work effectively.

We are struggling to determine when is the best time to rebase. We have gone through the Atlassian instructions and the group project workflow repo to determine how we should do this but we are hitting a wall.

We figured we would try to start small - I commented out some stuff in the backend and then my group was able to pull the changes successfully and see them...but there was no rebasing involved.

Currently we are working on rebasing in the front end so we can better see changes that have been made. I am working on a branch called HTML and Kevin is working on a branch called CSS. We both have made changes. Kevin has pushed the changes he has made to the CSS branch. Should he merge that branch to development and if he does, how do I see the changes that have been made?

**Comment by BenGitsCode** [comment]
Please comment on this issue with some of the new insights into how your squad plans to implement your projects git workflow.

**Comment by akradin** [comment]
Hey Ben,

So we have made some progress. Stanley made a change to his index.html file and made a pull request. Kevin approved the request and merged it into dev. He then pushed the dev branch. So this is what we did:

1. Person make changes on a feature branch
2. person decides those changes are done
3. person makes a pull request on github
4. Under the pull request drop down menus
	- for base you choose whatever branch you are working on
	- for compare you chose whatever branch you want to merge into (usually dev)
5. YOU TELL THE GROUP YOU MADE A PULL REQUEST AND ONLY ONE PERSON ACCEPTS THE PULL REQUEST
6. the person that accepts the pull request goes into terminal and switches to the dev branch and in terminal types in `git pull origin <branch-name> --rebase`
7. the person that accepts the pull request then does git push origin dev
8. everyone else who hasn't pulled will type in `git pull origin <branch-name> --rebase`

We can see the changes we made, it just seems like a lot of pushing and pulling. Are we pulling into the right branch? Should we ideally pull into only dev or whatever branch we are working in?

**Comment by BenGitsCode** [comment]
@akradin Please close this issue if you're satisfied with the resolution I presented.

**Comment by Sphilippe7** [comment]
The instructions above are correct

**Comment by kmg1434** [comment]
So I am having trouble with Github closing the pull request after I pull it. So once I saw 

```sujkid  wants to merge 1 commit into development from curl```

on github, I went to my terminal, ran ```git checkout development``` and ```git pull origin development --rebase```

That should tell Github to close the pull request correct? Well it did not after several refreshes etc. I still ran ```git push origin development``` anyways and everyone else was able to pull the changes to their local computers. Why is github being such a dink?

**Comment by BenGitsCode** [comment]
If this isn’t holding back your progress, move forward and I’ll take a look
at it after lunch :+1:

-- 
*Ben Adamski | Developer in Residence*
General Assembly Boston | 125 Summer Street, Boston MA 02210
ben.adamski@generalassemb.ly | xxx-xxx-xxxx |

On December 16, 2016 at 11:02:29 AM, Kevin Grady (notifications@github.com)
wrote:

So I am having trouble with Github closing the pull request after I pull
it. So once I saw

sujkid wants to merge 1 commit into development from curl

on github, I went to my terminal, ran git checkout development and git pull
origin development --rebase

That should tell Github to close the pull request correct? Well it did not
after several refreshes etc. I still ran git push origin development
anyways and everyone else was able to pull the changes to their local
computers. Why is github being such a dink?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/ga-wdi-boston/group-project/issues/185#issuecomment-267627027>,
or mute the thread

**Comment by kmg1434** [comment]
Uhhhh we're pretty dang confused right now.

Some of us have a ```dev``` branch and some of us don't. Some of us have a ```development``` branch and some of us don't. Github has both. We don't want the ```development``` branch anymore. 

Our pull requests are now closed, but now we have two more pushes, one on the ```dev``` branch which is fine and one on the ```development``` branch that we want to delete. I'm not sure if just deleting it from Github is a good idea. Any help?

**Comment by BenGitsCode** [comment]
@kmg1434 ping me  here or on slack when you return from lunch.

**Comment by neugierige** [comment]
@akradin 
re: your comment from 4:40pm 12/15

> 4. Under the pull request drop down menus
> - for base you choose whatever branch you are working on
> - for compare you chose whatever branch you want to merge into (usually dev)

It is the opposite. `BASE` is the branch you want to merge INTO (i.e. `dev` or `master` or `gh-pages`), and `COMPARE` is the feature branch that has been completed

**Comment by raq929** [comment]
What's the status of this?

**Comment by kmg1434** [comment]
So according to Ben "you're doing everything right, good job!" but I still don't quite understand merge conflicts. UUhhh I guess we can close this but I still have no idea why merge conflicts happen.

**Comment by Sphilippe7** [comment]
Rachel explained merged conflicts to the group
