### ISSUE TITLE
Sign Up Works With Not Matching Passwords

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/group-project#187]
Hey team,

We have gone ahead and gotten auth working, but you can sign-up with non-matching passwords. I will post the code below but here is what we have done to try to resolve the issue:
Look at past HTML and AJAX calls to check  to make sure the front end is working the way it should be
Looked at curl requests for sign-in in the express app to make sure our credentials are configured appropriately
Looked at closed issues
Changed `let user = { email: credentials.email, password: credentials.password };` to 
`let user = { email: credentials.email, password: credentials.password, password_confirmation: credentials.password };` in the users controller.

None of this was successful. Here is some code

```html
    <div class="modal fade" id="sign-up-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign Up</h4>
    </div>
    <div class="modal-body">
        <form class="sign-up-form">
         <div class="form-group">
           <label>E-Mail</label>
           <input type="email" id="sign-up-email" class="form-control" name="credentials[email]" placeholder="Email">
         </div>
         <div class="form-group">
           <label for="exampleInputPassword1">Password</label>
           <input type="password" class="form-control" id="exampleInputPassword1" name="credentials[password]" placeholder="Password">
         </div>
         <div class="form-group">
           <label for="exampleInputPassword1">Repeat Password</label>
           <input type="password" class="form-control" id="exampleInputPassword2" name="credentials[password_confirmation]" placeholder="Password">
         </div>
         <button type="submit" class="btn btn-primary" id="sign-up-submit">Submit</button>
         <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        </form>
        <div class="sign-up-fail"></div>
    </div>
    </div>
    </div>
    </div>
```

AJAX
```js
const signUp = (data) =>
  $.ajax({
    url: config.host + '/sign-up',
    method: 'POST',
    data,
  });
```

**Comment by akradin** [comment]
I also submitted some curl requests to make sure the back end is working the same way and it seems like it is. Both of these requests return 400 bad request.

```sh
API="http://localhost:4741"
URL_PATH="/sign-up"
EMAIL="a@a.com"
PASSWORD="1"
PASSWORD_TWO="1"

curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{
    "credentials": {
      "email": "'"${EMAIL}"'",
      "password": "'"${PASSWORD}"'",
      "password_confirmation": "'"${PASSWORD_TWO}"'"
    }
  }'
```

```sh
API="http://localhost:4741"
URL_PATH="/sign-up"
EMAIL="a@a.com"
PASSWORD="1"
PASSWORD_TWO="123"

curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{
    "credentials": {
      "email": "'"${EMAIL}"'",
      "password": "'"${PASSWORD}"'",
      "password_confirmation": "'"${PASSWORD_TWO}"'"
    }
  }'
```

**Comment by neugierige** [comment]
Alex, where are you guys?

**Comment by akradin** [comment]
Tremont

**Comment by akradin** [comment]
@gaand We checked in with Lu and it looks like it is a back-end issue. She recommended you check it out! Thanks!

**Comment by neugierige** [comment]
@akradin it doesn't look like you need password confirmation. checkout line 51: https://github.com/ga-wdi-boston/express-api-template/blob/master/app/controllers/users.js

**Comment by raq929** [comment]
If you want to fix this, I would add an 
`if(credentials.password === credentials.password_confirmation)`* to the sign-up function in 
`app/controllers/users.js`.  You'll have to send some sort of error response if the passwords don't match. 
I am not sure these variable names are correct. You should check the credentials object to be sure.

**Comment by neugierige** [comment]
@akradin you should try the curl with NO `password_confirmation` at all

**Comment by raq929** [comment]
(I suspect that will work.)

**Comment by akradin** [comment]
@neugierige Yeah I saw that and was thinking of adding an if statement like @raq929 suggested, I just didn't know how to process the error handling and that is when Lu said just escalate the issue to Antony

**Comment by raq929** [comment]
Where are you? I can come take a look.

**Comment by akradin** [comment]
We are in the first conference room, Tremont

**Comment by akradin** [comment]
So, with the help of Rachel we were able to get this working by editing the user controller `signUp` function.

```js
const signup = (req, res, next) => {
  let credentials = req.body.credentials;
  let user = { email: credentials.email, password: credentials.password };
  if(credentials.password===credentials.password_confirmation){
    getToken().then(token =>
      user.token = token
    ).then(() =>
      new User(user).save()
    ).then(newUser => {
      let user = newUser.toObject();
      delete user.token;
      delete user.passwordDigest;
      res.json({ user });
    })
    .catch(makeErrorHandler(res, next));
  }
  else{
    let error = {name: 'ValidationError' };
    makeErrorHandler(res, next)(error);
  }
};
```

This enabled the explicit used of `makeErrorHandler` outside of  the promise chain.

**Comment by raq929** [comment]
MakeErrorHandler returns a function that takes an error. It then checks that it's a validation error, and if so, returns that error with a 400 code. So, you can modify the error object if you want as well. For examples, you might want to add a `message` key that says something like `Passwords did not match`; which you can then display when you get the error on the front end.
