### ISSUE TITLE
Heroku | Not connecting mongodb to heroku

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/group-project#190]
Our group is trying to connect a mongodb which we populated in the command line to heroku. We followed the heroku deployment guide https://github.com/ga-wdi-boston/express-api-deployment-guide and this issue https://github.com/ga-wdi-boston/group-project/issues/222.
Not sure why when we run `heroku restart` , `heroku open` that it shows this error:
`Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.`

 We have a collection `users` with documents within it, and when we go `/users` within the url of `heroku open`,  it still shows nothing. We pushed to heroku master.
Why is the deployed site showing nothing in the database?

**Comment by raq929** [comment]
What commands did you use to populate the database in heroku?
Also, there is no issue 222, which one was it?

**Comment by jbuzzanco** [comment]
Sorry, it is this issue: https://github.com/ga-wdi-boston/capstone-project/issues/222
Created a collection `users` within the command line, then ran this:
```
db.users.insert({
     email: "ryan@",
     password: "123",
     surveys: {
        question : "WhYYYYYYYYY?",
        answers : ["Why Not?", "This is an answer too", "etc"]
     }
 });

```
We set the 3 config vars as well.

**Comment by raq929** [comment]
If you're creating it on the command line, it's on your local machine, not on heroku, unless you did something special to access heroku's database. 

The error on heroku open seems perhaps unrelated.

**Comment by jbuzzanco** [comment]
Ran `heroku addons:create mongolab:sandbox`and changed MONGODB_URI to MONGOLAB_GOLD_URI within all of the project. and commited those changes pushed and restarted heroku master
