### ISSUE TITLE
How do we handle AWS credentials securely while deploying to heroku? Who's credentials to use for group deployment?

### ISSUE THREAD

**Issue by kfili** [ga-wdi-boston/group-project#192]
We were wondering if one of the group members has to allow their AWS credentials to be used for the group's app. If so, are there any recommendations for how to decide who's credentials are used? Or are there any alternatives to hosting files, like the use of ones own server? If AWS, then how does that work with heroku?

**Comment by raq929** [comment]
Yep, I think one of you will have to use your AWS credentials. It's up to you to decide who does it. Just be sure you are not committing any of the secret keys. Technically, yes, you could use your own server, but we can't help you debug that, and also, it's valuable to learn to use a tool that is so widely used in web development. Almost everyone uses AWS (except direct competitors with Amazon, I assume.)
They should be added as ENV variables. 
The only difference this will make in heroku is that you'll have to set a few more ENV variables when you deploy.

**Comment by kfili** [comment]
Thank you. The solution to this issue is in the comment above.
