### ISSUE TITLE
FileBucket Read/Download Requirement Clarification

### ISSUE THREAD

**Issue by coffeeisamazing** [ga-wdi-boston/group-project#194]
The requirement reads as follows: "Ordinary users can only **read/download** a file where as Owners can do anything to the files they own."

I want to clarify that having a "download" option would satisfy this "read/download" requirement. This is not indicating that two separate actions "read" and "download" are required.

**Comment by BenGitsCode** [comment]
I believe that: Read =

**Comment by BenGitsCode** [comment]
I believe that: 
```
Read = As a user, I want the resource rendered into my local client, so I can see/READ it.
Download = As a user, I want to send a request to the server to download said resource to my local machine, through the client
```

Those aren't awesome user stories, but I want you to think of that way. As a user, I like to see what I'm downloading first, be it the resource itself, or a preview of some kind. That said, I'll defer to @payne-chris-r on this. Thoughts?

**Comment by coffeeisamazing** [comment]
> As a user, I like to see what I'm downloading first, be it the resource itself, or a preview of some kind.

They'd be able to see meta data before downloading (e.g. title). This might also not be possible depending on the file type which gets a bit complicated. For example, an image works fine but what about a document with complicated formatting or even an exe?

Our working assumption had been one or the other. We were planning to have buttons next to the files (and their meta data) for download, edit (metadata), and delete. The last two being subject to ownership.

**Comment by coffeeisamazing** [comment]
Visuals can be easier...our current thinking.
![007 - manage my files](https://cloud.githubusercontent.com/assets/14969865/21283182/48876a84-c3cc-11e6-85a6-0c8f96702144.jpeg)

**Comment by payne-chris-r** [comment]
I think either is fine, both is amazing, but ultimately I think it's your call as a team. The importance is on ownership. I would start with what you have, and then think about how you might implement a "preview" for certain types of files.

**Comment by coffeeisamazing** [comment]
Thanks, will proceed with download only. We will consider preview along with other enhancement ideas after minimum requirements are met.
