### ISSUE TITLE
Need Clarification on CMS Team Project Prompt

### ISSUE THREAD

**Issue by kmg1434** [ga-wdi-boston/group-project#195]
From https://github.com/kmg1434/group-project/blob/master/prompts.md the CMS Prompt reads:

"Build an app to build a website! Your app must allow non-technical users to write blog posts **and** pages for the site. When a visitor visits your site, they should see content. When a user logs in, they should see a dashboard that lets them create and edit new posts **or** pages."

So the four of us cannot come up with a single translation of what this paragraph is implying. A "blog post" is obvious; it is a chunk of text with a title owned by a single user. We thought, just like tumblr, facebook, twitter, etc, that a user would have **one** "page" with all of their blog posts contained on it. However, the sentence "When a user logs in, they should see a dashboard that lets them create and edit new posts **or** pages." seems to imply that a user will have **multiple** pages. What would be these multiple pages contain? Does a page contain blog posts? Is this suggesting a user would have multiple pages for different categories of blog posts? (e.g. User4 has 3 pages, one about cars, one about sports, one about fashion, each containing multiple blog posts). Can we get some clarification on this? Does it simply mean "A user can either have multiple pages or multiple blog posts; it's up to you to decide which one they have multiple of"?

This directly leads into our next issue: 
Does each user need it's own URL? (e.g. squad003.github.io/_username_)
Does each page need it's own URL? (e.g. squad003.github.io/_username_._pagename_)

Or could we simply re-fill squad003.github.io with whatever relevant content using UI buttons?

**Comment by payne-chris-r** [comment]
Think about it like `wordpress`. Typically with a CMS you have a blog that gets updated periodically (every day, once a week, etc), but then you also have information about you/your company/organization/etc. that doesn't change as frequently. Not a shameless plug, but a good example: http://november-project.com/
Has a `blog` and a set of information about where to meet, what it is, etc. So "pages" are for information that gets updated infrequently, and a blog is something that gets multiple articles posted to it regularly. Each user should have the ability to add "pages" (like `about me`, `contact`, etc.) AND a blog/blog posts (like `What I did today`, `Why Kale is great`, `Why people that run November Project can't stop talking about why you should join November Project`, etc). They are NOT connected to each other except for the fact that a user has the option of having both.

The answer to your next question is `no`, but you DO need to figure out how you're going to render each user's page(s)/blog. You don't need to implement front end routing (a different URL for each), but that would be sweet. A user should log in, and be directed to their `dashboard` to add a page or a blog post. YOU need to figure out how you want users (and maybe non-users) to be able to view content on other people's pages/blogs.

**Comment by kmg1434** [comment]
Ok that was very helpful and answered all of our questions for now!

I'll open a separate issue for the URL questions when/if we get there. Thank for clarifying, Chris!
