### ISSUE TITLE
Signup| invalid url

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/group-project#197]
We are getting the error. Syntax error, `failed to execute on XMLHttpRequest: Invalid URL. It doesn't get the POST request for signup. We think it is because config is not correct.

```
const signUp = (data) => {
  return $.ajax({
    url: config.apiOrigins.production + 'sign-up',
    method: 'POST',
    data,
  });
};

```

here is config
```
'use strict';

const store = {
  apiOrigins: {
production: 'http://localhost:4741'


}

};

module.exports = config;

```

**Comment by BenGitsCode** [comment]
What would that make your url look like it?

You can decide where, but something is missing a slash in that concatenation.

**Comment by gaand** [comment]
I would say you can't decide where.  The slash goes in one specific place.

**Comment by jdaly04** [comment]
Yes, the "/" should have been on the end of url ("localhost:4741/"). That fixed our error and was a typo on our part. 

cc @jbuzzanco @rproderick
