### ISSUE TITLE
PATCH Issue: "Cannot read property '_id' of undefined"

### ISSUE THREAD

**Issue by jdaly04** [ga-wdi-boston/group-project#198]
We're trying to make our "Change Password" function correctly and are continuing to get the error in the subject lien of this issue.

We believe the problem is stemming from the route we have in our ajax call but have tried changing the url route without any success. We can see that on signInSuccess we're getting back "user._id" so believe the issue is with "config.apiOrigins".

Does anything in the url look incorrect? If so, could you point us in the right direction to fix this?

API.JS / AJAX CALL:
```js
const changePassword = (data) => {
 return $.ajax({
   url: config.apiOrigins.host + '/change-password/' + config.apiOrigins.host.user._id,
   // url: config.apiOrigins.production + 'change-password' + config.apiOrigins.production.user.id,
   method: 'PATCH',
   headers: {
     Authorization: 'Token token=' + config.apiOrigins.host.user.token,
     // Authorization: 'Token token=' + config.apiOrigins.production.user.token,
   },
   data,
 });
};
```
CONFIG.JS FILE:
```js
'use strict';

const config = {
  apiOrigins: {
      // production: 'https://localhost:4741/'
      host: 'http://localhost:4741/',
    // production: 'https://powerful-garden-17029.herokuapp.com/',
  },
};

module.exports = config;
```

CURL REQUEST:
```js
API="http://localhost:4741"
URL_PATH="/change-password"

curl "${API}${URL_PATH}/${ID}" \
 --include \
 --request PATCH \
 --header "Authorization: Token token=${TOKEN}" \
 --header "Content-Type: application/json" \
 --data '{
   "passwords": {
     "old": "1234",
     "new": "4321"
   }
 }'

echo
```

cc @jbuzzanco @rproderick

**Comment by gaand** [comment]
Please show the code that saves the user information on successful sign in

**Comment by jdaly04** [comment]
Sorry about that. Here is the Sign-In Success:
```js
const signInSuccess = (data) => {
 config.apiOrigins.host = data.user;
 console.log(data);
};
```

**Comment by gaand** [comment]
Two things. You don't seem to be using the template as intended (you've commented out the correct use of `apiOrigins`). Second, you're overwriting `host` with `user`.

**Comment by jdaly04** [comment]
When we tried to use apiOrigins it wouldn't let us use it from local host, because the header was set for a our github repo. We were getting an error in the console saying the expected header was our github repo and localhost:7165 was not allowed. 

So, to test locally, we switched config to the local host. Should we not have done that?

**Comment by RpRoderick** [comment]
localhost/:1 XMLHttpRequest cannot load https://powerful-garden-17029.herokuapp.com/sign-up. The 'Access-Control-Allow-Origin' header contains the invalid value 'The-Three-Amigos/github.io/front-end-group'. Origin 'http://localhost:7165' is therefore not allowed access.

This is the error from earlier.  So we switched to Localhost, assuming that when we deployed, the access control header would switch over to the deployed site.

**Comment by jdaly04** [comment]
We have gotten the AJAX PATCH request to work now. We reverted config.js back to its original format.
```js
'use strict';

const config = {
  apiOrigins: {
    production: 'https://powerful-garden-17029.herokuapp.com/',
  },
};

module.exports = config;
```

We also had to edit the data we were calling in our changePassword AJAX call. Our AJAX call now shows:
```js
const changePassword = (data) => {
 return $.ajax({
   url: store.host + '/change-password/' + store.user._id,
   // url: config.apiOrigins.production + 'change-password' + config.apiOrigins.production.user.id,
   method: 'PATCH',
   headers: {
     Authorization: 'Token token=' + store.user.token,
     // Authorization: 'Token token=' + config.apiOrigins.production.user.token,
   },
   data,
 });
 console.log(data);

};

```

That has fixed the issue. ADDITIONALLY, we realized we were not returning the ajax call, which you can see above in our updated AJAX call. 

cc @RpRoderick @jbuzzanco
