### ISSUE TITLE
"unable to write random state" when trying to generate secrets for back-end

### ISSUE THREAD

**Issue by akadane87** [ga-wdi-boston/group-project#200]
@gaand I believe this was the mystery error we ran into during the lab. 

stackoverflow solutions seem to be a bit above my pay grade...

http://stackoverflow.com/questions/8411625/creating-private-key-public-certificate-on-max-os-x-terminal-permission-den

...should I go for it?

**Comment by gaand** [comment]
Run `ls -l ~/.rnd`.  I believe it will show the file owned by root.  If so, you should be able run `sudo chown $(whoami) ~/.rnd` to correct that.

**Comment by akadane87** [comment]
All set! I followed the steps above and am now able to generate secrets. Thank you @gaand
