### ISSUE TITLE
missing files after pulling from development -  1:1 request

### ISSUE THREAD

**Issue by akadane87** [ga-wdi-boston/group-project#201]
I was working on "shell" branch. Checked out to "development" (which group is working on) and pulled origin development. Now my "shell" branch is missing files and I don't see it at all on github.com at all nor do I see any commit history. Please please help me reset.

**Comment by raq929** [comment]
Where are you?

**Comment by akadane87** [comment]
Tracked down missing files and added them back. Thanks @BenGitsCode
