### ISSUE TITLE
curl | create survey is 400 status

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/group-project#204]
Have been working on the route/controller/models to create a survey.
a survey requires a title, question, and answers.
here is the curl request
```
#!/bin/bash

  API="http://localhost:4741"
  URL_PATH="/surveys"

  curl "${API}${URL_PATH}" \
    --include \
    --request POST \
    --header "Content-Type: application/json" \
    --data '{
      "credentials": {
        "title": "dogs",
        "question": "what is your favorite dog?"
        "answers:" ["german shepherd"]
      }
    }'

  echo

```

Here are the routes
```
'use strict';

module.exports = require('lib/wiring/routes')

// create routes

// what to run for `GET /`
.root('root#root')

// standards RESTful routes
.resources('examples')

// users of the app have special requirements
.post('/sign-up', 'users#signup')
.post('/sign-in', 'users#signin')
.delete('/sign-out/:id', 'users#signout')
.patch('/change-password/:id', 'users#changepw')
.resources('users', { only: ['index', 'show'] })
.resources('/surveys', { only: ['index', 'show', 'post'] })
.post('/surveys', 'surveys#create')
```

Here is the controller:
```
const create = (req, res, next) => {
  let survey = Object.assign(req.body.survey, {
    title: req.body.survey.title, question: req.body.survey.question, answers: req.body.survey.answers
  });
  Survey.create(survey)
    .then(survey => res.json({ survey }))
    .catch(err => next(err));
};

module.exports = controller({
  index,
  show,
  create

});
```

models:
```
const mongoose = require('mongoose');

const surveySchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
  },
  question: {
    type: String,
    required: true,
  },
  answers: [{
    type: String,
    required: true,
  }],
}, {
  timestamps: true,
  toJSON: { virtuals: true },
});

surveySchema.virtual('length').get(function length() {
  return this.text.length;
});

const Survey = mongoose.model('Survey', surveySchema);

module.exports = Survey;

```
It is a 400 error which makes me think that it is a routes issue, but I have a surveys resource route. So We're not sure what's happening here.
Any thoughts on why create is not working?

**Comment by payne-chris-r** [comment]
What are you passing as `data`?

**Comment by jbuzzanco** [comment]
Ok. So I tried changing the curl request to
```
  API="http://localhost:4741"
  URL_PATH="/surveys"

  curl "${API}${URL_PATH}" \
    --include \
    --request POST \
    --header "Content-Type: application/json" \
    --survey '{
      "surveys": {
        "title": "dogs",
        "question": "what is your favorite dog?"
        "answers:" ["german shepherd"]
      }
    }'

  echo
```

It then says survey is unknown. We also tried to change it to surveys and it is the same error.

**Comment by jdaly04** [comment]
@jbuzzanco try changing "survey" in the curl request to "data" and "surveys" to "survey", it may work.
cc @Rproderick

**Comment by jbuzzanco** [comment]
Ok so I tried to change it back to data,
```
#!/bin/bash

  API="http://localhost:4741"
  URL_PATH="/surveys"

  curl "${API}${URL_PATH}" \
    --include \
    --request POST \
    --header "Content-Type: application/json" \
    --data '{
      "surveys": {
        "title": "dogs",
        "question": "what is your favorite dog?"
        "answers:" ["german shepherd"]
      }
    }'

  echo

```
now it is unexpected string for the error. not sure why

This is the exact error here
```
{"error":{"message":"Unexpected string","error":{"body":"{\n      \"surveys\": {\n        \"title\": \"dogs\",\n        \"question\": \"what is your favorite dog?\"\n        \"answers:\" [\"german shepherd\"]\n      }\n    }","status":400,"statusCode":400}}}~/wdi/projects/p2-frontend (master)$ 
~/wdi/projects/p2-frontend (master)$   echo


```

**Comment by BenGitsCode** [comment]
Your curl request is missing a comma.

**Comment by jdaly04** [comment]
@jbuzzanco  I think you need a comma after " "question": "what is your favorite dog?"

**Comment by jdaly04** [comment]
@jbuzzanco  I also think "surveys" needs to be singular.

**Comment by jbuzzanco** [comment]
Ok so Here is the updated curl request with a comma.
```
#!/bin/bash

  API="http://localhost:4741"
  URL_PATH="/surveys"

  curl "${API}${URL_PATH}" \
    --include \
    --request POST \
    --header "Content-Type: application/json" \
    --data '{
      "surveys": {
        "title": "dogs",
        "question": "what is your favorite dog?",
        "answers:" ["german shepherd"]
      }
    }'

  echo

```
which returns the 400 bad request error. Furthermore changing survey to surveys in data's attribute still returns the same error (400).

**Comment by jdaly04** [comment]
@ jbuzzanco did you change "surveys" to "survey" in the above curl request?

**Comment by jdaly04** [comment]
I ask because I'm confused about your sentence, " Furthermore changing survey to surveys in data's attribute still returns the same error (400).'

**Comment by jbuzzanco** [comment]
@jdaly04 yea I tried both

**Comment by jbuzzanco** [comment]
Meant to have said changing surveys to survey in data's attribute still returns a 400 error in the server. Instead of saying the opposite way survey to surveys. 🦄

**Comment by gaand** [comment]
`"answers:"` looks like a problem.

**Comment by jbuzzanco** [comment]
Ok cool. So it is now a 400 error to 500 error. I put the colon : on the outside of answers to get this. Cannot read property length of undefined
```

  #!/bin/bash

    API="http://localhost:4741"
    URL_PATH="/surveys"

    curl "${API}${URL_PATH}" \
      --include \
      --request POST \
      --header "Content-Type: application/json" \
      --data '{
        "survey": {
          "title": "dogs",
          "question": "what is your favorite dog?",
          "answers": ["german shepherd"]
        }
      }'

    echo

```
`"error":{"message":"Cannot read property 'length' of undefined","error":{}}}`

Does it have to do with this length in the schema?
```
surveySchema.virtual('length').get(function length() {
  return this.text.length;
});
```
I am not sure but it's my best guess as we were just following the examples controller

**Comment by gaand** [comment]
Yes. It's almost certainly the return line.

**Comment by payne-chris-r** [comment]
If it can't read `length` of `undefined`, what (in the code you wrote above) isn't "defined"?

**Comment by jbuzzanco** [comment]
Ok, what I just tried, which was to turn text into title, question, or answers (as title is an attribute of surveys in here the controller), all of which return a 500 error.
For instance:
```
const surveySchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
  },
  question: {
    type: String,
    required: true,
  },
  answers: [{
    type: String,
    required: true,
  }],
}, {
  timestamps: true,
  toJSON: { virtuals: true },
});

surveySchema.virtual('length').get(function length() {
  return this.title.length;
});
```
& 
` return this.question.length;`
&
` return this.answers.length;`
all return 500 error by running the curl request from above.
The error message says duplicate key, which I am not sure I am understanding
Here is the message exactly
```
{"error":{"message":"E11000 duplicate key error collection: back-end-group.surveys index: title_1 dup key: { : \"dogs\" }","error":{"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: back-end-group.surveys index: title_1 dup key: { : \"dogs\" }","op":{"updatedAt":"2016-12-20T03:14:31.692Z","createdAt":"2016-12-20T03:14:31.692Z","title":"dogs","question":"what is your favorite dog?","_id":"5858a2177ab4d0208d2537f9","answers":["german shepherd"],"__v":0}}}}~/wdi/projects/group-project/back-end-group (master)$ 
~/wdi/projects/group-project/back-end-group (master)$     echo
```

**Comment by jbuzzanco** [comment]
So yea text wouldn't be defined, but I changed it to something that is for the survey controller. Still not what were looking for 🎯  I'm gonna call it a night for now. thanks everyone for your help so far, catch up in the morning 🌅

**Comment by raq929** [comment]
Do you need the length of  the title for something in your app? If no, just remove it.

**Comment by jbuzzanco** [comment]
Ok yea it makes sense not to have length. When I try to take it out as below, the server shuts down and waits to be fixed.
```
surveySchema.virtual().get(function () {
  return this.answer;
});
```
also commenting the virtual out returns a 500 error as well. 
 I tried looking at some documentation, couldn't find anything  so far http://mongoosejs.com/docs/2.7.x/docs/virtuals.html http://mongoosejs.com/docs/guide.html

**Comment by payne-chris-r** [comment]
What does your linter say? You have a syntax error.

**Comment by jbuzzanco** [comment]
What I am looking at has no linter errors for the code I wrote in the last response.

**Comment by BenGitsCode** [comment]
Do you still have a clean linter if you quit and reopen Atom?

**Comment by jbuzzanco** [comment]
When we open and close atom it doesn't show a syntax error. I got a 200 response after taking out the virtuals. However the we're not seeing the data on the server right now on the backend when we go to localhost:4741/surveys. We got this request to work by changing the title in the curl request because it was a duplicate key error and we have a unique validator on the backend.

**Comment by BenGitsCode** [comment]
@jbuzzanco that sounds like the resolution of this particular issue, please close this and open a separate issue for anything else, if you agree.

**Comment by jbuzzanco** [comment]
Ok cool
