### ISSUE TITLE
FileBucket: Categories table may not be loading after deploying to heroku

### ISSUE THREAD

**Issue by kfili** [ga-wdi-boston/group-project#206]
When uploading a file, the user can enter a title and select a category. There is a dropdown menu for categories but currently it doesn't populate when opened. We have a table of categories in our database which is supposed to provide the categories. Not sure how to do anything to our deployed mongo database beyond following the deployment guide for heroku:
https://github.com/ga-wdi-boston/express-api-deployment-guide

**Comment by neugierige** [comment]
so...you have 2 issues?

**Comment by kfili** [comment]
Yes, the other one is now a separate issue.

**Comment by raq929** [comment]
OK. So, you need to populate your heroku database with the categories. How did you populate your local database with categories?

**Comment by kfili** [comment]
I think we have a list of categories that we entered into the table. We
probably have a csv of categories in the repo that i will look for in a bit
as i am writing this on my phone. i imagine we enter it with mongo commands
but I didn't do that part myself actually. Where are there some particular
heroku/mongo commands?

**Comment by kfili** [comment]
So, yes, I have a table of categories in data/categories.csv

Not sure how to update heroku/mlab/mongo...

**Comment by payne-chris-r** [comment]
What have you tried?

**Comment by raq929** [comment]
Again, how did you populate the table locally?

**Comment by kfili** [comment]
```
mongoimport --db=TimeCapsule-Backend --collection=categories --type=csv --headerline --file=data/categories.csv
```

**Comment by BenGitsCode** [comment]
have you tried running that in heroku?

**Comment by kfili** [comment]
I tried running heroku run mongoimport and I got ```command not found```

```
~/wdi/projects/TimeCapsule-Backend (master)$ heroku run mongoimport --db=TimeCapsule-Backend --collection=categories --type=csv --headerline --file=data/categories.csv
Running mongoimport --db=TimeCapsule-Backend --collection=categories --type=csv --headerline --file=data/categories.csv on ⬢ sheltered-taiga-22202... up, run.9899 (Free)
bash: mongoimport: command not found
```

**Comment by payne-chris-r** [comment]
Take a look at this: http://docs.mlab.com/migrating/#prefilled-commands and I'll be right over.

**Comment by payne-chris-r** [comment]
For future reference, see this: https://github.com/ga-wdi-boston/express-api-deployment-guide/issues/5

**Comment by raq929** [comment]
What's the status of this?

**Comment by kfili** [comment]
The original problem was that I could not add documents to the remote backend database. 

I accessed the mlab database via the heroku website, and then manually added documents to the collection.

This was done via heroku.com -> click on the 'personal app' your trying to work on -> click on 'mlab mongoDB' in add-ons, this opens the mlab site -> now in mlab, click on the collection you want -> 'add document'.
