### ISSUE TITLE
Connecting a User to another User's site

### ISSUE THREAD

**Issue by Sphilippe7** [ga-wdi-boston/group-project#207]
"Content Management System

Build an app to build a website! Your app must allow non-technical users to write blog posts and pages for the site. When a visitor visits your site, they should see content. When a user logs in, they should see a dashboard that lets them create and edit new posts or pages."

So above I copy and pasted the prompt for our group project. We have all the functions working and our website is up and running! The problem is we are looking for a way to connect users. As it stands right now, when a user signs in, they are brought to their dashboard and are able to do thing everything specified in the requirements above. We are coming into a road block when trying to give users the access to seeing other user's sites. One method we tried implementing is writing a really long ```if``` statement to distinguish the user's dash board to how it looks for the public access but that did not work. Should we still be thinking of this as a single page application or more?

**Comment by payne-chris-r** [comment]
See #195 and let me know if you still have questions!

**Comment by akradin** [comment]
Hey so we are currently working on this and tackling it from the backend but we are hitting a road block. We have attempted to add an `if` statement into our index methods that checks for `currentUser`.
What we have so far is:
```js
const indexUsersPages = (req, res, next) => {
 let search = {};
 if (!req.currentUser._id) {
   //  search = {_owner: req.currentUser._id}
 } else {
   search = {_owner: req.currentUser._id};
 }

 console.log('search ', search);
 Page.find(search)
   .then((pages) => {
     if (!pages) {
       console.log('are we getting here?');
       return next();
     } else {
       console.log('pages ', pages);
       return pages;
     }
   })
   .then(pages => pages ? res.json({ pages }) : next())
   .catch(err => next(err));
};
```

That is what we have so far but we aren't sure how to proceed. We have toyed with the idea of eliminating current user all together but then this would prevent a dashboard from being possible. 
We are in the Tremont conference room if anyone would like to come take a look

**Comment by raq929** [comment]
So, what is the problem you're having right now. Is there an error?

**Comment by neugierige** [comment]
your code seems to check if there IS a current user at all. but I think what you are really going after is whether the current user the owner of certain content. is that right??

**Comment by akradin** [comment]
After talking with Rachel we are going to re-configure our routes to differentiate between `currentUser` and not `currentUser`. We will keep this issue open until we have a solution.

**Comment by gaand** [comment]
Is there a reason why you've named the `index` action `indexUsersPages`?

**Comment by kmg1434** [comment]
@gaand 
We have an ```index``` action that returns **all** users pages, although we never use it.

The ```indexUsersPages``` returns only **one** specific users pages, rather than everyones.

**Comment by gaand** [comment]
I think that's one action that changes it's behavior based on a query parameter.  I could be wrong.

**Comment by neugierige** [comment]
@kmg1434 recall that in previous talks and projects, we purposefully wrote code to make it so that `index` did not require authentication. I think the reverse is also achievable in the same method.

**Comment by akradin** [comment]
Here is what we have come up with. 

```js
const indexUserBp = (req, res, next) => {
  let search = { _owner: req.currentUser._id };
  console.log('search ', search);
  Blogpost.find(search)
    .then((blogposts) => {
      if (!blogposts) {
        console.log('are we getting here?');
        return next();
      } else {
        console.log('blog posts ', blogposts);
        return blogposts;
      }
    })
    .then(blogposts => blogposts ? res.json({ blogposts }) : next())
    .catch(err => next(err));
};
const indexOthersPosts = (req, res, next) => {
  let search = { _owner: req.params.other_user_id };
  console.log('search ', req.params.other_user_id);
  Blogpost.find(search)
    .then((blogposts) => {
      if (!blogposts) {
        console.log('are we getting here?');
        return next();
      } else {
        console.log('blogposts ', blogposts);
        return blogposts;
      }
    })
    .then(blogposts => blogposts ? res.json({ blogposts }) : next())
    .catch(err => next(err));
};
```

We have these two index methods which are used for showing `currentUser`'s blog posts and for the showing the blog posts of other users. We then have the following `module.exports` which allows for the second function to run without being logged in. Feel free to disregard the functions that are being exported that are not relevant to this issue.

```js
module.exports = controller({
  create,
  index,
  indexUserBp,
  indexOthersPosts,
  show,
  update,
  destroy,
}, { before: [
  { method: authenticate, except: ['index', 'show', 'indexOthersPosts'] },
], });
```

We then have updated routes to reflect these different methods. They are as shown below. We have currently tested these with the blogposts and the pages via `curl` requests. 

```js
.get('/pages/me/:user_id', 'pages#indexUsersPages')
.get('/pages/:other_user_id', 'pages#indexOthersPages')
```

**Comment by akradin** [comment]
Leaving open as we test on the front end

**Comment by neugierige** [comment]
The fact that those 2 functions only have a single differentiating line tells me that they do not need to be 2 separate functions. I think you can have a single generic "indexBp" function, whose argument in-take determines what posts to show.

But get that to work first.

**Comment by raq929** [comment]
What's your status on this?

**Comment by Sphilippe7** [comment]
sorry @raq929 we moved on. We made a single function as @neugierige mentioned above. I'll close this issue now.
