### ISSUE TITLE
Login issue with mLab

### ISSUE THREAD

**Issue by treep78** [ga-wdi-boston/group-project#209]
Signing up works on my mlab deployment, however when a user attempt to log in they get an error message. In the instances of login I've been seeing online that had this issue, their crypto function appears to work very differently than the one in the template.

```
HTTP/1.1 500 Internal Server Error
Server: Cowboy
Connection: keep-alive
X-Powered-By: Express
Access-Control-Allow-Origin: http://localhost:7165
Vary: Origin
Content-Type: application/json; charset=utf-8
Content-Length: 50
Etag: W/"32-f0PDWtN4RNCHOcPLVIwtbw"
Date: Tue, 20 Dec 2016 13:58:20 GMT
Via: 1.1 vegur

{"error":{"message":"Must give cipher-type, key"}}~/wdi/projects/project3/e-com-back-end (backend)$ 
```

**Comment by BenGitsCode** [comment]
Can I see the relevant code? It looks like you're not matching the params it wants.

**Comment by raq929** [comment]
If you're creating users without using the model in the template, that's an unsupported use case. 
We've given you the tools to create users through the template, and that's what we're able to help with. Why do you think it's necessary to create users through mlab?

**Comment by treep78** [comment]
I'm not sure what you mean by that. The code I'm using for login is from the express template and works perfectly on the local deployment.

**Comment by treep78** [comment]
All database calls go through mlab.

**Comment by treep78** [comment]
Sign up:
```
API="https://gentle-hamlet-35507.herokuapp.com"
URL_PATH="/sign-up"
EMAIL="jain@said.com"
PASSWORD="jane"

curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{
    "credentials": {
      "email": "'"${EMAIL}"'",
      "password": "'"${PASSWORD}"'",
      "password_confirmation": "'"${PASSWORD}"'"
    }
  }'
```
sign-in
```
API="https://gentle-hamlet-35507.herokuapp.com"
URL_PATH="/sign-in"
EMAIL="jain@said.com"
PASSWORD="jane"

curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{
    "credentials": {
      "email": "'"${EMAIL}"'",
      "password": "'"${PASSWORD}"'"
    }
  }'
```

**Comment by raq929** [comment]
Database calls go through your node server. Data gets stored using mlab.
It looks like you haven't set a secret key for your app. What do you get when you run `heroku config`? (Don't post secret keys here.)

**Comment by treep78** [comment]
I get my MONGODB_URI and PROD_MONGODB. The only info I can find for setting secret keys is for rails.

**Comment by raq929** [comment]
Looks like you missed a step in the deployment guide. Steps for setting the secret key are in here: https://github.com/ga-wdi-boston/express-api-deployment-guide

**Comment by treep78** [comment]
somewhat embarrassingly I hadn't been able to find that link. I think I had been searching heroku deployment guides in the wdi account rather than express

**Comment by treep78** [comment]
SOLUTION: I had not added a SECRET_KEY to my heroku. If you are having this issue follow the steps in: https://github.com/ga-wdi-boston/express-api-deployment-guide

Thanks Rachel!
