### ISSUE TITLE
On create survey, error status 500

### ISSUE THREAD

**Issue by RpRoderick** [ga-wdi-boston/group-project#210]
message: cannot convert undefined or null to object error:{}}}

I get this on create survey form submit.  I believe that it is related to my schema.  But, not sure where to go from here.  Schema:

```js
const mongoose = require('mongoose');

const surveySchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
  },
  question: {
    type: String,
    required: true,
  },
  answers: [{
    type: String,
    required: true,
  }],
  _owner: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
}, {
  timestamps: true,
});
```

**Comment by raq929** [comment]
It sounds more like you're not sending data to the API. Does a curl request work? Because if curl works, then nothing's wrong with your schema.

**Comment by raq929** [comment]
Please put three backtics around your code. '```js' for JavaScript

**Comment by RpRoderick** [comment]
Yes, the curl request worked earlier.  We successfully created a few surveys.  Trying to tie into the front end through the form.  
And ok on the ```

**Comment by RpRoderick** [comment]
Just for fun, I ran a curl request again.  I get the same error: cannot convert undefined or null to object.  So....we must have done something.  I'll continue to work on it and try and figure out what we changed.

**Comment by RpRoderick** [comment]
Ok, well, we had an s on the end of surveys that was screwing things up.  Now, curl requests go through again and create a survey just fine.  The front end errors out though.  500 internal error, message: cannot read property "title" of undefined error:{}}}.  So, similar error in that it is getting to the ajax but not liking this: (req.body.survey.title - I think)

```const create = (req, res, next) => {
  let survey = Object.assign(req.body.survey, {
   title: req.body.survey.title, question: req.body.survey.question, answers: req.body.survey.answers,
   _owner: req.currentUser._id
  });
console.log(survey);
  Survey.create(survey)
    .then(survey => res.json({ survey }))
    .catch(err => next(err));
}; ```

**Comment by payne-chris-r** [comment]
What is the difference between the object your client is sending and curl? If you figure that out, you should be good to go. My guess is you're not sending `title` from the front end? Can you post your `curl` request that IS working?

**Comment by RpRoderick** [comment]
sure.  This is the one that works.  We are using getFormFields to send the request from the front end.  It looks like the .catch on the backend is getting triggered.  I will compare the two and see if I can find a difference.  Maybe I need a separate form field for title and question?

```  API="http://localhost:4741"
    URL_PATH="/surveys"
    TOKEN="iamfURewNWOKXzHmJIvj6PqbmB28W1IZDAXz3K3BFFA=--gMCxi/7LWkf/DJNTFeT3j0tU3Rzp5EL0zjX9ujB6sdM="

    curl "${API}${URL_PATH}" \
      --include \
      --request POST \
      --header "Content-Type: application/json" \
      --header "Authorization: Token token=${TOKEN}" \
      --data '{
        "survey": {
          "title": "dogs9 rottie",
          "question": "what is your favorite dog?",
          "answers": ["rottweiler"]
        }
      }'```

**Comment by payne-chris-r** [comment]
Can you paste the html for the form?

**Comment by payne-chris-r** [comment]
```Maybe I need a separate form field for title and question?```
^ You absolutely do

**Comment by RpRoderick** [comment]
```<form id="questionAppend">
              <fieldset>
                <legend>Enter Question HERE</legend>
                <input type="text" name="survey[title]" placeholder="Title">
                <input type="text" name="survey[question]" placeholder="Question">
                <input type="submit" name="submit" value="Append Question!">
              </fieldset>
            </form>```

**Comment by RpRoderick** [comment]
for simplicity we were starting with 'each survey has one question' and we were going to move up to multiple questions once we got that down.

**Comment by RpRoderick** [comment]
```"surveys": [
{
"_id": "58594aca232d1b25547c093f",
"updatedAt": "2016-12-20T15:14:18.805Z",
"createdAt": "2016-12-20T15:14:18.805Z",
"title": "dogs 2",
"question": "what is your favorite dog?",
"__v": 0,
"answers": [
"german shepherd"
]
},
{
"_id": "58594bffefaec828bac9b0d2",
"updatedAt": "2016-12-20T15:19:27.398Z",
"createdAt": "2016-12-20T15:19:27.398Z",
"title": "dogs 5",
"question": "what is your favorite dog?",
"__v": 0,
"answers": [
"german shepherd"
]```

**Comment by RpRoderick** [comment]
A few examples of ones we've created.  Simple enough.  Each survey has a title and a question.  Will have a separate form for answers.

**Comment by payne-chris-r** [comment]
```js
const createSurvey = ...
  console.log('data is ', data);
  $.ajax...
```
What does that `data` object look like? Does it match your `curl` request? I don't think you have an `answers` in your `ajax` call...

**Comment by RpRoderick** [comment]
So.....Joel logged in on the front end site and created a survey with no problem!  I don't know why his worked just fine.  Our files are all up to date.  I'm going to pull the backend master again just to make sure but we've been going along step for step.  ARGH!  It's good that it works.  I just don't know why.  I haven't restarted my server in awhile....but his creates a survey without a problem.  I will keep this issue open for a few and see if I can get mine to create.

**Comment by BenGitsCode** [comment]
Could it be a caching issue? Hard refresh all of your browsers.

**Comment by RpRoderick** [comment]
maybe.  Joel pushed to github and then I pulled down from github (again, 99% sure I had the exact same files, but just to be sure..) and then reset my servers and it works fine for me too.  I don't know!  But surveys get created just as we intended.  Julia can also create.  I guess I'll close the issue?
