### ISSUE TITLE
Showing and Hiding Pages

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/group-project#212]
We are currently trying to show a users posts and pages. In the spirit of having it look like a real website, when you click on a user, you should see all of their pages which we have. We are struggling to effectively show the content within the page after clicking on the specific page title. Here is the function we have, we are fairly certain it is a `this` issue but we can't figure it out.
```js
const onPageClick = function () {
  let id = $(this).data('id');
  $('.content-' + id).html(this.page.content);
};
```

We get a type error of content undefined when we do this. This is the handlebars template we are referencing that is populated into an empty div with the class of `user-pages`.

```html
{{#each pages as |page|}}

  <!-- Show Pages -->
  <div class="row row-centered">
    <div class="col-xs-4 col-centered box">
      <button type="button" data-id="{{page._id}}"class="btn btn-success show-page-button btn-group btn-group-justified">{{page.title}}</button>
    </div>
    <div class="col-xs-4 col-centered box">
      <div class="content-{{page._id}} content">content: {{page.content}}</div>
    </div>
  </div>

{{/each}}
```

and then our click handler:
```js
  $('.user-pages').on('click', '.show-page-button', onPageClick);
```

**Comment by akradin** [comment]
We also tried making the `onPageClick` function do this:

```js
const onPageClick = function () {
  let id = $(this).data('id');
  $('.content-' + id).removeClass('hidden');
};
```

and added the class `hidden` to where the content this.
This function works, but we don't know how to re-add the `hidden` class when we look at a different page

**Comment by gaand** [comment]
I think you want to investigate `event.target`.  The first step is to add `event` as the formal parameter to your click handler.

**Comment by akradin** [comment]
We added `event.target` and added `event` as the parameter and it is still not working. Here is what we came up with 
```js
const onPageClick = function (event) {
  event.preventDefault();
  let id = $(event.target).data('id');
  console.log('id is ', id);
  let data = api.showPage(id);

  // let content = data.page.content;
  console.log('page data is ', data);

  // $('.content-' + id).removeClass('hidden');
  // $('.content-' + id).html(this.page.content);
  $('.show-page-content').html(data.readyState.responseJSON.page.content);
};
```

`data` ends up being this really long object that we cannot seem to access anything inside of which is where  `data.readyState.responseJSON.page.content` comes from, but this returns undefined

**Comment by akradin** [comment]
We got it!!!!!!!!!  🖖

```js
const onPageClick = function (event) {
  event.preventDefault();
  let id = $(event.target).data('id');
  console.log('id is ', id);
  api.showPage(id)
    .then((data) => {
      console.log('data is ', data);
      $('.show-page-content').html(data.page.content);
    })
    .catch(ui.failure);
};
```

**Comment by akradin** [comment]
Just for a bit of clairification, a users page buttons show up in a handlebars template and that `show-page-content` div is just in the regular `index.html` file. Not sure if it makes any difference but that is how we set it up.
