### ISSUE TITLE
Update Not Working

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/group-project#213]
So we have run across an issue that we don't believe was there when we were first setting up CRUD functionality. When we try to edit a page, the ajax call runs twice. So, the edit functionality works, but if a user was using the application with console open, it would throw an error.
Here is the code for the edit post function
```js
const onEditPage = function (event) {
  debugger;
  event.preventDefault();
  let id = $(event.target).data('id');
  let data = getFormFields(this);
  api.editPage(id, data)
  .then((data) => {
    ui.editPageSuccess(data);
    return api.indexMyPages();
  })
  .then(ui.indexMyPagesSuccess)
  .catch(ui.failure);
};
```

Here are the click handlers
```js
  $('.show-pages').on('click', '.edit-page-button', showUpdate);
  $('.show-pages').on('submit', '.edit-page-form', onEditPage);
```

The reason why they are formatted as such is because these are in a handlebars template. So when we do the first of those two functions, it triggers a modal that has the update form. Then, we update the form within the modal, hit submit and run into the error.

We have isolated the issue to being the fact that the form is within a modal but we are unsure of how to solve it.

We have tried doing this incase it had something to do with handlebars but it didn't resolve the problem.
```js
  $( '.edit-page-form').on('submit', onEditPage);
```

At this point we are just doing minor bug fixes so we would like to get this feature up and running if it has an easy solution

**Comment by raq929** [comment]
Cool. Can I see 
1. the html for the modal and `.show-pages`
1. the handlebars template in question
1. showUpdate

**Comment by akradin** [comment]
Yeah!
The HTML is as follows, basically just go to the bottom to see the modal:
```html
{{#each pages as |page|}}

  <!-- Show Pages -->
  <div class="row row-centered">
    <div class="col-centered box">
      <div class="content-{{page.id}} content page-name">title: {{page.title}} </div>
    </div>
    <div class="col-centered box">
      <div class="content-{{page.id}} content page-due">body: {{page.content}}</div>
    </div>
    <div class="col-xs-4 col-centered box complete-page">
      <button type="button" class="delete-page-button btn btn-danger" data-id="{{page._id}}">Delete</button>
    </div>
    <div class="col-xs-4 col-centered box complete-page">
      <button type="button" class="edit-page-button btn btn-success" data-id="{{page._id}}">Edit</button>
    </div>
  </div>

  <!-- Edit Page Modal -->
  <div class="modal fade page-edit-{{page._id}} edit-page-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="editPageModalLabel">Edit Page</h4>
        </div>
        <div class="modal-body">
          <form class="edit-page-form" data-id="{{page._id}}">
            <div class="form-group">
              <label>Edit Page Title</label>
              <input type="text" maxlength="25" class="form-control" name="page[title]" value="{{page.title}}">
            </div>
            <div class="form-group">
              <label>Edit Page Content</label>
              <textarea rows="4" cols="30" class="form-control" name="page[content]">{{page.content}}</textarea>
            </div>
            <button type="submit" class="btn btn-primary" id="edit-page-submit">Submit</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          </form>
        </div>
      </div>
    </div>
  </div>

{{/each}}
```

and the showUpdate is this
```js
const showUpdate = (e) => {
  let className = '.page-edit-' + $(e.target).data('id');
  $(className).modal('show');
};
```

**Comment by raq929** [comment]
Hmmm... nothing is popping out at me. Do you hit that debugger statement twice? If so, you're probably setting your click handler twice somehow.

**Comment by raq929** [comment]
If the debugger isn't happening twice: 
You said that you think it's because of the modal? What happens if you remove the modal but keep the form? (Probably some ugliness html-wise, but I'm talking functionality).

**Comment by akradin** [comment]
Yeah, it works fine if we take out the modal, just like you said, very ugly

**Comment by raq929** [comment]
Are the two ajax calls identical? (Check the network tab)

**Comment by raq929** [comment]
Your modal has the class `edit-page-form`, so it also has the click handler set on it. Try removing that class from the modal, or use an ID for your button instead of a class.

**Comment by akradin** [comment]
So for now we just have a hidden form that we show when we click the update button to replace the modal and we will explore fixing the modal a bit later. We ran across another issue, don't know if I should open up a new issue but validation isn't working on update.

So for example our `title` and `body` are required in our schema but if we update  a blogpost or page with no content in either of these, the backend accepts this. 
 _Validation does work on create_ which is strange
I did some research and it looks like validation is usually defined in the Schema

**Comment by raq929** [comment]
Did removing `edit-page-form` on the modal fix the double patch issue? 
And yes, please open an issue about validation. :)
Please post your schema and the update function.

**Comment by akradin** [comment]
We are trying the `edit-page-form` right now and opening up another issue.

**Comment by akradin** [comment]
Okay, so this fixes the problem. For some reason we need to do the hacky 
`$('.modal-backdrop').remove();`to hide the modal accordingly, but. it works.
 ¯\_(ツ)_/¯
