### ISSUE TITLE
Update Validation Not Working

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/group-project#214]
Validation isn't working on update.

So for example our title and body are required in our schema but if we update a blogpost or page with no content in either of these, the backend accepts this.
Validation does work on create which is strange
I did some research and it looks like validation is usually defined in the Schema so if our schema requires `title` and `body` shouldnt they be required when updating as well as creating?

**Comment by payne-chris-r** [comment]
have you tried it with curl?

**Comment by payne-chris-r** [comment]
I know I sound like a broken record, but your front end may be sending them (even if they're blank). I would've thought `title:""` would prevent something from updating, but I would just be mindful about what is actually getting sent. curl it. Log `data` before it leaves your front end. Stuff like that. Check your db. Confirm that it is in fact not saving anything for title.

**Comment by akradin** [comment]
Yeah, we checked our back end when we were trying and we were getting `200 OK`. Also, just because, I just double checked with empty strings in the curl request for create, I had content in it and it worked. I updated it without content and everything is fine.

I did a search for that specific blog post and it does in fact have no content in the title or the body.

Sure enough, when I make a blogpost with empty strings, it returns an internal sever error.

**Comment by raq929** [comment]
Please post your schema and update function.

**Comment by akradin** [comment]
Schema:
```js
const blogpostSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
  },
  content: {
    type: String,
    required: true,
  },
  _owner: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
}, {
  timestamps: true,
});
```

Update function
```js
const update = (req, res, next) => {
  // console.log(req.body);
  let search = { _id: req.params.id, _owner: req.currentUser._id };
  Page.findOne(search)
    .then(page => {
      if (!page) {
        return next();
      }

      // console.log(req.body.page);

      delete req.body._owner;  // disallow owner reassignment.
      Page.update(req.body.page);
      return page.update(req.body.page)
        .then(() => res.sendStatus(200));
    })
    .catch(err => next(err));
};
```


These are pretty much the same for pages and posts. I did a bit more research since I have expounded a bit on my mongoose vocab. Some people use regex validators, do you think that is a good direction to head in?

**Comment by gaand** [comment]
Did you intend to do this?

```js
      Page.update(req.body.page);
```
