### ISSUE TITLE
files not loading on deployment | gh-pages

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/group-project#218]
Upon the deployment of our web app, the styling is gone. The styling is there on localhost. There are two 404 errors for files not found in the console, both `vendor.js` and `application.js`. We tried to `git add` these files only to find out they do not exist. We followed  [gh-pages deployment guide](https://github.com/ga-wdi-boston/gh-pages-deployment-guide); not sure why they are gone, but apparently it is vital to the deployment of the application on gh-pages. 

This is the exact error in the console for both files:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
```
 Any suggestions on what we should do?

**Comment by gaand** [comment]
Are you using the latest version of `browser-template`?

If so, you should be able to run `grunt deploy` from the master branch.

**Comment by jbuzzanco** [comment]
I believe so, as that command ran successfully. Now I notice upon opening the front-end deployed site it says that the https request is unsuccessful. Not really sure why as the server is running on the backend.
This is the exact error

```
vendor.js:9646 Mixed Content: The page at 'https://the-three-amigos.github.io/front-end-group/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:4741/sign-up'. This request has been blocked; the content must be served over HTTPS.

```

**Comment by gaand** [comment]
From the browser-template README.md

> Developers should set config.apiOrigins.production (and config.apiOrigins.development if it differs from the default). With apiOrigins set, developers may rely on config.apiOrigin as the base for API URLs.

So, set `config.apiOrigins.production` to your deployed api, and use `config.apiOrigin` as the base url in your ajax requests.

**Comment by jbuzzanco** [comment]
Ok great. That is one part that as a group, we we're confused how to set earlier.
I tried to set the config file to this to include development and production, separating with a comma,  which may not be right.
```
'use strict';

const config = {
  apiOrigins: {
    development: 'http://localhost:4741',
    production: 'https://powerful-garden-17029.herokuapp.com/'
  },
};

module.exports = config;

```
I am now getting a 404 not found error upon sign-up within localhost. I tried setting the url base to `config.apiOrigin`.
Here is sign-up for reference.
```
const config = require('../config.js');



const signUp = (data) => {
  return $.ajax({
    url: config.apiOrigins + '/sign-up',
    // url: config.apiOrigins.production + 'sign-up',
    method: 'POST',
    data,
  });
};
```
The client and back-end were both served locally as I tested this.

**Comment by gaand** [comment]
```diff
   return $.ajax({
-    url: config.apiOrigins + '/sign-up',
+    url: config.apiOrigin + '/sign-up',
    // url: config.apiOrigins.production + 'sign-up',
```

You seem to have an extra `s`.

**Comment by jbuzzanco** [comment]
That was it! It is working locally at least. It is working locally now, but is not working for production. Production has the same error before that it cannot load the back-end deployed site upon sign-up. 
The error is:

```
XMLHttpRequest cannot load https://powerful-garden-17029.herokuapp.com/sign-up. The 'Access-Control-Allow-Origin' header contains the invalid value 'The-Three-Amigos/github.io/front-end-group'. Origin 'https://the-three-amigos.github.io' is therefore not allowed access.
```
In order to test this, I merged the working changes onto my master and ran `grunt deploy`.  Locally is working fine on my master now. I did not `git push origin master`. I am not sure why it cannot load the deployed back-end as of now.

**Comment by gaand** [comment]
The error message is telling you.

> The 'Access-Control-Allow-Origin' header contains the invalid value 'The-Three-Amigos/github.io/front-end-group'.

That says that  'The-Three-Amigos/github.io/front-end-group' is not a valid value for the header.

> Origin 'https://the-three-amigos.github.io' is therefore not allowed access.

That says that the actual origin isn't allowed.

I suggest you check your heroku config for the API.

**Comment by jbuzzanco** [comment]
Ok. I also tried getting rid of the preceding slash in the api calls, as I noticed it showed two slashes `//` in the failed sign-up request. That doesn't work as locally it is not showing anything in the console. 
It seems that the heroku config is pointing to that client for the api though. Because when I type `heroku config` it displays the origin: `The-Three-Amigos/github.io/front-end-group` as the `CLIENT_ORIGIN`. From what I understand, I think that is the correct client origin, but perhaps not since it is not a valid header value.

**Comment by gaand** [comment]
The error message says it's not valid, so that couldn't be the correct value.  Please have a look in the README.md at what it says about `CLIENT_ORIGIN`

**Comment by jbuzzanco** [comment]
Ok. I didn't see anything that explicitly said `CLIENT_ORIGIN` in the [browser template](https://github.com/ga-wdi-boston/browser-template), however it says to set production and development, which I did, and is working for development, just not production. Then it says to set `config.apiOrigin` as the base for the URL which also has been implemented.
From the browser template README
> Developers should set config.apiOrigins.production (and config.apiOrigins.development if it differs from the default). With apiOrigins set, developers may rely on config.apiOrigin as the base for API URLs.

This leads me to believe it may be something wrong with how I set development and production in the config file. When I try to set them separately though, it gives an error in the linter. I do not really know if they are set wrong, as this currently gives no linter error in the config file:
```
'use strict';

const config = {
  apiOrigins: {
    development: 'http://localhost:4741',
    production: 'https://powerful-garden-17029.herokuapp.com/'
  },
};

module.exports = config;

```

**Comment by gaand** [comment]
Did you mean "use `config.apiOrigin`" when you said "set `config.apiOrigin`"?

The config you pasted above looks fine.

`CLIENT_ORIGIN` is about your API, not your client, so you're looking in the wrong template.  Look at the end of [this section](https://github.com/ga-wdi-boston/express-api-template#installation).

**Comment by jbuzzanco** [comment]
Thanks for the reply.

Yes, "use" would have been a better description than "set" in my response above.

So I tried to reset the `CLIENT_ORIGIN` to `https://the-three-amigos.github.io/front-end-group/` 
It is another 404 not found error. Furthermore, this time it says in the error for sign-in, the header value is not equal to supplied origin. 
The exact error in this case
```
the-three-amigos.github.io/:1 XMLHttpRequest cannot load https://powerful-garden-17029.herokuapp.com//sign-in. The 'Access-Control-Allow-Origin' header has a value 'https://the-three-amigos.github.io/front-end-group' that is not equal to the supplied origin. Origin 'https://the-three-amigos.github.io' is therefore not allowed access.
```

As it is a 404 not found error for finding the heroku api, I noticed it has two slashes in the request, for instance there are two slashes `//` before the sign-in request: `https://powerful-garden-17029.herokuapp.com//sign-in`. So I tried to change the `CLIENT_ORIGIN` without the slash at the end of the url. 
Also tried to change the production url (within the client) to not have slash at the end.
The same error happens in both cases (the error written above), so removing that extra slash doesn't seem to be  fixing it.

I'm not sure why the header value is not equal to the supplied origin.

**Comment by gaand** [comment]
The extra slash is an artifact of your config settings that I didn't notice.  My apologies, your pasted config can be corrected as follows to eliminate the extraneous `/` in the request:

```diff
 'use strict';

 const config = {
   apiOrigins: {
     development: 'http://localhost:4741',
-    production: 'https://powerful-garden-17029.herokuapp.com/'
+    production: 'https://powerful-garden-17029.herokuapp.com'
   },
 };

module.exports = config;
```

This aligns the `production` entry with the `development` entry.  It's also not the problem.

Your `CLIENT_ORIGIN` still isn't set correctly.  This is the example from the link I pasted above:

```sh
heroku config:set CLIENT_ORIGIN=https://<github-username>.github.io
```

So, using your github pages setup:

```sh
heroku config:set CLIENT_ORIGIN=https://the-three-amigos.github.io
```

An origin header does not contain a path.

**Comment by jbuzzanco** [comment]
That is okay about the extraneous `/` within the config settings. I have it using the proper production url now.

It is now working for production to sign-in, as well as other requests that were working locally. Thank you. I changed the heroku config `CLIENT_ORIGIN` with

 ```
heroku config:set CLIENT_ORIGIN=https://the-three-amigos.github.io
```

I remember looking at the example many times for how to set the `CLIENT_ORIGIN` thinking that it was set correctly. The phrase you said in class before -- "pattern recognition is a skill" -- has been since fixing this, playing over and over in my head.
