### ISSUE TITLE
Cannot reproduce Stripe credit card error in project resubmission

### ISSUE THREAD

**Issue by joaufi** [ga-wdi-boston/group-project#220]
We are unable to reproduce the following error:
```Stripe declines an invalid card (500 error), but it still takes users to the past orders page as if the order had been successful.```

We have tried putting in all sorts of different cards and we don’t get a `500` error, we get back `402` if the card is not correct.

And the promise chain does not continue when we get back a 402 error. So far the only time the past orders loads is if the card charge was successful.

This error was outlined in the email. Could we meet with one of you to get the error to happen?

**Comment by raq929** [comment]
What I did to get this error was login, add a thing to my cart, enter the valid 4242 credit card, remove the last 2, and hit checkout. 
The server sends a 500 error, but the app takes me to the past orders page.

**Comment by raq929** [comment]
If that doesn't work for you, let's sit down and see if we can recreate it.

**Comment by joaufi** [comment]
I was able to reproduce the error. Currently working on a fix. I am going to close this as reproducing the error was what was at issue. Thanks!
