### ISSUE TITLE
Stripe Verification Code

### ISSUE THREAD

**Issue by rickdean** [ga-wdi-boston/group-project#222]
One of the errors we were asked to correct had to do with a Stripe verification code.  Our app utilizes a Stripe provided checkout module.  Depending on whether or not the user has submitted prior payments (and is registered) Stripe will offer the verification option.  Directly below that verification method it states that the user can enter their card info manually (which is the preferred option for the test).  The test card is '4242424242424242' with any exp date and any CRV.  

Is this still considered an issue as it is a Stripe feature?

Thank you!

**Comment by raq929** [comment]
Ah, OK. Yes, that sounds fine. I probably missed the manual input message because I had developer tools open and didn't scroll down.

**Comment by rickdean** [comment]
Thank you Rachel.  At the moment I will leave as is and consider it closed.  Thank you!
