### ISSUE TITLE
Modal Prevents Scroll on Close

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/group-project#223]
Hello! I posted this issue in forum but here it is so you can see some of the code I am working with. We have made some significant front end progress for our app but we are experiencing a major issue. A users Pages and Posts are generated on login using a separate handlebars template for each. There is a modal in each template that is triggered when you want to update the post or page because this is the ideal UX solution, we feel. However, when you submit an edit, the modal backdrop stays, i.e. the whole page has a gray hue and is unclickable and unscrollable. This is partially solved when using `$('.modal-backdrop').remove();`. When I say partially I mean the gray hue goes away and buttons can be clicked, but the page remains unscrollable. Here is the Handlebars template for blogposts.
```html
{{#each blogposts as |blogpost|}}

<div class="show-posts-wrapper">
  <div>
    <div>
      <div class="content blogpost-title">
        <p>{{blogpost.title}}</p>
       </div>
      <div class="content blogpost-content">
        <p>{{blogpost.content}}</p>
      </div>
    </div>
  </div>
    <div>
      <button type="button" class="edit-post-button" data-id="{{blogpost._id}}">Edit</button>
    </div>
    <div>
      <button type="button" class="delete-post-button" data-id="{{blogpost._id}}">Delete</button>
    </div>
  </div>

  <!--Edit blogpost Modal-->
   <div class="modal fade blog-edit-{{blogpost._id}} edit-post-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
     <div class="modal-dialog" role="document">
       <div class="modal-content">
         <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
           <h4 class="modal-title" id="editPageModalLabel">Edit Page</h4>
         </div>
         <div class="modal-body">
           <form class="blog-edit" data-id="{{blogpost._id}}">
             <div class="form-group">
               <label>Edit Page Title</label>
               <input type="text" maxlength="25" class="form-control" name="blogpost[title]" value="{{blogpost.title}}">
             </div>
             <div class="form-group">
               <label>Edit Page Content</label>
               <textarea rows="4" cols="30" class="form-control" name="blogpost[content]">{{blogpost.content}}</textarea>
             </div>
             <button type="submit" class="btn btn-primary" id="edit-post-submit">Submit</button>
             <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
           </form>
           <div class="post-failure"></div>
         </div>
       </div>
     </div>
   </div>
{{/each}}
```

So I thought it might be a problem with the `{{/each}}` being after the modal but the issue occurs when you place it before the modal, which in retrospect, makes sense. Here is the code for what happens when you click the edit button on the page:
```js
const showUpdate = (e) => {
  let className = '.blog-edit-' + $(e.target).data('id');
  $(className).modal('show');
};
```

That triggers the modal, then when you submit the update
```const onEditPost = function (event) {
  event.preventDefault();
  let id = $(event.target).data('id');
  let data = getFormFields(this);
  if(!data.blogpost.title || !data.blogpost.content) {
    $('.post-failure').html('Enter title and content please!');
    return;
  }
  api.editPost(id, data)
  .then(() => {
    ui.editPostSuccess();
    return api.indexMyPosts();
  })
  .then(ui.indexMyPostsSuccess)
  .catch(ui.failure);
};
```

Here are those `ui` functions just because
```js
const editPostSuccess = (data) => {
  $('.modal-backdrop').remove();
};

const indexMyPostsSuccess = (data) => {
  $('.show-all-my-posts').html(showMyPosts(data));
};
```

We are aware removing the modal will resolve the problem, but it is an interesting bug.

**Comment by gaand** [comment]
I don't know if this is part of or related to the issue, but if you use `id="a non-unique value"` (e.g. `id="editPageModalLabel"`) in an each as you have, your rendered html is invalid.

**Comment by akradin** [comment]
Oh, makes sense. I went ahead and removed all `id`s from the handlebars template , but the issue persists.

**Comment by payne-chris-r** [comment]
There's likely bootstrappy stuff going on. You should go through your click handlers with a fine-toothed comb and try to figure out when they're firing and when the modal is opening and closing. My guess is it's visually disappearing, but bootstrap still thinks it's open.

**Comment by akradin** [comment]
I went through everything associated with this modal and can't seem to find anything. I also explored several different ways to use the `.hide()` and `.modal('hide')` methods but I can't seem to figure out what is going on. I figured it was an issue with Bootstrap and Handlebars so instead of having a success function that hides `.edit-post-modal` or  `.edit-page-modal` I changed the promise chain to look like this:
```js
const onEditPost = function (event) {
  event.preventDefault();
  let id = $(event.target).data('id');
  let data = getFormFields(this);
  let edit = '.blog-edit-' + id;
  console.log(edit);
  if(!data.blogpost.title || !data.blogpost.content) {
    $('.post-failure').html('Enter title and content please!');
    return;
  }
  api.editPost(id, data)
  .then(() => {
    ui.editPostSuccess();
    return api.indexMyPosts();
  })
  .then($(edit).modal('hide'))
  .then(ui.indexMyPostsSuccess)
  .catch(ui.failure);
};
```

In conjunction with a `$('.modal-backdrop').remove();` in the ` ui.editPostSuccess()` function, still doesn't work though. This way, the specific modal that is being targeted is being closed.

**Comment by payne-chris-r** [comment]
```diff
- .then($(edit).modal('hide'))
+ .then(()=>{
+   $(edit).modal('hide')
+ })
```

**Comment by akradin** [comment]
True, did that and it worsens the issue, the entire div that contains a users posts disappears. Even if you try to hack your way out of it by doing something like:
```js
  .then(() => {
    $(edit).modal('hide');
    $('.show-all-my-posts').show();
  })
```

Also scrolling is still doesn't work. Another clue, clicking a button resolves the scrolling issue, however simply clicking anywhere on the page does not.

**Comment by payne-chris-r** [comment]
Is this doing what you think it is? That `return` feels funky. It might be that you need to do the hide regardless...
```js
  if(!data.blogpost.title || !data.blogpost.content) {
    $('.post-failure').html('Enter title and content please!');
    return;
  }
```

**Comment by sujkid** [comment]
The above return statement makes the submit button unclickable if there is no title or content.. 
the problem exists even if you remove that piece of code...

**Comment by raq929** [comment]
I talked with Alex about this today. We could not isolate the code that is currently hiding the modal. The current plan of attack is to get to the point where the modal DOES NOT HIDE on submit, and then work on having it hide correctly. The plan to do this is to target the modal differently (use an id instead of a class, for example) so that we're sure it's not being targeted by more than one click handler.

**Comment by akradin** [comment]
Update on what Rachel said.
Went ahead and deleted the modal entirely, and re-created it in its simplest form. So now, all you can do is update the title. I changed it so it has IDs instead of classes (for the most part) and the issue persists. The modal still closes when it should not. I have searched the entire project for for the classes/IDs in the modal that might be causing this, but haven't been able to find anything. I have also commented out all clickhandlers one at a time (per Rachel's advice) and the issue persist.

**Comment by akradin** [comment]
I met with Antony and we discussed possible solutions. We combed through the whole project and realized that on login, there is a promise chain that shows a users pages and posts. Antony suggested I replicate this promise chain for editing posts and pages, which I did but the issue persists. Here is what the edit function looks like now.
```js
const onEditPost = function (event) {
  event.preventDefault();
  let id = $(event.target).data('blog-edit');
  let data = getFormFields(this);
  // let edit = "edit-modal-" + id;
  api.editPost(id, data)
  .then((res) => {
    ui.editPostSuccess(res);
    return papi.indexMyPages();
  })
  // .then(() => {
  //   $(edit).modal('hide');
  //   $('.show-all-my-posts').show();
  // })
  .then((res) => {
    pui.indexMyPagesSuccess(res);
    return api.indexMyPosts();
  })
  .then(ui.indexMyPostsSuccess)
  .catch(ui.failure);
};
```

I haven't messed with the `indexMyPostsSuccess` function yet. So maybe the answer lies there?
