### ISSUE TITLE
Random URL Generator

### ISSUE THREAD

**Issue by jdaly04** [ga-wdi-boston/group-project#224]
We're struggling with how to meet the requirement: "Each live survey should be hosted at a unique, randomly-generated URL."

We've looked at closed issues, but there are only 1-2 seemingly relevant ones. Mainly, [(https://github.com/ga-wdi-boston/group-project/issues/29)], seems to be related. However, even looking at the links posted by consultants within that issue and doing outside research, we're really not sure how to implement this. 

It seems like we will have to use something along these lines:
[](https://developer.mozilla.org/en-US/docs/Web/API/Window/location), but it's not really making too much sense just based on documentation.

Any guidance / advice would be greatly appreciated.

**Comment by jdaly04** [comment]
Looks like second like didn't go through... after "...along these lines:", so here it is again:
https://developer.mozilla.org/en-US/docs/Web/API/Window/location

**Comment by raq929** [comment]
Ok. What's happening now? What's the behavior you want? 
I think the first step is to generate the hash and display it to the user creating the survey.
Then you can use location to look at the hash and decide which survey to show.

**Comment by jdaly04** [comment]
Right now, we don't have anything for random url generation. We have buttons for each survey, which we'd like (based on requirements) to be clicked and redirect the user to a randomly generated url with the survey question. That is based on our interpretation of the requirement.

We're not seeing that happen on past projects with this prompt so don't have too much to go off of. I am guessing it would be a click handler for the survey button that somehow triggers the url generation. I'm not quite understanding "...use location to look at the hash and decide which survey to show".

**Comment by RpRoderick** [comment]
So, I used a random math generator to set the hash of each survey on click within the handlebars template itself.  I *believe* this meets the requirements.  Code is below.

```html
{{#each surveys}}
  <div class="imageImage">
        <button class="btn btn-warning" id="{{_id}}" onclick="randomUrl()"> GO TO:  {{title}} </button>

  <script>
  function randomUrl() {
      location.hash = Math.random().toString();
  }
  </script>
</div>
{{/each}}
```

**Comment by payne-chris-r** [comment]
I don't know if that code works or not just by looking at it. When you paste code blocks you need to be cognizant of how it gets formatted in github (or stackoverflow, etc), I've done it for you here, but please take a second look at it (and click preview) in the future! You're more likely to get better help from people on the internet.

On to your comment, does it generate random urls? Doing in-line scripting like that is a little yucky, but that's not the objective right now. If it works, then you should be good!!

**Comment by payne-chris-r** [comment]
Are you actually storing the random url anywhere? The purpose of the requirement is so that you can send me a URL that I can find A SPECIFIC survey somewhere. This kind of just looks like the button sends you to a random url, but without looking at the rest of your code I can't be sure.

**Comment by jdaly04** [comment]
We are not currently storing the random url anywhere, and it's certainly an ugly way of sort of achieving what we're after. We will have to figure out how to store it I guess.

**Comment by jdaly04** [comment]
I'm closing this based on Ryan's post (which fixed original issue), but we're opening another issue to figure out how to save url / get handlebars working properly.
