### ISSUE TITLE
form refreshes page on submit

### ISSUE THREAD

**Issue by RpRoderick** [ga-wdi-boston/group-project#225]
I have two separate forms, each one is within a handlebars template.  Both of them refresh the page on submit, SOMETIMES.  Not always, I cannot reproduce any sort of consistency with the error.  I have preventdefault built in to the event functions.  Doesn't seem to matter.  Here is the code.

**Comment by RpRoderick** [comment]
```{{#each surveys}}
  <div class="imageImage">
         <button class="btn btn-warning" id="{{_id}}"> GO TO:  {{title}} </button>
  </div>
  <div class="deleteImageImage">
    <form id="delSurvey">
      <fieldset>
        <input type="text" value="{{_id}}">
        <input type="submit" name="submit" value="DELETE!">
      </fieldset>
    </form>
  </div>
  {{/each}}```

**Comment by RpRoderick** [comment]
```
const onDeleteSurvey = function (event) {
  event.preventDefault();
  let deleteSurvey = getFormFields(event.target);
  api.deleteSurvey(deleteSurvey)
    .then(ui.deleteSurveySuccess)
    .catch(ui.deleteSurveyFailure);
};
```

**Comment by RpRoderick** [comment]
```
const addClueHandlers = () => {
  $('#questionAppend').on('submit', onQuestionAppend);
  // $('#displayAllCurrentUsersSurveys').on('submit', onDeleteSurvey);
  $('#delSurvey').on('submit', onDeleteSurvey);
  $('#answerAppend').on('submit', onAppendAnswer);
  $('#viewYourSurveysAndAnswers').on('click', onViewYourSurveys);
  $('#viewAllSurveys').on('click', onViewAllSurveys);
};
```

**Comment by payne-chris-r** [comment]
If they're handlebars templates, the buttons likely don't exist when you try to attach the click handlers. It's a common problem. Try just putting the following in your handler:
```js
console.log("click handler <id> fired");
```
my guess is it's not.

**Comment by RpRoderick** [comment]
The prevent default within the function DeleteSurvey was not being assigned to the submit event within clue handlers because of the way handlebars loaded the templates.  So, I declared a function within the handlebars template itself, which was a click event (on the class of button) and added prevent default in that function.  In the end, the way the handlebars template was set up did not work, so the problem was irrelevant, but it was an interesting lesson in handlebars and the way it loads.  Sometimes the events would load one way, sometimes they would load another way, so it was a little difficult to pin down the error because it didn't always happen.  The takeaway is to make sure your prevent default is working the way you think
