### ISSUE TITLE
my backend repo is not pulling down changes

### ISSUE THREAD

**Issue by RpRoderick** [ga-wdi-boston/group-project#227]
Remotes are correct.  When I git pull origin master, it says that it is up to date, yet it doesn't actually pull down changes.  I can git log and see julia's commits, but my atom files are not updated with changes.  I can't figure out why.

**Comment by BenGitsCode** [comment]
Have you tried quitting entirely, and reopening atom?

**Comment by BenGitsCode** [comment]
Have you tried quitting e1

**Comment by RpRoderick** [comment]
yes, I even restarted computer.  Same deal.  What do you mean by e1?

**Comment by BenGitsCode** [comment]
Oh that was a typo, ignore it. 

The commits your seeing locally, but not seeing in Atom, you can see those commits on github, with the code you're expecting to see locally?

**Comment by RpRoderick** [comment]
yes exactly.  The code on github is up to date, I can git log and see the commits, but I do not see the commits locally on atom.  When I pull down, there are no errors and terminal tells me that everything is up to date.  I feel like I'm missing something simple here...

**Comment by RpRoderick** [comment]
Well, I don't know what fixed it.  It seems that the data for pulling in the commit was there, but it was not DISPLAYING locally.  We tricked the local machine by making a new branch, manually copy and pasting the changes from github onto my local atom file, and merging back into master.  It seems to have worked.
