### ISSUE TITLE
Rename to `team-project`

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/group-project#229]
To better reflect goal (teamwork).

**Comment by BenGitsCode** [comment]
This was brought up again in planning 1/25/17 resounding agreement in the room. 

Someone with permission needs to be pinged to make this change by whoever is tasked with this update in cohort 016.

**Comment by gaand** [comment]
@raq929 I think you may have missed a step:  https://github.com/orgs/ga-wdi-boston/projects/3

**Comment by jrhorn424** [comment]
@gaand Has my recent change to #69 addressed your concern?
