### ISSUE TITLE
Fork/Clone Existing Back-End won't allow to set secrets

### ISSUE THREAD

**Issue by jbuzzanco** [ga-wdi-boston/group-project#231]
Hello,

I am trying to use the existing front-end & back-end from our group project by forking-cloning as @payne-chris-r suggested to have my own back-end repository for resubmission on the way out of class today.  I am following the [express-api template](https://github.com/ga-wdi-boston/express-api) and want to set secrets as it shows in the steps with this command,
```
sh echo SECRET_KEY=$(/usr/local/opt/openssl/bin/openssl rand -base64 66 | tr -d '\n') >>.env
```
but it returns the error. 
```
/bin/echo: /bin/echo: cannot execute binary file
```

I want to set secrets because I believe it needs them to run successfully and I cloned this back-end from our group back end repo, which didn't have secrets committed, therefore the secrets shouldn't have been cloned with it. It is not allowing sign-in so I can only imagine more problems would arise if it wasn't addressed from here.
Thanks

**Comment by raq929** [comment]
Ah, the `sh` is a typo. Try it without that on the front of the command.

**Comment by jbuzzanco** [comment]
The `sh` typo in given command seemed to be what was wrong with running the server as it generated the .env and nodemon is running now.
