### ISSUE TITLE
Passing multiple hashes to handlebars

### ISSUE THREAD

**Issue by jdaly04** [ga-wdi-boston/group-project#233]
This is related to my previous issue just closed (https://github.com/ga-wdi-boston/group-project/issues/232) 

Now I have the correct object that I want to pass to the handlebars template, but I tried passing it as a second argument and that does not work. Then in googling it, it doesn't seem like you can pass two hashes to a handlebars template so am now trying to find a way to do so.  I also tried adding  separate JQuery specifically for the 'counts' object, but I was still directing it to same template.

This is what I tried (passed 'counts' in addition to 'newData') but that did not work. I tried adding 'counts' directly into the handlebars template, which I didn't really think would work since it's not an attribute of the 'newData' object..it's a separate object. Now, I'm stuck on what else to try.

UI.JS - What I tried passing to handlebars template: 
```js
const viewYourSurveysSuccess = (data) => {
  // store.user = data.user;
  console.log("data is ", data);

  let newData = {
    surveys: data.survey
  };

  console.log('data length is ', data.survey.length);

  for (let i = 0; i < data.survey.length; i++) {
    let answersArr = data.survey[i].answers;

    let counts = {};
    for (let i = 0; i < answersArr.length; i++) {
      let num = answersArr[i];
      counts[num] = counts[num] ? counts[num] + 1 : 1;
    }
      console.log('count is ', counts);
    $('#displayAllCurrentUsersSurveys').show().html(showYourSurveysTemplate(newData, counts));
    $('#myModal1').modal('hide');
    $('#myModal6').modal('show');
  }
};
```

HANDLEBARS TEMPLATE:
```js
{{#each surveys}}

<div class="imageImage">
    <h1>Title: {{title}}</h1>
</div>
<br>
<div class="imageImage">
    <h4>Question: {{question}}</h4>
</div>
<div class="imageImage">
    <h4>Answers: {{answers}}</h4>
</div>
```

**Comment by gaand** [comment]
I'm not quite sure what you're trying to accomplish, but would adding counts as a property of newdata help?

Or maybe adding the counts once calculated to each survey in newdata?

**Comment by jdaly04** [comment]
That is definitely what I am trying to accomplish. I'm trying to pass counts to the handlebars template.

I tried to use Jquery .extend but that did not work, so I'm still not clear on how to add counts to the newData object.

**Comment by jdaly04** [comment]
I'm still struggling with this. I have tried to get counts into the newData object but am not able to successfully do so. I have tried another way of displaying the tallies for each answer (which is what the end goal is), and I am able to console.log the correct data but again don't know how to get that to render in the front-end using the handlebars template I have. I've been working on this for the last hour and fifteen minutes:

UI.JS WITH CORRECT DATA CONSOLE LOGGING:
```js
const viewYourSurveysSuccess = (data) => {
  // store.user = data.user;
  console.log("data is ", data);

  let newData = {
    surveys: data.survey
  };

  console.log('data length is ', data.survey.length);

  for (let i = 0; i < data.survey.length; i++) {
    let answersArr = data.survey[i].answers;

    let a = [], b = [], prev;
    answersArr.sort();
    for ( let i = 0; i < answersArr.length; i++ ) {
        if ( answersArr[i] !== prev ) {
            a.push(answersArr[i]);
            b.push(1);
        } else {
            b[b.length-1]++;
        }
        prev = answersArr[i];
    }
      $('#displayAllCurrentUsersSurveys').show().html(showYourSurveysTemplate(newData));

    for(let i = 0; i < a.length; i++) {
      debugger;
      console.log(b[i], ' people answered ', a[i]);
      $('#answers').text(b[i], ' people answered ', a[i]);
    }
```

HANDLEBARS TEMPLATE I AM TRYING TO GET THIS DATA TO:
```js
{{#each surveys}}

<div class="imageImage">
    <h1>Title: {{title}}</h1>
</div>
<br>
<div class="imageImage">
    <h4>Question: {{question}}</h4>
</div>
<div class="imageImage" id="answers">
    {{!--THIS IS WHERE I WANT THE NEW DATA b[i]:a[i] which is coming from UI.JS--}}
</div>
<div class="imageImage">
  <form class="delSurvey">
    <fieldset>
      <input type="hidden" name="survey_id" value="{{_id}}">
      <input type="submit" name="submit" value="DELETE!">
    </fieldset>
  </form>
</div>
<div class="imageImage" data-id={{_id}}>
  <form class="changeTitle">
    <fieldset>
      <input type="hidden" name="survey[_id]" value="{{_id}}">
      <input type="text" name="survey[title]" value="{{title}}">
      <input type="submit" name="submit" value="Change Title!">
    </fieldset>
  </form>
</div>
<hr>
{{/each}}
```

**Comment by gaand** [comment]
Could you just set answers (or a and b) as properties of newData.surveys?

**Comment by jdaly04** [comment]
I'm going to attempt to implement your suggestion of setting a and b as properties of newData.surveys. I was able to get this to work by changing the viewYourSurveys function and handlebars template to:

UI.JS:
```js
const viewYourSurveysSuccess = (data) => {
  // store.user = data.user;
  let array = data.survey.map(function(survey) {
    survey.answers = survey.answers.reduce((prev, curr) => {
      if (!prev[curr]) {
        prev[curr] = 1;
      } else {
        prev[curr]++;
      }
      return prev;
    }, {});
    return survey;
  });

  // // console.log("answers are", array);
  let newData = {surveys:data.survey};
  $('#displayAllCurrentUsersSurveys').show().html(showYourSurveysTemplate(newData));
  $('#myModal1').modal('hide');
  $('#myModal6').modal('show');
};
```
HANDLEBARS:
{{#each surveys}}

<div class="imageImage">
    <h1>Title: {{title}}</h1>
</div>
<br>
<div class="imageImage">
    <h4>Question: {{question}}</h4>
</div>
<div class="imageImage">
  <h4>Answers:
    {{#each answers as |answer|}}
    <br> {{ @key }}: {{ this }}
    {{/each}}
```

**Comment by jdaly04** [comment]
Correcting formatting of handlebars template:
```js
{{#each surveys}}

<div class="imageImage">
    <h1>Title: {{title}}</h1>
</div>
<br>
<div class="imageImage">
    <h4>Question: {{question}}</h4>
</div>
<div class="imageImage">
  <h4>Answers:
    {{#each answers as |answer|}}
    <br> {{ @key }}: {{ this }}
    {{/each}}
  </h4>
```
