### ISSUE TITLE
Schemas inside Schemas as arrays

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/group-project#241]
We currently have a this schema setup
the answer Schema goes in the question Schema as an array which goes into the surveySchema as an array:
```javascript
const answerSchema = new mongoose.Schema({
  response: {
    type: Boolean,
    required: false,
  }
});

const questionSchema = new mongoose.Schema({
  problem: {
    type: String,
    required: true,
  },
  answers: [answerSchema]
});

const surveySchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
  },
  _owner: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  questions: [questionSchema]
});
```

We are having issues testing scripts for answering a question when it is all arrays in arrays..

**Comment by bernardlee** [comment]
How are you testing this?

**Comment by doremaxime** [comment]
Well we did not cover having schema inside schemas as arrays in class which is why we don't know how to test it.

**Comment by raq929** [comment]
Ok, so you said you're having issues testing it, so that's why we asked. What have you tried?

**Comment by doremaxime** [comment]
Bernard enlightened us on how getFormFields works. 
Conclusion was that we either scrap getFormFields and create the object passed to the back end ourselves, or get the handlebars data to conform to getFormField.
