### ISSUE TITLE
GitHub repo deleted help!

### ISSUE THREAD

**Issue by jwaskow** [ga-wdi-boston/group-project#242]
Hey, so our back-end repo got deleted from github.  We still have the repo locally on our computers, so I don't think we lost any work.  How do we go about fixing this?  I don't want to make any rash decisions.

**Comment by jwaskow** [comment]
Clarifying that this is the repo of the Organization that was deleted.

**Comment by BenGitsCode** [comment]
We'll be right there.

**Comment by raq929** [comment]
Is this resolved? Please update and close if so.

**Comment by jwaskow** [comment]
Sorry, yes it is.

**Comment by raq929** [comment]
Please tell us how you resolved it.

**Comment by jwaskow** [comment]
Ben and Bernard came and helped us, sorry I don't remember the specifics well enough to reproduce it here.  We essentially used one of the local repos we had and added the organization as a remote to it.
