### ISSUE TITLE
Stringify handlebars [object object]

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/group-project#244]
I am trying to display data from backend to frontend with handlebars.

handlebars
```handlebars
{{#each surveys as |survey|}}
<div class="show-survey" survey-id="{{survey._id}}">
  <form>
    <fieldset>
      <label>
        <div>{{survey.title}}</div>
        <div>{{survey.questions}}</div>
        <input type="radio" value="true" data-bind="checked:IsChecked, checkedValue: true"/>True
        <input type="radio" value="false" data-bind="checked:IsChecked, checkedValue: false"/>False
      </label>
      <input data-id="{{survey.id}}" class="answer-question" type="submit" name="submit" value="Submit Answer">
    </fieldset>
  </form>
</div>
{{/each}}
```
The ```{{survey.title}}``` prints the title correctly (as a string).
The ```{{survey.question}}``` prints ```[object object]``` when it should be printing out the question as a string.
This is because the question is a schema as an array embedded in the surveySchema as below:

surveySchema:
```javascript
const questionSchema = new mongoose.Schema({
  problem: {
    type: String,
    required: true,
  },
  answers: [answerSchema] // Ignore this
});

const surveySchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
  },
  _owner: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  questions: [questionSchema] // HERE
}
```

I need to somehow make the question of the survey be stringified and not show as an object...
I have found some sites which seem helpful but do not know how to implement them (specifically which files to put the functions):
_http://stackoverflow.com/questions/22475485/store-json-object-to-html-element-with-handlebars#22509256_
_http://zshawnsyed.com/2015/04/30/output-json-in-handlebars/_

Currently, a team mate is working on a different approach than handlebars but I am trying the handlebar approach.

**Comment by bernardlee** [comment]
> This is because the question is a schema as an array

You answered your own question here.

**Comment by doremaxime** [comment]
haha yeah, so i tried having it as the below code to try to get it to conform to the getFormField function but no luck:
```{{survey.questions[response}}``` but the linter does not allow it
```{{survey[questions[response]]}}``` isn't allowed either.
I remember that you got it to work for a second with a format that I can't replicate as you went on to show us how to create create our own data object in the events.js

**Comment by bernardlee** [comment]
That is unrelated.  What is the value of `survey.questions`?

**Comment by doremaxime** [comment]
Well if I ```console.log(data)``` the console will show the following:
![screen shot 2017-03-08 at 8 39 22 pm](https://cloud.githubusercontent.com/assets/24608045/23732147/5f01376e-043f-11e7-8a56-70424bc241c9.png)

**Comment by doremaxime** [comment]
Showing that there is the answers, and the problem 'is it raining?' inside (the 4th question as an example'

**Comment by bernardlee** [comment]
I should have asked, "what type of value is `survey.questions`?"

**Comment by doremaxime** [comment]
well the question is an array object made of an answer (which is an array of boolean value) and of a response (which is a string value).

**Comment by bernardlee** [comment]
What can you do to and with an array?  What type of value is `surveys`?

**Comment by doremaxime** [comment]
hmmm.... well an array can be be applied many different methods to get the right index/element out. 
But I don't see how I can enter JS into HTML to filter out the unwanted data.
I believe survey to be an object because of how the Schema is written (keys & values) and the value of it's keys vary between strings and booleans, some of which being in array.

**Comment by bernardlee** [comment]
Look at `surveys` in the screenshot that you posted and look at the block of code in your first post.

**Comment by doremaxime** [comment]
Ok, since there are multiple surveys, surveys is an array of surveys, not sure how i missed that. The nesting continues...

**Comment by doremaxime** [comment]
In an object, there is an array or surveys, which is an object with an array of question.

**Comment by bernardlee** [comment]
Yes, `surveys` and `questions` are both arrays.  How did you render the `surveys` array in your Handlebars template?

**Comment by doremaxime** [comment]
Well with an **each**: ```{{#each surveys as |survey|}}```
but since there is only one question, i didn't see an **each** being necessary.. but since questions has multiple keys, i see how that is needed now. I will try that tonight and reply in the morning.

**Comment by bernardlee** [comment]
That sounds good.  Please keep us updated.

**Comment by doremaxime** [comment]
Solution:

Have an **each** inside the main **each** for ```<div>{{question.problem}}</div>``` such that:

```handlebars
{{#each surveys as |survey|}}
<div class="show-survey" survey-id="{{survey._id}}">
  <form>
    <fieldset>
      <label>
        <div>{{survey.title}}</div>

        {{#each survey.questions as |question|}}
        <div>{{question.problem}}</div>
        {{/each}}

        <input type="radio" name="surveys[questions][answer][response]" value="true" data-bind="checked:surveys[questions][answer][response], checkedValue: true"/>True
        <input type="radio" name="surveys[questions][answer][response]" value="false" data-bind="checked:surveys[questions][answer][response], checkedValue: false"/>False
      </label>
      <input data-id="{{survey.id}}" class="answer-question" type="submit" name="submit" value="Submit Answer">
    </fieldset>
  </form>
</div>
{{/each}}
```

This will iterate through the array and pick the key that is needed (in this case being problem).

Thank you for helping me through this Bernard! 
Appreciate how it was hints for me to work through it rather than the solution itself.

**Comment by bernardlee** [comment]
This should be a separate issue, but don't put custom attributes in HTML elements.

```html
<div class="show-survey" survey-id="{{survey._id}}">
```

Instead, use a combination of [data-*](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*) and jQuery's [.data()](https://api.jquery.com/data/) method.

Also, you shouldn't access attributes that have an underscore as a prefix (e.g., `_id`) since those are typically private variables that aren't meant to be accessed outside of its instance or scope.
