### ISSUE TITLE
Looking for clarification of pages versus blog

### ISSUE THREAD

**Issue by novakw267** [ga-wdi-boston/group-project#248]
Ideally if someone is available to chat and field a few questions, we were just looking for clarification between the expectations of the difference between pages and blog.

**Comment by raq929** [comment]
Basically, it's two resources. Pages is where you could make a static page, like "About Me" or "My favorite horses" and a blog is a single page that has multiple posts on it.

**Comment by novakw267** [comment]
Thank you Rachel that talk was helpful. It gave us a few great ideas.

**Comment by raq929** [comment]
Bill, this is not an appropriate way to close an issue. Please post with what you learned. Post the pictures from the whiteboard. The issue queue is meant to solidify your understanding by having you write the solution as well as help future developers who have the same issue. Your response does neither of those things. Please comment again with what you learned. Thanks!

**Comment by novakw267** [comment]
Rachel came in and walked us through blogs and posts.

 Blog gets content added to that page, when you make a new post it gets added to that page in chronological order. However with pages, each new post to a page is a separate piece of content. 

A user can have many blogs and many pages, however the blogs will be stored in the same place, where as the pages each would have their own place. In addition a page should have more options to alter how they looks and the content that is being displayed. 

For the sake of this application our pages will probably not have separate urls, and won't be loaded on separate pages. 

That is my understanding of what we went over.

**Comment by raq929** [comment]
I prefer to think of what you're calling 'blogs' as 'blog posts'. But essentially, yes. 
Frontend routing is a stretch goal for this prompt. 
Thanks for the update!
