### ISSUE TITLE
Question about requirements for eCommerce

### ISSUE THREAD

**Issue by laurpaik-zz** [ga-wdi-boston/group-project#249]
To what extent do we need to implement Stripe? Do we need to send anything to our database, keep logs of our tokens that are passed through the form, something else...? Can we get some structure?

**Comment by jrhorn424** [comment]
Is Stripe processing a test payment?

**Comment by laurpaik-zz** [comment]
I mean... so far, the checkmark turns green and we get a POST success on the server.

**Comment by raq929** [comment]
I think you're fine then.

**Comment by laurpaik-zz** [comment]
Thank you!
