### ISSUE TITLE
How To Create A Second Update

### ISSUE THREAD

**Issue by skylarkJ** [ga-wdi-boston/group-project#253]
Issue:
We would like to get an advice how to do it. We are having an update on Question to the Survey and would like to get a second update on an answer to a question.

**Comment by BenGitsCode** [comment]
What have you tried so far?

**Comment by doremaxime** [comment]
We have tried having one update function for both but it's bitting us in the butt because updating a question needs to be owned by the user that created the survey, but the update for the answer can be done by anyone. 
Furthermore, each needs to do 2 different things: 
Questions: updates the data of the questions by patching a new question to the survey
Answer: patches the answer to the question it belongs to.

**Comment by doremaxime** [comment]
Therefore we need to make a second update action/function but we have never dealt with creating more functions that will talk to the back end. However, if we make a new ajax function that is also a patch, how will the back end know that it should do the other patch action?

**Comment by raq929** [comment]
Call it something else, like update_answers, or something, and create a route to it. You can model it on the sign-up route - that's the same deal, a route that has a differently named controller function.

You'll need to have your front-end direct to that different route.

**Comment by doremaxime** [comment]
Thanks Rachel, we are currently attempting to make an if statement in the 1 update function in the controller that will check for owner ship first which will decide which update to make (question or answer). Will open back up when there is a solution :)

**Comment by doremaxime** [comment]
Update function solution:

```javascript
// identifies if it's the user's survey
      if (survey._owner == req.user.id) {
// let's that user add questions to her survey and blocks a user from updating someone else's survey
        survey.questions[survey.questions.length] = req.body.survey.questions;
      } else {
// let's all other user update an answer to a survey except the user who created the survey
        for (let i = 0; i < survey.questions.length; i++) {
          let newAnswers = survey.questions[i].answers.length;
// adds the answers to the array of answers
          survey.questions[i].answers[newAnswers] = survey.questions[i].answers[newAnswers] ||     req.body.survey.questions[i].answers;
        }
      }
```
