### ISSUE TITLE
How/Where to require handlebars helpers?

### ISSUE THREAD

**Issue by jwaskow** [ga-wdi-boston/group-project#254]
We render a user's blog posts through handlebars.  The issue is that handlebars iterates through the response in order, so the most recently created posts get rendered last.  I think a blog should show most recent posts first, so I'm trying to figure out how to make it iterate in reverse.  I found a collection of helpers that might be useful (https://github.com/diy/handlebars-helpers).  The one I want to use is called 'each-reverse'.

I did npm install and I can see the diy-handlebars-helpers folder in the node_modules folder.  The thing is I don't know how to require the folder so I can use the helpers.  The instructions on that GitHub page just say to use 
```
var helpers = require('diy-handlebars-helpers');
```
but I don't know which file I should use this code in.  The handlebars files are html, so I tried putting it in a script tag in the handlebars file, but that didn't work.  How can I require this without having the 'require' line of code get rendered into html through handlebars?

Thanks.

**Comment by raq929** [comment]
I think it would be easier to re-order the data before it gets to handlebars, either in your success function on the front end, or on the back end before you send the data to the client.

**Comment by ladypinetree** [comment]
We were able to solve this by adding `data.blogs = data.blogs.reverse();` before the data was sent to handlebars.
