### ISSUE TITLE
Project Status Review Request

### ISSUE THREAD

**Issue by cob0910** [ga-wdi-boston/group-project#255]
Could consultants please check out our deployed app? We would like to confirm if it appears complete and seems to meet expectations? We'd appreciate notes about anything you see anything we've missed that MUST be fixed or just suggestions.

We will be working on styling and the READMEs this weekend and if time allows further Google API interaction.

DEPLOYED: https://squad-sol.github.io/bucket-browser/
FRONTEND: https://github.com/Squad-SOL/bucket-browser
BACKEND: https://github.com/Squad-SOL/bucket-api
HEROKU: https://fast-atoll-26007.herokuapp.com

**Comment by MicFin** [comment]
Potential image path errors.
![screen shot 2017-03-10 at 3 16 14 pm](https://cloud.githubusercontent.com/assets/5384023/23811610/b3fd8de2-05a4-11e7-8c99-4253977202bb.png)

**Comment by cob0910** [comment]
Those are known and part of style fixes! Thanks @MicFin!

**Comment by raq929** [comment]
Is it supposed to be dropping pins on the map? Because it does not seem to be doing that...

**Comment by cob0910** [comment]
@raq929 it does but I believe you have to click an autofill suggestion for it to place the pin.

**Comment by MicFin** [comment]
1.  When I sign up with a password that doesnt match and an invalid email, I do not get an error message.
2.  When I sign in with wrong password, the pop up closes so I cant tell if I succeded or not unless I open the pop up again to see the message that I gave the wrong password.
3.  When I change password with **wrong** initial password, the pop up closes so I cant tell if I succeded or not unless I open the pop up again to see the message that I gave the wrong password.
4.  When I change password with **correct** initial password, the pop up closes so I cant tell if I succeded or not unless I open the pop up again to see the message that I succeeded
5.  When I create a new restaurant with blank info, I do not get an error message.
6.  The restaurant does not get added to the map when I create it, not sure if it is supposed to but a pin is only added if I type an address into the search field.

**Comment by cob0910** [comment]
@MicFin 
1-4 - (edit) interestingly these all work for me in chrome and safari. did you use a different browser?
5 - great catch, thank you! we hadn't tried to send an incomplete restaurant yet
6 - at this point the map is to search for a place and then you save what details you have manually. We have not been able to figure out how to save the data from the pin to our own database and then how to get those pins to redisplay for the user.

Thank you very much!

**Comment by MicFin** [comment]
Ok let's close this issue.  The problem with an issue like this is it is open ended.  I could keep finding potential bugs and you could keep adding them to your work queue.  Let's try more focused issues that have a solution.  Maybe we can open an issue for testing a specific feature.  

Here's a potential idea for how to post an issue like this

>Title: "Sign in/out user bugs"
>Description: "We are requesting fellow developer(s) or consultant(s) test our sign in and sign out workflow.  We will be closing this issue on Friday at 5pm and will address any bugs found.  Here are the user stories we would like feedback on:
>1.  When a user signs up with an email that is already taken, display an error message
>2.  When a user signs up with passwords that do not match, display an error message
>3.  When a user signs up correctly, display a success message
>..etc.

**Comment by raq929** [comment]
@cathyob I suggest telling your users about the pins on your site,
otherwise users like me won't know what's wrong. (Ie: don't see any pins?
Do XYZ)
