### ISSUE TITLE
header is not present on the requested resource

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/group-project#256]
I have just deployed my app with heroku and the front end is hosted on Github.

The error message displaying in the console when trying to sign up is:
```
XMLHttpRequest cannot load https://ga-wdi-boston.herokuapp.com/sign-up. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://gzmj-survey.github.io' is therefore not allowed access. The response had HTTP status code 400.
```

From the error message, i believe i need to add a ```Access-Control-Allow-Origin``` header the requested resource.

The **API** file is the only place that has 'headers' from my experience therefore i think i need to add another header like the below code?
```javascript
const signUp = function(data) {
  return $.ajax({
    url: config.apiOrigin + '/sign-up',
    method: 'POST',
    // headers: Access-Control-Allow-Origin,
    data,
  });
};
```
We have just never cover any such header in class.

Not sure if needed but this is involved with the back end
**config.js**
```javascript
const config = {
  apiOrigins: {
    production: 'https://safe-citadel-54247.herokuapp.com/',
    development: 'http://localhost:4741',
  },
};
```

**Comment by bernardlee** [comment]
> The API file is the only place that has 'headers' from my experience therefore i think i need to add another header like the below code?

Nope.

> Not sure if needed but this is involved with the back end config.js

Is that a local version or a remote version of `config.js`?

**Comment by doremaxime** [comment]
When I opened the issue it was just local (a mistake i should know better at this point) but now it is the remote and deployed version and is showing the same error message in the browser console.

**Comment by bernardlee** [comment]
What is the error?

**Comment by doremaxime** [comment]
After 10ish minutes the message has changed to:
![screen shot 2017-03-11 at 9 42 43 pm](https://cloud.githubusercontent.com/assets/24608045/23828557/ba78879e-06a3-11e7-91eb-d3fa7fc82653.png)

So if the 'Access-Control-Allow-Origin' header has a value 'https://doremaxime.github.io' that is not equal to the supplied origin. The origin being the organization's github (https://gzmj-survey.github.io) 
From what I understand there are two point that need to match and currently, one has the correct header and the other doesn't. 

I believe the error has occurred because the header should be **https://gzmj-survey.github.io** and that it currently is **https://doremaxime.github.io**.

The error must have occurred at some point in the deployment as I did it from my computer <doremaxime> and I should have done something that it should have come from the organization's github <gzmj-survey>.

Although I could be over thinking this...

**Comment by doremaxime** [comment]
oh my.... I am just now seeing there are 2 ```/``` in the path.
I will make the adjustment and reply

**Comment by doremaxime** [comment]
Nope, same error message is still there after making the adjustment of the production URL which had an extra ```/```

**Comment by bernardlee** [comment]
What is the `CLIENT_ORIGIN` environmental variable set to on the deployed back end's Heroku server?

**Comment by doremaxime** [comment]
```CLIENT_ORIGIN``` is **https://doremaxime.github.io**
I should change that to **https://gzmj-survey.github.io**  is that right?

**Comment by bernardlee** [comment]
Try it.  Check the "Deploying to Heroku" section on the [Express API Deployment Guide](https://github.com/ga-wdi-boston/express-api-deployment-guide).

**Comment by doremaxime** [comment]
Ok, so that has helped I believe as the error message is now more simple:
![screen shot 2017-03-11 at 10 15 19 pm](https://cloud.githubusercontent.com/assets/24608045/23828701/5bb4ddca-06a8-11e7-8366-e86ec4b19b63.png)

Checking my old apps, the URLs also have the 2 ```//``` before the sign-up such as:
https://daily-boulders.herokuapp.com//sign-up

Let me change it back to 2 ```//``` and will update after.

**Comment by bernardlee** [comment]
I suspect that the bad request error is from your attempt to create a/a, b/b, or c/c for email/password combinations.  I created those using cURL a couple of hours ago.  As for the double forward slash, check #250.

**Comment by doremaxime** [comment]
I checked that issue which lead me to believe there should be one ```/``` which is why i took it out before but it still didn't work. Checking my 2nd project and it had 2 ```//``` in the config file and the browser console so i put it back. now i'm more confused about it.

As for: I suspect that the bad request error is from your attempt to create a/a, b/b, or c/c for email/password combinations.
I thought so too so i tried long random characters and it doesn't change the error :(

**Comment by bernardlee** [comment]
Did you try creating a new account with random characters as email and password combinations in both cases (one forward slash and two forward slashes)?

**Comment by doremaxime** [comment]
It worked! 
I have no idea why having one ```/``` works for this production url and not my past project but it  works...


Solution code for config.js:
```javascript
'use strict';

const config = {
  apiOrigins: {
    production: 'https://safe-citadel-54247.herokuapp.com',
    development: 'http://localhost:4741',
  },
};

module.exports = config;
```

and trying multiple random characters when signing up.

Bernard sweeping in for the win again! Big thank you from team GZMJ!

**Comment by bernardlee** [comment]
> I have no idea why having one / works for this production url and not my past project but it works...

This one uses Express.js and the other uses Ruby on Rails.  Not all frameworks parse routes the same way.
