### ISSUE TITLE
Page refresh, submit handlers in handlebars

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/group-project#257]
Status:
Be able to call the function **onUpdateSurveyQuestion** when clicking on "add question" which should submit a form.

Issue:
Page refreshed when clicking the "add question".

Goal:
Page does not refresh when clicking "add-question" and calls the function 
**onUpdateSurveyQuestion** 

Handler:
```javascript
const addHandlers = () => {
  $('.index-display').on('submit', '#question-create', onUpdateSurveyQuestion);
};
```
There are other handlers that are also inside index-display that work (not forms though)
The div with the class **index-display** exists when the document is loaded.

onUpdateSurveyQuestion:
```javascript
const onUpdateSurveyQuestion = function(event) {
  debugger; 
  event.preventDefault();

  let data = getFormFields(event.target);

  api.updateSurveyQuestion(data)
    .then(ui.successQuestionCreate)
    .catch(ui.failureSurveyCreate);
};
```
 I put the debugger in there to see if it event.preventDefault is the error but browser doesn't get to that point.

handlebars:
```handlebars
<form class="style-form" id="question-create" data-id="{{survey.id}}">
          <fieldset>
            <label>
              <input class="field-style" type="text" name="survey[questions[problem]]" placeholder="Add Question To Survey">
              <input class="field-style" type="text" name="survey[{{survey._id}}]" value="{{survey._id}}" placeholder="Survey ID">
            </label>
            <input class="survey-button" data-id="{{survey._id}}" type="submit" name="submit" value="Add Question">
          </fieldset>
        </form>
```

I checkout the relevant issue #225 but the solution code was not posted and I do not understand how he added another ```event.preventDefault();``` inside handlebars.

**Comment by bernardlee** [comment]
Is that the entirety of the Handlebars template or just part of it?

**Comment by doremaxime** [comment]
This was only part of it.
This is the entirety:
```handlebars
<div id="surveys-box">
{{#each surveys as |survey|}}
<div class="show-survey" survey-id="{{survey._id}}">
  <form>
    <fieldset>
      <input type="button" class="survey-show" value="{{survey.title}}" data-id="{{survey._id}}">
      <label class="survey-contents">
        {{survey.title}}


        <form class="style-form" id="question-create" data-id="{{survey.id}}">
          <fieldset>
            <label>
              <input class="field-style" type="text" name="survey[questions[problem]]" placeholder="Add Question To Survey">
              <input class="field-style" type="text" name="survey[{{survey._id}}]" value="{{survey._id}}" placeholder="Survey ID">
            </label>
            <input class="survey-button" data-id="{{survey._id}}" type="submit" name="submit" value="Add Question">
          </fieldset>
        </form>


        <input type="button" data-id="{{survey._id}}" value="Delete Survey" class="survey-destroy delete-style">
        <label class="questions-style">
          {{#each survey.questions as |question|}}
          <div class="survey-questions">
            <div class="survey-problem question-style">{{question.problem}}</div>
          </div>
          <input class="survey-id" value="{{survey._id}}" style="display: none;">

          <input class="survey-problem-id" value="{{question._id}}" style="display: none;">
          <div class="box-radios">
          <div class="col-1"><input type="radio" name="{{question.id}}" value=true data-bind="checked:IsChecked, checkedValue: true"/>Yes</div>
          <div class="col-2"><input type="radio" name="{{question.id}}" value=false data-bind="checked:IsChecked, checkedValue: true"/>No</div>
          </div>
          {{/each}}
        </label>
        <input data-id="{{survey.id}}" class="answer-question" type="submit" name="submit" value="Submit Answer">
    </label>
    </fieldset>
  </form>
</div>
{{/each}}
</div>

```

**Comment by bernardlee** [comment]
Consider how the "Add Question" button is rendered and how it is selected.

**Comment by doremaxime** [comment]
hmm...

Not 100% sure about the difference between rendering and selecting the button.

I believe the submit handler 
``` $('.index-display').on('submit', '#question-create', onUpdateSurveyQuestion);``` 
renders it. 
At least in my mind it does because **index-display** is loaded when the document is initially loaded. **#question-create** is placed in the form.

As for the select:
it is selected by the form?  As in the inputs/labels/fieldset are in the form.

What my eyes see as what my be causing this is that the form, is in another form.
Looking at it now I am wondering what the other form is doing...
I'm going to take that out and test it.

**Comment by bernardlee** [comment]
Hint: Look at how `surveys` is rendered.

Also, try not to access attributes that have `_` as a prefix.

**Comment by doremaxime** [comment]
Does one need to include all the divs that the submit is in to the handler?

Something like:
```javascript
const addHandlers = () => {
  $('.index-display', '#surveys-box' , '.show-survey').on('submit', '#question-create', onUpdateSurveyQuestion);
};
```

**Comment by bernardlee** [comment]
> Does one need to include all the divs that the submit is in to the handler?

No.

How many "Add Question" buttons get rendered on the same page?

**Comment by doremaxime** [comment]
So that specific "add-question" is not being rendered?
I'm thinking that because i believe to have found a solution! 

With the following code, the page is not refreshing and the function is being called:
handler:
```javascript
  $('.index-display').on('submit', $('.question-create').val(), onUpdateSurveyQuestion);
```

handlebars:
```handlebars
<div id="surveys-box">
{{#each surveys as |survey|}}
<div class="show-survey" survey-id="{{survey._id}}">
  <form>
    <fieldset>
      <input type="button" class="survey-show" value="{{survey.title}}" data-id="{{survey._id}}">
      <label class="survey-contents">
        {{survey.title}}


        <form class="style-form question-create" data-id="{{survey.id}}">
          <fieldset>
            <label>
              <input class="field-style" type="text" name="survey[questions[problem]]" placeholder="Add Question To Survey">
              <input class="field-style" type="text" name="survey[{{survey._id}}]" value="{{survey._id}}" placeholder="Survey ID">
            </label>
            <input class="survey-button" data-id="{{survey._id}}" type="submit" name="submit" value="Add Question">
          </fieldset>
        </form>


        <input type="button" data-id="{{survey._id}}" value="Delete Survey" class="survey-destroy delete-style">
        <label class="questions-style">
          {{#each survey.questions as |question|}}
          <div class="survey-questions">
            <div class="survey-problem question-style">{{question.problem}}</div>
          </div>
          <input class="survey-id" value="{{survey._id}}" style="display: none;">

          <input class="survey-problem-id" value="{{question._id}}" style="display: none;">
          <div class="box-radios">
          <div class="col-1"><input type="radio" name="{{question.id}}" value=true data-bind="checked:IsChecked, checkedValue: true"/>Yes</div>
          <div class="col-2"><input type="radio" name="{{question.id}}" value=false data-bind="checked:IsChecked, checkedValue: true"/>No</div>
          </div>
          {{/each}}
        </label>
        <input data-id="{{survey.id}}" class="answer-question" type="submit" name="submit" value="Submit Answer">
    </label>
    </fieldset>
  </form>
</div>
{{/each}}
</div>
```

For other developers looking: the data is not being passed right but that's another issue.

**Comment by bernardlee** [comment]
> So that specific "add-question" is not being rendered?

No.  Answer the question that I asked and look at how the "Add Question" button is selected when an event handler gets attached to it.

**Comment by doremaxime** [comment]
Sorry, i thought that was more of a hint, i'm just not sure what the difference between render and selected is, which i added to a previous comment.

In the current case, only one shows up, but users can make it to have multiple show up too.

So "add question" button question is selected by having the same data-id as the form?

Furthermore, a team mate just got it to work in a way that makes no sense as the click handler uses ```".question-create"```whereas in the form it's an id! but somehow it works.

**Comment by bernardlee** [comment]
> Sorry, i thought that was more of a hint, i'm just not sure what the difference between render and selected is, which i added to a previous comment.

No apology needed.  When I was referring to rendering, I meant the way that the elements were being drawn or output onto the page.

You and a team member did find a solution, but I'm continuing to ask these questions because there isn't an answer regarding an understanding of why it wasn't working.

Let's assume that it's still at a stage where it isn't working.  `surveys` is an array and being rendered by the Handlebars template, so there are potentially zero, one, or more surveys.  This means that there can be potentially more than one "Add Question" button.  Each of these buttons has an `id` attribute of `question-create`.  What's the problem here?

**Comment by doremaxime** [comment]
Well it's that they all have the same id. 
I just thought that since there is only one it would work.

**Comment by bernardlee** [comment]
That's what I was looking for.  There isn't only one being rendered.  Apologies, since I neglected to supply this next hint earlier on.  Look in the `index.html` file.

**Comment by doremaxime** [comment]
Wow.. there is one in the html but it's commented out so the browser still reads and registers 2 places that have the id.

**Comment by bernardlee** [comment]
It's not commented out.

**Comment by doremaxime** [comment]
oh in my local it is

**Comment by bernardlee** [comment]
If it's commented out on your local version, then it should be fine.  I was using the latest version in the repository as a reference.

**Comment by doremaxime** [comment]
Cool.

solution update in handlebars:
```handlebars
        <form class="style-form" id="question-create{{survey.id}}" data-id="{{survey.id}}">
```

THANK YOU bernard!
