### ISSUE TITLE
console.log/error requirement

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/group-project#258]
Taking out all the console.log/error is a requirement.
However, there are some in the backend ```server.js``` and  in ```spec/server.spec.js```.
Because we are not taught about these files, i am not sure if the requirements are met if I don't  comment those out too....

![screen shot 2017-03-13 at 12 16 26 am](https://cloud.githubusercontent.com/assets/24608045/23841314/b4343b5a-0782-11e7-9c06-a7134f442168.png)
![screen shot 2017-03-13 at 12 16 47 am](https://cloud.githubusercontent.com/assets/24608045/23841313/b433460a-0782-11e7-897a-a70ec84bdad0.png)

**Comment by bernardlee** [comment]
Leaving those should be fine.  The files in `spec` are for testing so they can be left alone.
