### ISSUE TITLE
Consultation Request - CMS

### ISSUE THREAD

**Issue by cpm5041** [ga-wdi-boston/group-project#266]
Our team, Shake n' Bake, would like to meet with a consultant to discuss project requirements and strategy. 

Prompt: Content Management System

Build an app to build a website! Your app must allow non-technical users to write blog posts and pages for the site. When a visitor visits your site, they should see content. When a user logs in, they should see a dashboard that lets them create and edit new posts or pages.

Specifically, we would like to talk through the relationships between users and posts/pages and general project requirements. Thanks!

**Comment by BenGitsCode** [comment]
Before meeting, can you share your wireframes, user stories, and ERD as they are now?

What about the posts/pages user relationship do you have questions about?

**Comment by scottyscripts** [comment]
can you please post wireframes, ERD, and user stories that you have now?

**Comment by cpm5041** [comment]
Closing as this was resolved on the other repo.
