### ISSUE TITLE
Consultation Request - Surveys

### ISSUE THREAD

**Issue by octater** [ga-wdi-boston/group-project#267]
Team Beerboys would like a consultation to discuss project direction.  Attached are the wireframes, users stories, and ERD.

<img width="827" alt="screen shot 2017-05-16 at 9 40 35 am" src="https://cloud.githubusercontent.com/assets/26232064/26109105/728a24f4-3a1c-11e7-83b4-33bdc1d09d6c.png">

![](https://files.slack.com/files-tmb/T0351JZQ0-F5D4ECASU-2663bce5d4/img_20170515_151136273_1024.jpg)

1. As a surveyor, I want to sign up, so that I can create surveys.
2. As a surveyor, I want to sign in, so that I can create surveys.
3. As a surveyor, I want to change a password so that I can protect my identity.
4. As a surveyor, I want to sign out, so that I can safely log out and no one can see my survey data.
5. As a surveyor, I want to create a survey and generate a link to each survey.
6. As a surveyor, I want to update existing surveys so that I can modify them.
7. As a surveyor, I want to delete a survey if it is no longer needed.
8. As a surveyor, I want to be able to view all results of a survey in a dashboard.
9. As a respondent, I want to be able to fill out the survey.
10.As a respondent, I want to be able to submit the survey.

**Comment by octater** [comment]
![img_20170515_151136273](https://cloud.githubusercontent.com/assets/26232064/26109238/e2cacde0-3a1c-11e7-814b-a263b0c95a0e.jpg)

**Comment by tvcrawley** [comment]
@octater Please close this issue, if all questions have been satisfactorily answered.

**Comment by octater** [comment]
Thanks so much Toni and Ben
