### ISSUE TITLE
need consult on project we requested the issue yesterday 

### ISSUE THREAD

**Issue by Ryaong792** [ga-wdi-boston/group-project#268]
Was not aware that we needed to be in GIT not enterprise till today.  

See images and ERD/USER STORIES etc
https://git.generalassemb.ly/ga-wdi-boston/team-project/issues/272

**Comment by tvcrawley** [comment]
@Ryaong792 Please close this issue, if all questions have been satisfactorily answered.

**Comment by Ryaong792** [comment]
completed closing
