### ISSUE TITLE
Request for initial team project consult - Femme Squad Plus One 

### ISSUE THREAD

**Issue by angmas** [ga-wdi-boston/group-project#269]
copied from [enterprise version of team-project repo](https://git.generalassemb.ly/ga-wdi-boston/team-project/issues/268)

Hi,

Can we meet with a consultant to have an initial team project consult?

Thanks,
Femme Squad Plus One

**User Stories**
![image uploaded from ios](https://git.generalassemb.ly/storage/user/5750/files/87cbc0b8-3984-11e7-9e78-3929ad78a7b6)

1. Create an account
2. Sign in with my account name and password
3. Be able to change my password
4. Be able to sign out of my account 
5. See all files uploaded to the app
    1. See them by category/tag
    2. See who owns the files
    3. Download any file regardless of owner

As an owner, I want to: 
1. Upload/save a file to my own account
2. Create/update/delete my own file structure for my saved files
3. Delete a file from my own account
4. Make updates to an existing file
5. Assign tag(s) to my files (at creation, at any time after creation) 
6. Know/see when my file was uploaded/created
7. Know/see when my file was modified

@nsavanorkejoyce @aeabbott @jim-moody

**Comment by tvcrawley** [comment]
@angmas Please close this issue, if all questions have been satisfactorily answered.

**Comment by angmas** [comment]
Closing issue: we got our answers. Thanks!
