### ISSUE TITLE
Need review of cart and order schemas

### ISSUE THREAD

**Issue by vanduong28** [ga-wdi-boston/group-project#272]
We plan to have a cart schema and an order schema and when a user submits an order we intend to have the cart information populate in a 'carts' array within the order schema. In doing so an order collection will contain an array of all of the user's submitted cart orders. In the order.js we have a productSchema defined but thinking we shouldn't need this as there is a productSchema in the cart.js that we expect to pass the product information. Since the orderSchema contains an array of carts we assume the product information can be accessed through these cart objects. Please review our schema and let us know if we are on the right track before moving forward.

cart.js
```
'use strict'

const mongoose = require('mongoose')

const productSchema = new mongoose.Schema({
  name: String,
  price: Number,
  quantity: Number,
  image: String
})

const cartSchema = new mongoose.Schema({
  userId: {
    type: String,
    required: true
  },
  products: [productSchema]
},
  {
    timestamp: true,
    toObject: {virtuals: true},
    toJSON: {virtuals: true}
  })

cartSchema.virtual('cartSum').get(function cartSum () {
  let sum = 0
  for (let i = 0; i < this.products.length; i++) {
    sum += this.products[i].quantity * this.products[i].price
  }
  return sum
})

const Cart = mongoose.model('Cart', cartSchema)

module.exports = Cart
```

order.js
```
'use strict'

const mongoose = require('mongoose')

const productSchema = new mongoose.Schema({
  name: String,
  price: Number,
  inventory: Number,
  image: String
})

const cartSchema = new mongoose.Schema({
  userId: String,
  cartSum: Number,
  products: [productSchema]
})

const orderSchema = new mongoose.Schema({
  orderDate: {
    type: Date,
    required: true
  },
  carts: [cartSchema]
},
  {
    timestamp: true,
    toObject: { virtuals: true },
    toJSON: { virtuals: true }
  })

const Order = mongoose.model('Order', orderSchema)

module.exports = Order
```
product.js
```
'use strict'

const mongoose = require('mongoose')

const productSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true
  },
  price: {
    type: Number,
    required: true
  },
  inventory: {
    type: Number,
    required: true
  },
  image: {
    type: String
  }
},
  {
    timestamp: true,
    toObject: { virtuals: true },
    toJSON: { virtuals: true }
  })

productSchema.virtual('inStock').get(function inStock () {
  return this.inventory !== 0
})

const Product = mongoose.model('Product', productSchema)

module.exports = Product
```

**Comment by tvcrawley** [comment]
Questions to consider: Am I being DRY? Is there a way to use code located in a different file? Am I separating my concerns?

**Comment by vanduong28** [comment]
We've been trying to reference the productSchema in product.js from cart.js but haven't been able to successfully do so without creating a productSchema in the cart.js We modeled our current schema after this example: http://stackoverflow.com/questions/22244421/how-to-create-mongoose-schema-with-array-of-object-ids

Since mongodb has a lot of repetition and the same data can be stored in many collections we assumed this would be expected in our schema.

**Comment by tvcrawley** [comment]
Remember the [`Books and their _owners`](https://git.generalassemb.ly/ga-wdi-boston/express-api/blob/solution/app/models/book.js)?

**Comment by vanduong28** [comment]
I took a look at the express-api lesson and found 

```
_owner: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  }
```

We'll look more into ref and how to apply it to our cart and order.

**Comment by tvcrawley** [comment]
Update?

**Comment by vanduong28** [comment]
We're good to go now. Thanks!!
