### ISSUE TITLE
Custom URLs

### ISSUE THREAD

**Issue by antleo1995** [ga-wdi-boston/group-project#273]
At a loss as to how to have a forward facing custom URL as we have just been using SPAs. I can easily build out a backend URL to a single resource but no idea how to route that to a front end URL from our deployed app. Any guidance towards this goal is appreciated.

**Comment by jordanallain** [comment]
are you talking about things like query params?

**Comment by antleo1995** [comment]
Not sure where it is coming from. We followed the pattern from examples and ended up with that result. Essentially the req.body is not getting survey built out but surveySchema

**Comment by tvcrawley** [comment]
Is this in response to [this issue](https://github.com/ga-wdi-boston/team-project/issues/271)?

**Comment by antleo1995** [comment]
And yes...I responded to the wrong issue. Still researching this one. There is a new response to the other issue

**Comment by lisamsmith100** [comment]
Hello,
Do you recommend using Angular JS in Project 3?
Or is there a best practice with what we have been taught so far?
Do you recommend editing the config file for  each individual survey?

**Comment by BenGitsCode** [comment]
Why are you asking about Angular? Is that in reference to the unique URLs?

**Comment by lisamsmith100** [comment]
Yes, in reference to the unique URLs.  We are trying to come up a way to create them.

**Comment by tvcrawley** [comment]
Have you searched the previous issues on this? Seems like a problem **another group** would have had.

**Comment by jordanallain** [comment]
also my first reply to this issue was never replied to

**Comment by BenGitsCode** [comment]
Truth.

**Comment by antleo1995** [comment]
I thought we discussed this over the table @jordanallain - we are trying to figure out the custom url issue. I have been trying for a while to google solutions and Angular front end routing came up over and over. I have seen views as a possible solution as well, but fear the URL isn't persistent.

**Comment by antleo1995** [comment]
And to answer another question yes, I checked previous issues and there were not any solutions offered at any point that I found.

**Comment by antleo1995** [comment]
Jordan came in with the audible of the year - apparently not a requirement - closing issue and moving on for now. I have some idea of how to revisit if need be.
