### ISSUE TITLE
Live Survey url question

### ISSUE THREAD

**Issue by octater** [ga-wdi-boston/group-project#278]
our team is still having issues wrapping our heads around the live survey url.   Our app url is https://push-it-real-good.github.io/survey-client/, so would the url to the survey be https://push-it-real-good.github.io/survey-client/<survey number> or https://push-it-real-good.github.io/survey-client/index.html?<survey number>

Maybe a quick 10 minutes could be a life saver.

**Comment by jordanallain** [comment]
is this still an issue for you guys?

**Comment by octater** [comment]
yes it is.  we have an idea but would like to chat about it first

**Comment by tvcrawley** [comment]
**Reminder:** this feature is now a reach goal. You can totally do this but it would be best to aim for this implementation after all requirements are met first.

**Comment by octater** [comment]
we need to talk about what is sent to the users to fill out the survey

**Comment by octater** [comment]
closing for now.  will open a new issue if still needed
