### ISSUE TITLE
Is "Page Preview in New Window" Functionality a violation of the SPA requirement?

### ISSUE THREAD

**Issue by danielleletarte** [ga-wdi-boston/group-project#279]
A feature our team is considering for the CMS prompt is the ability to preview a page you have created in a full size, separate window. This functionality is consistent with what you see on sites like WordPress. Selecting a "Preview" button would do a GET request and open a full size rendering of the website in a new window. This gives the user the ability to view a realistic mockup. 

All CRUD functionality will happen within our SPA (creating new pages from a template editing existing pages etc.). We will have a dashboard where users have access to any content they have created, but we are curious if rendering the full page preview in a new window is breaking any rules.

**Comment by payne-chris-r** [comment]
I love it. Can you get back to the app from the page, or do you just have to close the new window? I think either way is fine. I'm just curious.

**Comment by jrhorn424** [comment]
This is an excellent feature.

I recommend a new window/tab. `target="_blank"`

**Comment by BenGitsCode** [comment]
https://github.com/ga-wdi-boston/team-project/issues/280 Linking this issue as they're related.

**Comment by danielleletarte** [comment]
I'm thinking the new window would have to just be closed to get back to the app. Hoping we can pull it off for Friday. Thanks for the feedback!
