### ISSUE TITLE
iframe content not loading on deployed site

### ISSUE THREAD

**Issue by danielleletarte** [ga-wdi-boston/group-project#280]
We created an iframe that displays a page template when a user wants to create a new page. The code for this template is in a separate html file in a "templates" folder within our project. The iframe displays fine on local host, but we get the below error on the deployed site. 

<img width="636" alt="screen shot 2017-05-17 at 9 59 17 am" src="https://cloud.githubusercontent.com/assets/25553014/26157704/e7d8a52a-3ae7-11e7-9726-f17d0d052918.png">

Wondering if the html file that we are trying to load in the iframe needs to be named "index.html? That's my best guess based on the error..

**Comment by scottyscripts** [comment]
can you send the code of your iframe? If it's a relative path you may have to change it http://stackoverflow.com/questions/30245024/how-to-use-iframes-in-github

**Comment by danielleletarte** [comment]
It is indeed a relative path! Would love suggestions on how best to change

` <iframe id="template-1-iframe" src="./assets/templates/page-template-1.html" width="100%" height="90%" frameborder="0" scrolling="yes">
            <p>
              iframes not supported
            </p>
            </iframe>`

**Comment by BenGitsCode** [comment]
@danielleletarte try using the url that results from viewing that file raw, on your github.

**Comment by danielleletarte** [comment]
New error.

<img width="885" alt="screen shot 2017-05-17 at 11 00 45 am" src="https://cloud.githubusercontent.com/assets/25553014/26160934/83274be6-3af0-11e7-807c-5fd6d0635ed1.png">

**Comment by danielleletarte** [comment]
Any feedback on the above? I see other people have had similar issues with pages deployed on github, but struggling with a resolution.

**Comment by scottyscripts** [comment]
Apologies looking into this now!

**Comment by BenGitsCode** [comment]
I have a couple of things to try. 

1.  add `allowfullscreen="allowfullscreen"` to your iframe.
2. Wrapping your iframe in a div.

Try those first, separately, and let me know if anything changes.

**Comment by BenGitsCode** [comment]
Also please be using private mode/incognito if you're not already 😬

**Comment by danielleletarte** [comment]
No luck :( My iframes were already wrapped in divs. The current deployed version has option 1 above, but it didn't appear to resolve the issue.

https://go-away-alan.github.io/blogFace-client/

**Comment by BenGitsCode** [comment]
Hm, I have another idea worth trying but I'll come take a look at it with you.

**Comment by BenGitsCode** [comment]
Here's the issue I mentioned https://github.com/jekyll/jekyll/issues/346#issuecomment-31295437

Specifically try putting `&nbsp;` before your closing iframe tag.

**Comment by danielleletarte** [comment]
Still no luck. Please see error, below. I input the dummy text, as suggested.

https://go-away-alan.github.io/blogFace-client/

<img width="563" alt="screen shot 2017-05-17 at 12 58 22 pm" src="https://cloud.githubusercontent.com/assets/25553014/26166168/a0c17e82-3b00-11e7-9281-71ef3125496c.png">

Any other suggestions? A lot of our design depends on this functionality so I really hope we can get this working.

**Comment by danielleletarte** [comment]
Took Scott's advice and refactored my code. I put the html directly in the modal and I'm not losing the functionality I hoped to keep. Thanks!
