### ISSUE TITLE
Issues importing MongoDB collection to Heroku

### ISSUE THREAD

**Issue by rlarsonil71** [ga-wdi-boston/group-project#284]
We are looking to deploy our MongoDB database to Heroku.  

Our squad followed all instructions in the following repo:
https://git.generalassemb.ly/ga-wdi-boston/express-api-deployment-guide

Our heroku account has three config variables set (heroku>settings>config vars): 
    MONGODB_URI, SECRET_KEY, CLIENT_ORIGIN

We are trying to import our MongoDB documents into our Heroku mLab account.

We have been searching Google and closed issues on the team-project repo and found the following article on StackOverflow:
http://stackoverflow.com/questions/36082423/connecting-to-mongodb-database-on-mlab-fails-authentication

We don't see instructions on how to import our collections to Heroku and have spent more than 30 minutes on this issue.  

Please let us know if you need further information.  Thanks!

@vanduong28
@jkjellan

**Comment by rlarsonil71** [comment]
In the above StackFlow article, we found the following suggestion:

You can get the dbuser and dbpass with:

$ heroku config | grep MONGODB_URI

Grab the dbuser (example_user) and dbpass (example_pass) from the response:

MONGOLAB_URI: mongodb://example_user:example_pass@mlab.com:12345/db

**Comment by rlarsonil71** [comment]
Using the `heroku config | grep MONGODB_URI` command and the following command from https://www.mlab.com/databases/heroku_2kt07qnr:

To connect using the mongo shell:
mongo ds139791.mlab.com:39791/heroku_2kt07qnr -u <dbuser> -p <dbpassword>

we are now able to connect to our Heroku mLab but looking to figure out how to import our MongoDB to Heroku mLab.

Output from heroku config command:
```
~/wdi/projects/c2c-nozama-api (master)
$ heroku config | grep MONGODB_URI
MONGODB_URI:   mongodb://heroku_2kt07qnr:PASSWORD@ds139791.mlab.com:39791/heroku_2kt07qnr
~/wdi/projects/c2c-nozama-api (master)
$ 
```

Output from mongo command above:
```
$ mongo ds139791.mlab.com:39791/heroku_2kt07qnr -u heroku_2kt07qnr -p PASSWORD
MongoDB shell version v3.4.4
connecting to: mongodb://ds139791.mlab.com:39791/heroku_2kt07qnr
MongoDB server version: 3.2.13
WARNING: shell and server versions do not match
rs-ds139791:PRIMARY> 
```

**Comment by rlarsonil71** [comment]
Headed to lunch.  Back at 1:30pm and will review issue response.

**Comment by BenGitsCode** [comment]
It looks like you're just connecting to your servers db, not updating it with your local database. 


Have you tried this? https://blog.heroku.com/push_and_pull_databases_to_and_from_heroku

**Comment by rlarsonil71** [comment]
Thanks Ben @BenGitsCode.  I did notice that the article you posted above is from 2009 and the feature in this article has been deprecated.

**Comment by rlarsonil71** [comment]
We found the following ```mongoimport``` command in our mongodb-crud repo:
https://git.generalassemb.ly/ga-wdi-boston/mongodb-crud/blob/solution/scripts/import/books.sh

**Comment by rlarsonil71** [comment]
We have resolved this issue and are now able to import our MongoDB documents into our remote MongoDB Heroku mLab database which creates a new collection that we can now see on our mLab database dashboard.

We were  **incorrectly** running the ```mongoimport``` command in a terminal from within the mongo interface rather than from our client (master) command line.

The following 2 commands worked to import documents from our collection to our remote database on Heroku:

In a terminal:
```
$ ~/wdi/projects/OUR-CLIENT (master)
$ mongoimport -h <DB USER>.mlab.com:<DB PASSWORD> -d <DB NAME> -c <COLLECTION> -u <DB USERNAME> -p <DB PASSWORD> --file data/product_list_remote.csv --type csv --headerline -drop
2017-05-17T14:24:21.210-0400	connected to: <DB USER>.mlab.com:<DB PASSWORD>
2017-05-17T14:24:21.226-0400	dropping: <DB NAME>.<COLLECTION>
2017-05-17T14:24:21.360-0400	imported 12 documents
```

**Comment by rlarsonil71** [comment]
Closing issue.
