### ISSUE TITLE
Custom Route Implementations

### ISSUE THREAD

**Issue by lisamsmith100** [ga-wdi-boston/group-project#285]
We are trying to create a custom route to query the MongoDB/Mongoose from Express.  Since we did not cover this in class, we are looking for recommendations on best way to do this.

We have spent far more than 30 minutes on finding a solution but have not found a solution.

We have tried adding code for this in the controller but the code ultimately breaks what we have working.

Can you recommend starter code or a solution?

The problem is we are wanting to query the questions collection by survey id.  We are using Handlebars.  

Thank you and will monitor for any additional information needed to respond.

@tonyl @donpowers

**Comment by jordanallain** [comment]
what did your custom route look like?

**Comment by lisamsmith100** [comment]
Am told we're trying a couple other things... will add after we try a few things if the other ideas don't work.

Not closing just yet... will tag if/when we need advisement.  Our custom route didn't work and code is lost so we can't paste code.  I did ask if it is possible to get a recommendation?

**Comment by lisamsmith100** [comment]
We found a solution.  Closing this comment.

in routes.js:

```js
.get('/questionsbysurvey', 'questions#indexBySurvey')
```

in our controller questions controller:
```js
const indexBySurvey = (req, res, next) => {
  // console.log(req.body.survey.id)
  Question.find({ '_survey': [
        mongoose.Types.ObjectId(req.body.survey.id)
    ] })
    .then(questions => res.json({
      questions: questions.map((e) =>
        e.toJSON({ virtuals: true, user: req.user })),
    }))
    .catch(next)
}

…
module.exports = controller({
  index,
  show,
  create,
  update,
  destroy,
  indexBySurvey,
}, { before: [
  { method: setUser, only: ['index', 'show'] },
  { method: authenticate, except: ['index', 'show'] },
  { method: setModel(Question), only: ['show'] },
  { method: setModel(Question, { forUser: true }), only: ['update', 'destroy'] },
], })
}
```

in our curl request:
```sh
ID="591c84247cd6579770d5f234"
API="http://localhost:4741"
URL_PATH="/questionsbysurvey"
TOKEN="kJ4oKiWr7ra0yFJowFSg2TFidyU1ilziJXDcNoc0ZeA=--1y3UEL38wGTnUhRPI3JP9hMO6aWKyMXrhao1Z5xY/Kc="
curl "${API}${URL_PATH}" \
  --include \
  --request GET \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=${TOKEN}" \
  --data '{
    "survey": {
      "id": "'"${ID}"'"
    }
  }'

echo
```

We are going to refactor.

**Comment by lisamsmith100** [comment]
I added to slack.
