### ISSUE TITLE
question about deleting rows from 2 different tables

### ISSUE THREAD

**Issue by octater** [ga-wdi-boston/group-project#289]
When we delete a document from our surveys table, we also want to delete all documents from the response table with the same survey_id.  I have tried several different coding examples in the surveys controller with no success.

Could we have a quick 5 minute chat to  discuss the best practice and needed code for this to occur.

Thanks,

@conorjennings, @kqngo, @octater, @mattkwondo

**Comment by jordanallain** [comment]
is it necessary to have a response table? can you just store the responses in each survey or do you feel like you want to have a separate table?

**Comment by octater** [comment]
I think at this point, the separate response table

**Comment by jordanallain** [comment]
here's a link that may help

http://stackoverflow.com/questions/14348516/cascade-style-delete-in-mongoose

**Comment by octater** [comment]
Thanks Jordan.  I think I tried every flavor but that
