### ISSUE TITLE
Receiving 405 error after deploy

### ISSUE THREAD

**Issue by khan-ngo** [ga-wdi-boston/group-project#291]
Getting the following error upon deploy:

``` 
vendor.js:9678 POST https://push-it-real-good.github.io/survey-client/floating-savannah-15725.herokuapp.com/sign-up 405 (Method Not Allowed)
```
We see the following typo in config.js

Current:
    production: 'https:floating-savannah-15725.herokuapp.com'
 
will add:
    production: 'https://floating-savannah-15725.herokuapp.com'

**Comment by khan-ngo** [comment]
@conorjennings, @kqngo, @octater, @mattkwondo

**Comment by BenGitsCode** [comment]
@kqngo Let me know if you still see the problem after redeploying with the typo fix. According to heroku, this should no longer be an issue and all HTTP methods are supported.

**Comment by khan-ngo** [comment]
@BenGitsCode - thanks for your time. 

 That did the trick... the two missing slashes

11:58:12.227 vendor.js:9678 XHR finished loading: POST "https://floating-savannah-15725.herokuapp.com/sign-in".
send @ vendor.js:9678
ajax @ vendor.js:9285
signIn @ no-conflict.js:13
onSignIn @ no-conflict.js:13
dispatch @ vendor.js:5318
elemData.handle @ vendor.js:5126
