### ISSUE TITLE
Stripe Checkout configuration

### ISSUE THREAD

**Issue by rlarsonil71** [ga-wdi-boston/group-project#293]
Our squad has incorporated the Stripe payment form into our e-commerce application.

We have reviewed Stripe documentation and sample code of previous e-commerce projects on GitHub and are getting the following Linter error message in our assets/scripts/stripe/events.js file:

'StripeCheckout' is not defined.  

How do we define StripeCheckout?

Here is our code for assets/scripts/stripe/events.js:
```
const onCreateCharge = function (data) {
  console.log('in onCreateCharge. data is ', data)
  const handler = StripeCheckout.configure({
    key: 'OUR TEST KEY',
    image: 'https://stripe.com/img/documentation/checkout/marketplace.png',
    locale: 'auto',
    token: function (token) {
      const credentials = {
        stripeToken: token.id
      }
    }
  })
       .then(console.log('PAYMENT Successful'))
       .catch(console.log(error)
}

module.exports = {
  onCreateCharge
}
```

Below is a section of our index.html for stripe:
```
 <!-- stripe payment form -->
 <div id="stripePmtForm">
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"></script>
        <button type="button" id="checkoutBtn" classs="btn btn-primary">Checkout</button>
 </div>
```

We are looking to ```then``` off of the StripeCheckout.configure function and move on to other client updates.

Please let me know if you need further information.

Any assistance will be much appreciated!   Thanks!

@vanduong28
@jkjellan

**Comment by jordanallain** [comment]
how have you included Stripe in your project?

**Comment by jordanallain** [comment]
also are you using these docs?

https://stripe.com/docs/checkout/express

**Comment by rlarsonil71** [comment]
We added stripe using npm install and it shows up in our package.json file:

$ npm install stripe --save

From our package.json file:
```
  "dependencies": {
    "jquery": "^3.1.1",
    "stripe": "^4.19.0"
  },
```

We reference the src file for stripe in our index.html file (see above).

Also, previously we referenced this example in our index.html file:
```
<script
  src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="OUR TEST KEY"
  data-amount="2000"
  data-name="Demo Site"
  data-description="2 widgets"
  data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
  data-locale="auto">
</script>
```

**Comment by rlarsonil71** [comment]
We followed the Stripe documentation for Express (https://stripe.com/docs/checkout/express) and were unable to get that to work.

**Comment by jordanallain** [comment]
if you have included the package in your project you shouldn't need to use the src tag to reference the package you are using. you should be able to just require and use it in a javascript file

**Comment by BenGitsCode** [comment]
Can you show me the outputs of `heroku config` and `heroku info` ?

**Comment by laurpaik-zz** [comment]
where do you call the function that actually sends a request?

**Comment by rlarsonil71** [comment]
Output from ```heroku config```:
```
$ heroku config
=== protected-cliffs-21162 Config Vars
CLIENT_ORIGIN: https://coast-2-coast.github.io
MONGODB_URI:   mongodb://heroku_2kt07qnr:bo618efggd2pje39jrkclrvpnl@ds139791.mlab.com:39791/heroku_2kt07qnr
SECRET_KEY:    cGtM6h44nWTXTgmss6G5JTzaGDbQ+9zLEluVRV4PjPtfSIC+H9RiFZwLKMps1558TSdMzeSkdRfpBAmZEV0oG8GD
~/wdi/projects/c2c-nozama-api (development)
$ 
```

Output from ```heroku info```:
```
$ heroku info
=== protected-cliffs-21162
Addons:         mongolab:sandbox
Auto Cert Mgmt: false
Dynos:          web: 1
Git URL:        https://git.heroku.com/protected-cliffs-21162.git
Owner:          larson5.ron@gmail.com
Region:         us
Repo Size:      78 KB
Slug Size:      19 MB
Stack:          heroku-16
Web URL:        https://protected-cliffs-21162.herokuapp.com/
~/wdi/projects/c2c-nozama-api (development)
$ 
```

**Comment by BenGitsCode** [comment]
OK great your config looks good, can you answer the question above ☝️ ❓

**Comment by rlarsonil71** [comment]
We spoke to Lauren and realized that we incorrectly stripped out Stripe API code as we didn't think we needed a ```charges``` collection but we need to AJAX POST to /charges/ from our client to our API.   

We are in the process of following https://stripe.com/docs/stripe.js instructions and coding where needed on our client and API.

**Comment by rlarsonil71** [comment]
We added Stripe code to our client and API.   Stripe checkout is now working.  Closing issue.
