### ISSUE TITLE
Team Ballers 1:1 request

### ISSUE THREAD

**Issue by sjruby** [ga-wdi-boston/group-project#294]
Hoping to confirm that we've met MVP requirments, links below.

Thanks!

Deployed Site : https://ballers-inc-public.github.io/ballers-bucket-list-client/
Client Repo: https://github.com/Ballers-Inc-Public/ballers-bucket-list-client
API Repo: https://github.com/Ballers-Inc-Public/ballers-bucket-list-api

**Comment by jordanallain** [comment]
Your placeholder text in this input gets cut off, small but will improve your UI. Seems like i can update a goal that was previously completed to not started. Seems a little strange but maybe you intended that. Haven't done a complete audit but those were two things I noticed at first.

<img width="295" alt="screen shot 2017-05-18 at 3 15 25 pm" src="https://cloud.githubusercontent.com/assets/18097107/26219415/dbef1280-3bdc-11e7-80cf-d7f0deb48216.png">

**Comment by sjruby** [comment]
Awesome we fixed that first one, and the second one is a feature not a bug 👍
