### ISSUE TITLE
Text Area Issue - Disable Line Break

### ISSUE THREAD

**Issue by rrdaniels85** [ga-wdi-boston/group-project#295]
Hello!

Our team has the CMS prompt. We are currently using a text area for the blog and page form fields. We like that it visually looks better than a single line input form. However, it allows a user to make spaces between lines by hitting return. We want to disable this though because the back end of our app does not register the line break and when it comes back to the user it's all squished together as one paragraph. We don't want the user to think they can have a line break but then not be able to actually have it display that way. Is there a way to disable the ability of the user to his return within a text area? I couldn't find anything after googling online. Been spinning my wheels for awhile.

Here is what our form fields look like: 
``` 
  <!-- Create user page tab panel -->
        <div role="tabpanel" class="tab-pane" id="create-page">
          <!-- <button id="createPageButton" role="button" class="btn btn-default createPageButton" data-toggle="modal" data-target="#createPageModal">Create new Page!</button> -->
          <div id="pageBody" class="container well col-md-12 page hidden user-view">
            <!-- Page Text Area -->
            <div id='pageTextArea' class="container well col-md-9 page">
              <form id="create-page-form" role="form">
                <textarea id="create-page-title" rows="2" cols="75" name="page[title]" placeholder="Enter page title!"></textarea>
                <textarea id="create-page-body" rows="15" cols="75" name="page[body]" placeholder="Enter page body!"></textarea>
                <textarea id="create-page-footer" rows="2" cols="75" name="page[footer]" placeholder="Enter page footer!"></textarea>
              <label for="create-body-confirmation">Template</label>
              <select name="page[template]" id="create-page-template">
                <option value="defaultTemplate">Default</option>
                <option value="coolTemplate">Cool</option>
                <option value="fancyTemplate">Fancy</option>
              </select>
                <button id="createPageButton" type="submit" role="button" class="btn btn-default createPageButton">Submit your Page!</button>
                <!-- <span><p>Create page had an issue, try again!</p></span> -->
              </form>
            </div>
          </div>
        </div>
```

**Comment by jordanallain** [comment]
Hey Rachel. One thing you can try is to set an event listener on that text area that listens for the `return` key and then provide an action you want to happen instead of a new line being entered.

**Comment by rrdaniels85** [comment]
Thanks, ill try that out!

**Comment by jordanallain** [comment]
this link should prove helpful

http://stackoverflow.com/questions/18779322/disable-new-line-in-textarea-when-pressed-enter

**Comment by BenGitsCode** [comment]
Has that helped @rrdaniels85 ❓

**Comment by rrdaniels85** [comment]
That has definitely helped! Actually just got it working. Thank you guys! :)
