### ISSUE TITLE
SCSS issue with cart that needs to be adjusted. 

### ISSUE THREAD

**Issue by Ryaong792** [ga-wdi-boston/group-project#296]
SCSS issue with cart that needs to be adjusted.

**Comment by jordanallain** [comment]
can you specify what the issue is?

**Comment by Ryaong792** [comment]
<img width="1138" alt="screen shot 2017-05-18 at 3 34 38 pm" src="https://cloud.githubusercontent.com/assets/26121697/26220175/8fcae052-3bdf-11e7-87ef-56cea363145a.png">
having problems getting these to line up

**Comment by jordanallain** [comment]
lets have a look

**Comment by Ryaong792** [comment]
thank you I'll use the clear fix or flex box.

**Comment by jordanallain** [comment]
was likely a float issue as elements are colliding.
