### ISSUE TITLE
Project planning 1on1: Joe, Arlo, Nikki, Kelly (JANK)

### ISSUE THREAD

**Issue by kellye2010** [ga-wdi-boston/group-project#300]
Members: Nikki, Arlo, Joe, Kelly

ERD:
![image](https://cloud.githubusercontent.com/assets/4691419/26310856/5780c48e-3ed0-11e7-99da-e165a3876778.png)

Wireframe: https://drive.google.com/open?id=0B085YpY7Y_tmVUJtVDVpbnNJUkk

User Stories:
As a user...

Authentication
I want to sign up so that I can sign in
I want to sign in
I want to change my password
I want to be able to upload a profile photo (optional)

Bucket list items - mandatory
I want to be able to see a map of the US.
The map should indicate for each state whether I have
Completed at least 1 bucket list item there
Created some bucket list items there but not completed any
Not created any bucket lists items there
I want to be able to click on a state and view a list of my items for that state.
From there, I should be able to edit/delete/add to those items.
For each item, I want to be able to record:
Title
Location
Description
Due date
Created date
Completed date
GPS location (optional)
Category
Flag for completed/uncompleted
Flag for public/private (private by default) (optional)
Add a photo (optional)
State (automatically filled where appropriate)
I should be able to view all of my bucket list items regardless of state

Bucket list items - optional
To get ideas for new items, I would like to be able to navigate to a Discover page.  From there, I would like to be able to see/search
Suggestions from a third party API based on the state
Suggestions based on other users’ public items
I should then be able to easily add those items to my list (making edits to any field as necessary)
I want to add comments to list items for other people and allow other people to comment on my public list items
I want to earn badges for completing certain milestones
Certain number of states
Certain number of items
All states in a certain region

Items to ask about on Monday
Are we required to use a “show” method as opposed to using index with filters?

**Comment by BenGitsCode** [comment]
Head on over to classroom 4.

**Comment by joebelmonte** [comment]
Ben, we are all in Newbury - do you want to come here?

**Comment by BenGitsCode** [comment]
Be right over.

**Comment by joebelmonte** [comment]
Thanks!

**Comment by BenGitsCode** [comment]
Please close this issue and open more as they come.

**Comment by MicFin** [comment]
@joebelmonte can this be closed?
