### ISSUE TITLE
Squad Orange Overview

### ISSUE THREAD

**Issue by Maggicorp** [ga-wdi-boston/group-project#302]
Wireframe:
![img_7440](https://cloud.githubusercontent.com/assets/26171080/26311842/a6901806-3ed3-11e7-8da7-47f9e14fcdd1.JPG)

User stories:
	As a user, I can purchase as many prints as I want 
	As a user, I can buy print online
	As a user, I can sign in and see prints I bought in the past
	As a user, I can sign in and see print I put in my cart but never purchased.
	As a user, I can see all the print before I sign in.  
	As a user, I cannot add prints the shopping cart until I am successfully signed in.

**Comment by BenGitsCode** [comment]
Please close this issue and open new ones for new issues as they come 👍

**Comment by Maggicorp** [comment]
Meeting was great!
