### ISSUE TITLE
Requesting 1:1 for Team Project

### ISSUE THREAD

**Issue by mlynnes** [ga-wdi-boston/group-project#304]
We are prepared to discuss our project with a consultant. 

Project - CMS

User Stories  - 
1. As a visitor, I want to be able to see content on the app without having to sign in or sign up.
2. As a new user, I want to be able to sign up for an account.
3. As a user, I want to be able to sign in to my account.
4. As a user, I want to be able to change my password.
5. As a user, I want to be able to sign out of my account.
6. As a user, I want to be able to view, create, update, and delete blog posts.
7. As a user, I want to be able to view, create, update, and delete pages.

ERD - 
User (has many posts, has many pages) - Posts (belong to user) - Pages (belong to user)

Wireframes - currently drawn out, but now currently uploaded.

**Comment by danman01** [comment]
@mlynnes we can meet now - where are you guys working?

**Comment by mlynnes** [comment]
We are working in the 'Beacon' room currently. Thanks!

**Comment by danman01** [comment]
Ok - be there soon!

**Comment by danman01** [comment]
We met and discussed the starting planning docs for the project. Can you go ahead and close this issue? Thanks!
