### ISSUE TITLE
One on four, Survey Promt

### ISSUE THREAD

**Issue by Anddrew914** [ga-wdi-boston/group-project#305]
User can:
  -Sign Up
  -Sign In
  -Create a survey that consists of multiple true false questions
  -Stretch Goals:
    -Create Open ended and 1-5 range questions.
  -View answers to surveys.

Non Authenticated Users Can
  -Get a survey by id and take the survey.
  Stretch Goals:
    -View a list of all surveys and click to take that survey.
    -View a list of all surveys by a certain user and take their surveys.

ERD and Wireframs
https://goo.gl/photos/p8UULyL3fwY7haRx6

**Comment by danman01** [comment]
Hey, we will see you guys soon in the kitchen / lounge
