### ISSUE TITLE
grunt test sign-in

### ISSUE THREAD

**Issue by prankmode** [ga-wdi-boston/group-project#307]
Can someone help me with a grunt test?  I would like to test sign-in so that means I need to do a sign-up and create the user first.  I do that but then my sign-in give me a 404 not found instead of a most desired 200.   (I have also tried just directly creating the User in the database but that had other problems)

Here's the code:

```
describe('testing auth with user', function () {
  let server;

  beforeEach(function () {
    let app = require('../server');
    server = app.server;

    // remove any users that exist
    // User.remove(err => err && console.error(err));
    // create a user to use for these tests
    console.log('creating test account')
    const data = {
      credentials: {
        email: 'test@test.com',
        password: 'test',
        password_confirmation: 'test',
      },
    };
    request(server)
      .post('/sign-up')
      .set('Content-Type', 'application/json')
      .set('Accept', 'application/json')
      .send(data)
      .expect('Content-Type', /json/)
      .expect(201);

  });

  afterEach(function () {
    server.close();
    // remove any users that exist
    User.remove(err => err && console.error(err));
  });

  // sign in with our test user
  it("post '/sign-in' with test user account", function postUser(done) {
    const data = {
      credentials: {
        email: 'test@test.com',
        password: 'test'
      },
    };
    request(server)
      .post('/sign-in')
      .set('Content-Type', 'application/json')
      .set('Accept', 'application/json')
      .send(data)
      .expect(200, done);
  });

});
```

**Comment by danman01** [comment]
Are you testing that the server gives a valid response, or do you want to test that your `sign-in` function works as expected? Currently you are basically duplicating your `sign-in` and `sign-up` functionality in this test, which does not do much in terms of testing your client side application code. It does however test that the backend API is listening to `POST` requests at a given url and returns some sort of status.

As far as getting the 404, that means the endpoint can't be found, correct? Does signing in work for your curl requests to that same url, and are you sure the url is what you think it is?

Testing is great and encouraged, but might be better to backfill tests once you've met the core requirements just so you don't spend too much time on figuring out how and what to test. You could easily spend a few days testing each component of your app.

Here are a few pages I've found to get started, and I imagine you've also found a few good ones:
- [jasmine testing and ajax requests](https://larry-price.com/blog/2014/06/04/jasmine-a-whole-new-world-of-javascript-testing)
- [node http requests and unit testing with jasmine](https://codeutopia.net/blog/2015/01/30/how-to-unit-test-nodejs-http-requests/)

Again, make sure you are solid on core requirements for the project, and then feel free to dive into testing.

**Comment by jordanallain** [comment]
@prankmode still looking for feedback on this?

**Comment by prankmode** [comment]
seems like it's fruitless, doesn't it?
