### ISSUE TITLE
Severely Quagmired in patching survey results to mongo

### ISSUE THREAD

**Issue by d00medman** [ga-wdi-boston/group-project#308]
When storing answers from our survey, the goal is to push each given answer (which will either be true or false) to an array called results. This is easier said than done. Over the weekend, I was stonewalled by the inability to send a new array using a CURL request (though I could update the data in the mongo console itself). 

Is it possible to do this pushing of data on the back end, or does it make more sense to simply have the array be updated on the front end, then patched to the back end? The latter would require a get request, then the patch request, which adds a potential layer of problems, but I can at least conceptualize how it would be done. The former seems more simple, but I do not know how I would do it. Either way, I need to interact with AJAX to send data from the front end to the back end, and I am not clear on the syntax of this. 

How should I go about tackling this problem, and do you have any resources to recommend for either approach?

**Comment by d00medman** [comment]
This is the current code for my update method. I have yet to test it and it probably doesn't work, but I think it does a good job of illustrating what I want to do.

If there is a current user, update changes the prompt. If there is no current user, update patches the sent answer to the results array.

```js
const update = (req, res, next) => {
  // meant to allow user to update their own survey's prompt
  if (survey._owner === req.user.id) { // not sure if survey.owner is proper syntax
    delete req.body._owner
    req.survey.update(req.body.survey)
      .then(() => res.sendStatus(204))
      .catch(next)
  // this mode is set to fire when
  } else {
    req.survey.update(req.body.survey)
      .then((newAnswer) => {
        req.results.push(newAnswer)
      })
      .then(() => res.sendStatus(204))
      .catch(next)
  }
}
```

**Comment by danman01** [comment]
Looking into this now...

**Comment by d00medman** [comment]
Alright, my plan is to basically do the latter in the controller. Now, I am facing a new problem: I need update to fire differently depending on the existence of a current user. If there is a user, I need it to change the prompt of the survey. If there is no user, I need it to push the data to the results array.

The problem here is that removing I am not sure how to make the authentication before method modular. I am fairly certain I need two separate ajax calls, but I also need to change the update method in the controller so it can be fired without needing to authenticate.

**Comment by BenGitsCode** [comment]
> I need update to fire differently depending on the existence of a current user. If there is a user, I need it to change the prompt of the survey. If there is no user, I need it to push the data to the results array.

Start by pseudocoding/diagramming this out. 

As for the second part I would focus more on getting that action working _any way_ and then you can work on the better, more modular way after. It's great that you're factoring it in, but we can cross the modularity bridge when we get to it. First  get the survery updated and then we can find the preferred way of doing it.

**Comment by d00medman** [comment]
The update works for the user updating the arrays prompt. What I need to do is get it to make a patch request without authentication. The modularity is thus central to the working of my code. 

Should I abandon this approach and simply make a new method for answer handling? I have avoided this approach up until now largely because I didn't want to deal with routing. Do you think this approach would actually be less of a headache?

**Comment by danman01** [comment]
For the original question about when to update, think about the game project - how did you update the tic-tac-toe board as each move happened? Did that work well? Alternatively like you mentioned, you could wait until the "end" or a button click, then fire off the ajax request to `PATCH` the survey with the results.

As for storing / sending an array of data, that should be possible. Check out Google for sending a list or an array via an ajax request. Use console logs to ensure your data is what you think it is, and then try to persist it to your mongoDB, which can hold an array of data in a field.

Also what Ben said, go in small steps and diagram / list out the steps you want to take, knocking out the easiest first, and working up towards the refactored final piece of functionality for your update function.

**Comment by danman01** [comment]
>What I need to do is get it to make a patch request without authentication. The modularity is thus central to the working of my code.

Does ☝️ result in an error when updating without being authenticated?

**Comment by d00medman** [comment]
Yeah, it throws me a 401 error, largely because I took out the auth header. I've actually moved to a different paradigm, instead building a new method. Unfortunately, I am already tripped up by the routing. 

I am currently hitting a 401 error, but our survey paradigm is that anyone can send an answer to the server. How can I get around this 401 error without needing to pass a token through the API?

**Comment by danman01** [comment]
Are you using some sort of before filter to require authentication for the `update` action?

**Comment by d00medman** [comment]
I actually just resolved the 401 error and am now dealing with a 404 error
HTML:

```html
<form class="answer">
    <fieldset>
      <input type="string" name="survey[id]" placeholder="Select ID">
      <input type="text" name="survey[answer]" placeholder="Answer">
      <input type="submit" name="submit" value="Answer Survey">
    </fieldset>
  </form>
```

event:

```js
const onAnswer = function (event) {
  event.preventDefault()
  let data = getFormFields(event.target)
  const id = data.survey.id
  data = data.survey.answer
  api.answer(data, id)
    .then(ui.updateSuccess)
    .catch(ui.updateFailure)
}

$('.answer').on('submit', onAnswer)
```
AJAX call:

```js
const answer = (data, id) => {
  return $.ajax({
    url: config.apiOrigin + '/answers/' + id, // now its a 400 error
    method: 'PATCH',
    data
  })
}
```

Route:

```js
.patch('/answers/', 'surveys#answer')
```

controller (not yet built beyond a simple console log if you hit the server):

```js
const answer = (req, res, next) => {
  console.log('hits')
}
```

**Comment by d00medman** [comment]
Resolved the 404 error by updating the route to match the AJAX call

```js
.patch('/answers/', 'surveys#answer')
```
I am now being thrown a 500 error, which seems to be the result of my empty controller method. Building out controller and seeing what happens.

How can I get around the 500 request and have my controller output actually show:

```js
const answer = (req, res, next) => {
  console.log(req)
}
```

**Comment by danman01** [comment]
Going to give you time on it until you want to loop one of us in via Slack, as you're using this as a log.

**Comment by d00medman** [comment]
I'm stonewalled again. I keep getting 500 errors and have no idea why. I also cannot really check the output on my server because the 500 errors block my console logs from firing. Here is my updated controller.

```js
const answer = (req, res, next) => {
  console.log(req.query.survey.id)
  Survey.findById(req.query.survey.id, function(err, survey) {
    if (err) {return err}
    console.log(survey)
  })
}
``` 

I think If I can find some way to figure out what everything is represented as in the server, I will be able to figure out what is causing the server to stick

**Comment by danman01** [comment]
When was the last time your code was working? What have you added? What can you try to back out and see if the 500 goes away? It's hard to debug an error like that with no direction, unfortunately...

When you do get to a good point, do a commit, which you can amend / combine with other commits later so the commit has the meaning you want, but at least you know it's a working state of your application.

**Comment by danman01** [comment]
Any update on this 500 error?

**Comment by MicFin** [comment]
@d00medman  Was this resolved?

**Comment by d00medman** [comment]
Due to the general intractability of these problems we decided to move in a different direction in our data handling.
