### ISSUE TITLE
sign-in not working

### ISSUE THREAD

**Issue by JLisaW** [ga-wdi-boston/group-project#310]
I can't sign-in after I sign-up.  After signing up, I keep getting a 500 internal error but I can't figure out why it's happening.

This is what I get in my terminal:
POST /sign-up 201 237.931 ms - 173
POST /sign-in 500 172.475 ms - 55

**Comment by BenGitsCode** [comment]
You're getting the 500 after signing up successfully and trying to sign in? Or you're getting that when you try to sign up?

Can you post the curl request you're sending?

**Comment by JLisaW** [comment]
I'm getting the 500 after I successfully sign up. 

```
API="http://localhost:4741"
URL_PATH="/sign-in"

curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{
    "credentials": {
      "email": "'"${EMAIL}"'",
      "password": "'"${PASSWORD}"'"
    }
  }'


API="http://localhost:4741"
URL_PATH="/sign-up"

curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{
    "credentials": {
      "email": "'"${EMAIL}"'",
      "password": "'"${PASSWORD}"'",
      "password_confirmation": "'"${PASSWORD}"'"
    }
  }'
```

**Comment by BenGitsCode** [comment]
And you're passing the token you get on sign up to the sign-in request?

**Comment by JLisaW** [comment]
We don't have have tokens for sign up or sign in? 

Also, Andrew is able to sign up and sign in

**Comment by JLisaW** [comment]
To clarify, I'm the only one in my group who can't sign in. SIgn up works though, and I'm getting a five hundred error on sign in. I've even made new folders and recloned the front end and back end repos to see if it was something to do with my code. Also, the deployed site works with the same code.

**Comment by BenGitsCode** [comment]
using the same curl request?

I can come take a look.

**Comment by JLisaW** [comment]
Thanks!

**Comment by BenGitsCode** [comment]
@JLisaW Can you close this?
