### ISSUE TITLE
Git merge conflicts

### ISSUE THREAD

**Issue by pjliddy** [ga-wdi-boston/group-project#314]
Trying to rebase to merge feature branch into dev. Getting errors saying merge conflicts need to be resolved, but no idea how to do that. Do we edit them directly in .atom? Do we do it in the vimdiff mergetool? I could use a conversation.

**Comment by scottyscripts** [comment]
You can open up the files in question in your atom and edit them accordingly. This is a pretty helpful guide https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/

**Comment by Anddrew914** [comment]
Our group is having the same issues. Things are not behaving like we expect when we resolve conflicts. Any chance one of you could sit down with  both groups and tell us how this works? We've got only local repos with code looking like it should now since our merges broke both repos.
