### ISSUE TITLE
Issue Running Backend server (nodemon/npm start)

### ISSUE THREAD

**Issue by kellye2010** [ga-wdi-boston/group-project#316]
I receive an issue when attempting to run my backend server using 'nodemon' or 'npm start.'
I have already run npm install, and nodemon is installed as well. My backend was working running these commands yesterday, and the only thing that has changed since then is that I tried to rebase the origin of the branch I was working from with the most up to date changes of others working on the project. I've also tried removing the directory from my machine completely and re-cloning it again (following the steps after installation for a .env file with a secret key, and running npm install) and I still receive the error in the screenshot attached. Please help!

![screen shot 2017-05-23 at 11 47 04 am](https://cloud.githubusercontent.com/assets/4691419/26363070/e2b40178-3fad-11e7-8d9a-33614a06a2cd.png)

**Comment by jordanallain** [comment]
looks like you potentially have a typo in `events.js`

if it says `throw er` try changing `er` to `err`

**Comment by kellye2010** [comment]
Hey Jordan,
In this instance I am the only one on my team receiving this error, and I am using the most up to date repositories, as are the rest of my team members - shouldnt they receive this error as well if its a file issue?
Also, we've checked for this error and it does not appear in any files we can find (frontend or back end).

**Comment by kellye2010** [comment]
Had to run 'brew services stop mongodb', then 'brew services start mongodb', and was successfullt able to run nodemon again. 
Thanks!
