### ISSUE TITLE
Can't update individual array items

### ISSUE THREAD

**Issue by Maggicorp** [ga-wdi-boston/group-project#319]
We are trying to update individual items in the array but we can only add to them.   This is our code which adds cart items to the cart array.  We want to be able to update the cart items in the array with new values if people want to buy more, but we can't figure out how to update  individual items by id number.  Do we need to pull them and then push them again? How to we reference the item in the array, since we want to only pull the one where
 cart.idNum: req.body.buyer.cart[0].idNum

```
const update = (req, res, next) => {
  delete req.body._owner
  req.buyer.update({'$push': {cart: req.body.buyer.cart[0]}})
    .then((buyers) => res.sendStatus(201))
    .then(console.log('Cart newly updated!'))
    .catch(next)
}
```

**Comment by benjimelito** [comment]
Per our earlier conversation: Finding the index of the item that you wish to update and using the following is one possible approach: https://docs.mongodb.com/manual/reference/operator/update/set/#set-elements-in-arrays

**Comment by BenGitsCode** [comment]
Any updates on this?

**Comment by Maggicorp** [comment]
We still can't.  We just got our index request to get current user but we are going to need to get the array of cart items before we can update them.  We tried what Ben suggested but set seems to only work for individual fields rather than for items in the array.

**Comment by laurpaik-zz** [comment]
are you trying to update the items with the buyer controller, or are you trying to update the buyer altogether?

**Comment by Maggicorp** [comment]
And we are back, this time trying to do a pull and a push to update them.  We can pull but the following push doesn't seem to be happening 
```
const update = (req, res, next) => {

  delete req.body._owner;  // disallow owner reassignment.

  let owner = {_owner: req.user._id }
  Buyer.findOne(owner, { cart: { $elemMatch: {idNum: req.body.buyer.cart[0].idNum}}})
  .then(object => {
    console.log('object is', object)
    if (object.cart.length === 0) {
      req.buyer.update({'$push': {cart: req.body.buyer.cart[0]}})
        .then((buyers) => res.sendStatus(201))
        .then(console.log('Cart newly updated!'))
        .catch(next)
    }
    else {
      const idNum = object.cart[0].idNum
      req.buyer.update(
        {'$pull': {cart: { idNum: req.body.buyer.cart[0].idNum}}}
      )
      .then(req.buyer.update({'$push': {cart: req.body.buyer.cart[0]}}))
      .then((buyers) => res.sendStatus(201))
      .catch(next)
      }
    }
  )}

```

**Comment by scottyscripts** [comment]
Is `console.log('object is', object)` logging to the console? So `Buyer.findOne(owner, { cart: { $elemMatch: {idNum: req.body.buyer.cart[0].idNum}}})` is checking to see if `cart` contains an object with `idNum` being equal to the `idNum` from params, correct? What are you trying to check in the `findOne` query?

**Comment by Maggicorp** [comment]
It is pulling the right object.  Basically what happens after we update an object is it disappears.  Then if we update it again it comes back.  So it is finding and removing the right thing, it just isn't pushing a new one afterwards.

**Comment by scottyscripts** [comment]
Ahhhh I see. Do you want to use `req.buyer` to update? if you are finding the correct object (which is named `object` in your code) and have access to it could you update with that in your `.then`?

**Comment by Maggicorp** [comment]
We got rid of .then and now it seems to be able to update it properly.  More testing is in order.

**Comment by Maggicorp** [comment]
This is what we currently have
```
const update = (req, res, next) => {

  delete req.body._owner;  // disallow owner reassignment.

  let owner = {_owner: req.user._id }
  Buyer.findOne(owner, { cart: { $elemMatch: {idNum: req.body.buyer.cart[0].idNum}}})
  .then(object => {
    console.log('object is', object)
    if (object.cart.length === 0) {
      req.buyer.update({'$push': {cart: req.body.buyer.cart[0]}})
      .then(response => console.log('after push it says', response))
        .then((buyers) => res.sendStatus(201))
        .then(console.log('Cart newly updated!'))
        .catch(next)
    }
    else {
      const idNum = object.cart[0].idNum
      req.buyer.update(
        {'$pull': {cart: { idNum: req.body.buyer.cart[0].idNum}}}
      )
      .then(response => console.log('after pull it says', response))
      req.buyer.update({'$push': {cart: req.body.buyer.cart[0]}})
      .then(response => console.log('after push it says', response))
      .then(res.sendStatus(201))
      .catch(next)
      }
    }
  )}
```
