### ISSUE TITLE
AJAX call throws 500 error on get request

### ISSUE THREAD

**Issue by d00medman** [ga-wdi-boston/group-project#322]
I am currently having almost [this](https://github.com/ga-wdi-boston/team-project/issues/288) exact problem. I am able to successfully curl with the following:

```curl
API="http://localhost:4741"
ID="5924a70b3adcb5d3c01ea7ba"
URL_PATH="/questions"
curl "${API}${URL_PATH}" \
  --include \
  --request GET \
  --header "Content-Type: application/json" \
  --data '{
    "question": {
      "_survey": "'"${ID}"'"
    }
  }'

echo
```

my AJAX call:

```js
const surveyQuestions = function (id) {
  console.log(id)
  return $.ajax({
    url: config.apiOrigin + '/questions',
    method: 'GET',
    data: {
      'question': {
        '_survey': id
      }
    }
  })
}
```

my original controller

```js
  let searchUserQuestions = { _survey: req.body.question._survey }
  Question.find(searchUserQuestions)
    .then(question => res.json({
      question: question.map((e) =>
        e.toJSON({ virtuals: true})), // no
    }))
    .catch(err => next(err))
```

I actually updated my controller along the lines used to resolve the last issue, but it continues to throw me a 500 error

```js
const index = (req, res, next) => {
  Question.find({ '_survey': [
        mongoose.Types.ObjectId(req.query.question._survey)
    ] })
    .then(questions => res.json({
      questions: questions.map((e) =>
        e.toJSON({ virtuals: true })),
    }))
    .catch(next)
```

This is the URL, it is still returning with the query params, which I though my above changes to the controller would fix. Why would my changes to the code not produce the same result it did in the issue? FWIW, they were using a custom route, while we are simply overwriting the index method of our question controller. Could that be a source of the problem?

`http://localhost:4741/questions?question%5B_survey%5D=5924a70b3adcb5d3c01ea7ba`

**Comment by scottyscripts** [comment]
Why is the URL at the bottom different from the one in your requests? Is `req.query` defined in your controller the way you are currently making those requests? Where are you getting req.query? Can you confirm that you are entering that index method?

**Comment by d00medman** [comment]
req.query.question._survey, when I make my ajax request, becomes equivalent to the _survey property of question, which will allow me to return all questions that are have this _survey id. This is how we are linking our survey data type to our question data type.

I am unsure of why the url is different, but I know for a fact that it is sending query params rather than a standard url. I am also unsure of whether or not req.query is properly defined in my controller. I am also almost certain that I am entering an index request. Maybe I am approaching this wrong. Do you think it would be in my best interest to simply build out a custom route for this problem, rather than face the errors of trying to overwrite the inbuilt index method?

**Comment by d00medman** [comment]
Alright, it turns out the problem was that we were trying to read from the ata field of the ajax call in this line 
```js
let searchUserQuestions = { _survey: req.body.question._survey }
```

The fix here was that, in order to function on the client side, `body` needed to be switched to `query` to allow the search to read from the url and thus get the appropriate data

```js
let searchUserQuestions = { _survey: req.query.question._survey }
```
