### ISSUE TITLE
Did I just delete my work?

### ISSUE THREAD

**Issue by Anddrew914** [ga-wdi-boston/group-project#323]
I was getting ready to push work to the master branch and, to be safe, tried to first fetch and check how the files were going to be different. 

This is a log of what happened 
$ git pull origin master
From github.com:TheBestGASquad/FrontEnd
 * branch            master     -> FETCH_HEAD
Current branch HEAD is up to date.
~/WDI/projects/Group-Project/FrontEnd 
$ git status
HEAD detached from FETCH_HEAD
nothing to commit, working tree clean 
$ git checkout FETCH_HEAD
Warning: you are leaving 1 commit behind, not connected to
any of your branches:
  7138003 Streamlines UX,
If you want to keep it by creating a new branch, this may be a good time
to do so with:
 git branch <new-branch-name> 7138003
HEAD is now at 8735809... Merge pull request #8 from TheBestGASquad/d00medman-patch-1
~/WDI/projects/Group-Project/FrontEnd 
$ git checkout HEAD
~/WDI/projects/Group-Project/FrontEnd 
$ git checkout master
Previous HEAD position was 8735809... Merge pull request #8 from TheBestGASquad/d00medman-patch-1
Switched to branch 'master'

And then I proceeded to try to look for my commits. Are they gone or is there something I can do to get them back?

**Comment by benjimelito** [comment]
Have you tried running `git log` to see a history of your commit messages and related hashes?

**Comment by Anddrew914** [comment]
Yeah, it's not showing the commit I had made.

**Comment by Anddrew914** [comment]
Using git reflog and finding the sha that referenced right before I made the mistake allowed me to checkout to that spot and make a new attached head. Thanks Ben!
