### ISSUE TITLE
[express/mongoose] - How do I get the update action to send back the JSON for the updated resource

### ISSUE THREAD

**Issue by aprilsourz** [ga-wdi-boston/group-project#325]
I want the update action in in our Items controller to send back the JSON for the item that was updated.

I am able to make to update an an item successfully  and get back a 204 when my the controller code looks like :

```js
const update = (req, res, next) => {
  delete req.body._owner;  // disallow owner reassignment.
  req.item.update(req.body.item)
    .then(() => res.sendStatus(204))
    .catch(next);
};
```

This is my attempt to get back a JSON response from the update action.

```js
const update = (req, res, next) => {
  delete req.body._owner // disallow owner reassignment.
  let item = Object.assign(req.body.item)
  console.log(item)
  req.item.update(req.body.item)
    .then((item) =>
      res.status(200)
        .json({
        item: item.toJSON({ virtuals: true, user: req.user }),
      }))

    .catch(next);
};
```

I get a 500 and the error in my chrome console is:

 {"error":{"message":"item.toJSON is not a function","error":{}}}"

I am a little stumped. I'll keep googling for an answer and looking at the mongoose documentation.
Any advice on where to look for the answer? I'm calling toJSON on something that doesn't have that method. How can i access the updated item from the database in the response?

**Comment by benjimelito** [comment]
When you simply return `item` in your `.then` statement, is it not in the correct format?

**Comment by aprilsourz** [comment]
I found a work around. I will test that out too. Thank you.
