### ISSUE TITLE
Handlebars helpers is GA templates

### ISSUE THREAD

**Issue by pjliddy** [ga-wdi-boston/group-project#327]
We're trying to put a conditional helper in our Handlebars template (if owner_id === user_id) but the helper doesn't seem to be called even though it's registered in JS.

Is there a required way of using Handlebars helpers (i.e., external files in the templates/helpers directory)? If so, how do they need to be set up (plain JS, module.export, etc) and as what type of file (.js or .handlebars)?

**Comment by scottyscripts** [comment]
can you post that template's code? Where is the current location of that template? How are you trying to use the helper?

**Comment by pjliddy** [comment]
Made it as a module with exports. good to go.
