### ISSUE TITLE
500 for controller action with stripe

### ISSUE THREAD

**Issue by Maggicorp** [ga-wdi-boston/group-project#328]
```GET http://localhost:4741/charge?{%22id%22:%22tok_1AN65VE4UNzYgNSt97FWCuZx%22,%…2:%223@1.1%22,%22livemode%22:false,%22type%22:%22card%22,%22used%22:false} 404 (Not Found)
```
this is the issue we are getting.  We defined a charge method in the buyer controller with a route that looks like this. We moved the more specific route to be read first. 
```
.post('/charge', 'buyers#pay')
.resources('buyers')
```
Here is our ajax call
```
const makeCharge = function (token) {
  console.log('at make charge')
  return $.ajax({
    url: config.apiOrigin + '/charge',
    method: 'GET',
    headers: {
      'Authorization': 'Token token=' + store.user.token
    },
    data: JSON.stringify(token)
  })
}
```
and here is the controller method.  It's not hitting the controller method so we can't deal with any  issues in that yet. 
```
const pay = (req, res, next)  => {
  let amount = 500
  console.log('at pay req is ', req)
  stripe.customers.create({
    email: req.body.email,
    card: req.body.id
  })
  .then(customer =>
    stripe.charges.create({
      amount,
      description: "Sample Charge",
      currency: "usd",
      customer: customer.id
    }))
  .then(charge => res.send(charge))
  .catch(err => {
    console.log("Error:", err)
    res.status(500).send({error: "Purchase Failed"})
  })
}
```

**Comment by benjimelito** [comment]
I noticed that you're defining the route as a `POST` : `.post('/charge', 'buyers#pay')`, but when you're actually making the ajax request you're setting the method to `GET`

**Comment by benjimelito** [comment]
Scott mentioned that this is what the documentation said to do, but I would be surprised if this wasn't causing some sort of issue

**Comment by Maggicorp** [comment]
Changed it to POST, which helped.  New errors.  Will update with new error message.

**Comment by Maggicorp** [comment]
The problem is that the request isn't passing the right data.  req.body.email and req.body.id are both returning undefined.  It seems that something is being lost when we changed the fetch to an ajax request.

**Comment by benjimelito** [comment]
Would you mind console logging what `req` looks like in the controller and
posting that?

**Comment by Maggicorp** [comment]
I got those properties, new issue is that it can't make the request with them.  It is returning a 500 error and not hitting the .catch or .then that comes afterwards.  So something is happening here
```
stripe.customers.create({
    email: req.body.email,
    card: req.body.id
  })
```

**Comment by Maggicorp** [comment]
It gets req.body.email and req.body.id to b tok_1AN8dZE4UNzYgNSt3sXXxULe and 3@1.1, which is correct.

**Comment by Maggicorp** [comment]
Okay, I kept it in the folder and it correctly makes the request now.  I added these headers.  
const express = require("express");
const stripe = require("stripe")(keySecret);
const bodyParser = require("body-parser");

**Comment by Maggicorp** [comment]
Sadly, this does not work in the deployed version even thought it works locally. 
:(

**Comment by benjimelito** [comment]
What sort of errors are you getting in the deployed version?

**Comment by Maggicorp** [comment]
I am having a really hard time figuring out why stripe isn't working deployed and what it is actually creating.   Can anyone do a one on one with me about it?  I have also just paste some of my questions but I could really use some help looking at it overall

**Comment by Maggicorp** [comment]
I had to save my secret password in the heroku configuration for it to worked deployed.
