### ISSUE TITLE
Requirements Questions: File Bucket

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/group-project#335]
How are we required to display and edit files? Can this simply be displayed in a new tab in the browser or do they have to be displayable/editable in the app itself?

What file types are we required to support? Text files, images, etc?

What does "edit" mean for this project? That it has been reuploaded by the owner? Or do we need to, for example, show a text file so they can edit it in the app and save it?

**Comment by tvcrawley** [comment]
Gather/develop your planning docs and we can chat about prompt specific questions then.
