### ISSUE TITLE
Request for Team 1:1 - Git Rich or Die Pryin'

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/group-project#336]
User stores (trello): https://trello.com/invite/b/bRyHNpqY/aa52c70bf27a157cdd46b874f77402e2/wdi-3-git-rich-or-die-pryin

WireFrames/ERD:
https://drive.google.com/drive/folders/0BxtpRPyddhwRQzlkNHVSSFBLZ00?usp=sharing

**Comment by tvcrawley** [comment]
There are no user stories as of yet.
Please make them so a 1:1 can occur. 

Also, it'd be great if your Trello board could be made public so someone doesn't have to join the team in order to see the content.

**Comment by artpylon** [comment]
The trello board should be public already, but try this link
https://trello.com/invite/b/bRyHNpqY/aa52c70bf27a157cdd46b874f77402e2/wdi-3-git-rich-or-die-pryin

The trello board contains all our user stories

**Comment by tvcrawley** [comment]
This (https://trello.com/invite/accept-board) is the link you're sending which invites a user to your board. This (https://trello.com/b/bRyHNpqY/wdi-3-git-rich-or-die-pryin) should be the public link you send to others.

Also, **there are no user stories** specified anywhere on this board.

**Comment by artpylon** [comment]
The backlog contains all our user stories, but I also just copied and pasted them into the front end repos readme:
https://github.com/the-best-org-lab/drip-drop-frontend/blob/master/README.md

This is the organization for our team containing the two repos:
https://github.com/the-best-org-lab
