### ISSUE TITLE
1 on 1

### ISSUE THREAD

**Issue by slammyde7113** [ga-wdi-boston/group-project#337]
Here's what we whiteboarded out:
![file_000 1](https://user-images.githubusercontent.com/27901872/27554840-d03fa052-5a7d-11e7-9c14-0fd52541bba3.jpeg)
![file_000](https://user-images.githubusercontent.com/27901872/27554844-d2f88796-5a7d-11e7-813c-c5d81d60e75b.jpeg)

**Comment by tvcrawley** [comment]
Missing the user stories

**Comment by slammyde7113** [comment]
-When I sign up, I should be able to sign in
-When I sign in, I should be able to sign up, sign out, change password, and go to my cart. I should also see a product menu, which I can add to my cart.
-When I go to my cart, I should be about to delete items and pay for my cart total
-When I pay for my cart total, I should see an empty cart and a confirmation that my purchase was successful

**Comment by tvcrawley** [comment]
@slammyde7113 We've met and discussed the planning docs for the project. Can you close this issue? Thanks!
