### ISSUE TITLE
request for 1-on-1 for Schrödinger software

### ISSUE THREAD

**Issue by EricLScace** [ga-wdi-boston/group-project#338]
User stories: https://github.com/squad-three/squad-three-back-end/wiki/User-Stories

Wireframes: https://github.com/squad-three/squad-three-back-end/wiki/Wireframes

ERD: https://github.com/squad-three/squad-three-back-end/wiki/ERD

**Comment by tvcrawley** [comment]
@EricLScace We've met and discussed the planning docs for the project. Can you close this issue? Thanks!
