### ISSUE TITLE
Help understanding JS error resulting from how we are requiring a file

### ISSUE THREAD

**Issue by lisawilliams** [ga-wdi-boston/group-project#341]
We are trying to require a file from a jQuery plugin we are using. However, it's generating an error, the file is being required using a JS syntax we are not familiar with. Can you help us understand what is happening here?

```
const $ = require('jquery')
require('datatables.net-bs')

require('./dataTables.editor.js')(window, $)

```

**Comment by lisawilliams** [comment]
This references issue # 28 from our repo: https://github.com/squad-three/squad-three-front-end/issues/28

**Comment by BenGitsCode** [comment]
Why are you requiring jQuery, and what documentation are you following to require this plugin?

**Comment by scottyscripts** [comment]
@lisawilliams What exact functionality are you guys trying to get from the editor package? There is probably a way to accomplish what you want without dealing with this. I am only slightly concerned because datatables has npm packages for most plugins besides this one for some reason...

**Comment by scottyscripts** [comment]
editor appears to be a paid thing after the 15 day free trial? Are you guys planning on paying for this?

**Comment by constaac** [comment]
Yea, probably going to get the money back. It prompts an editor window and makes AJAX calls. If the installation went well, It would be incredibly useful. I understand how to do it otherwise. The idea was installing the plugin would take a hell of a lot less time - which has been a mistake.

**Comment by constaac** [comment]
Is it possible to have a 1on1 for 10 minutes to see if anything can be done, before I scrap it all. I'm losing my mind over this, its been about 12 total hours of trying to figure this out. If I have to scrap it, I don't have much time to get going on an alternative

**Comment by constaac** [comment]
https://datatables.net/forums/discussion/43238/struggling-with-editor-installation#latest

https://editor.datatables.net/manual/getting-started

Using the npm package for datatables, and local files for the editor

**Comment by payne-chris-r** [comment]
You're not being methodical. Is this required to getting your project across the line? Maybe I don't understand the point of the plugin, but it sounds like something you should be doing after you have it working already--not before.

**Comment by tvcrawley** [comment]
@lisawilliams Has this been addressed? If so, please update the issue with the solution and close.

**Comment by lisawilliams** [comment]
Closed as we abandoned this approach for a simpler one.
