### ISSUE TITLE
Sign-up in the express-api allows password and confirmation password mismatch

### ISSUE THREAD

**Issue by MarcyNash** [ga-wdi-boston/group-project#342]
Issue #276 has a fix for this bug. Since the bug is in the API and has not yet been fixed, should I just copy the code which fixes this bug? Or, should I expect that the consultant testers won't fail our project because sign-up allows password and confirmation password mismatch?

**Comment by BenGitsCode** [comment]
I would not recommend knowingly pushing a bug into your production application.

**Comment by MarcyNash** [comment]
Thanks Ben. Will copy the code from issue #276
