### ISSUE TITLE
Delete/Update Requests with Mongoose

### ISSUE THREAD

**Issue by slammyde7113** [ga-wdi-boston/group-project#343]
We're having trouble with the delete and update requests for our tables. Here some of our code to give context.
Get Request Result for Products Table:
```
{
    "product": {
        "_id": "5951976290fe850d650ae4c1",
        "name": "test",
        "price": 0,
        "description": "test",
        "_owner": "595153ad6f18427ef38c416b",
        "__v": 0,
        "id": "5951976290fe850d650ae4c1",
        "editable": false
    }
}
```
Delete Request Curl Script:
```
curl -X DELETE \
  http://localhost:4741/products/5951976290fe850d650ae4c1 \
  -H 'authorization: Token token=B3vDp2Ay310wxNjPx5EMecMSFmqnUnmnD98yeaLnsjs=--FXJqlTfi/3Xoj15rjF8wZhbMTHN2tkNZaN5ej+WAG4U=' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
```
Delete Request Result:
```
{
    "error": {
        "message": "404 Not Found",
        "error": {
            "name": "HttpError",
            "status": 404,
            "message": "404 Not Found"
        }
    }
}
```
I've written delete requests before and I haven't encountered this issue before. I'm using the same delete controller as the examples model uses (with modifications of course). Normally I'd console.log my request and see what I'm sending but its not being executed in the controller. Here's an example:
```
const destroy = (req, res, next) => {
  console.log(req)
  req.product.remove()
    .then(() => res.sendStatus(204))
    .catch(next)
}
```
Any help would be greatly appreciated.

**Comment by slammyde7113** [comment]
This works in the mongo shell thought:
```
db.products.remove({ "_id": ObjectId("5951976290fe850d650ae4c1")})
WriteResult({ "nRemoved" : 1 })
```

**Comment by BenGitsCode** [comment]
What else have you tried so far? Have you looked through this issue queue for similar problems?

**Comment by slammyde7113** [comment]
I've tried a different delete request format:
```
const destroy = (req, res, next) => {
  Product.remove({ _id: req }, function (err) {
  if (!err) {
    res.sendStatus(400)
  } else {
    res.sendStatus(404)
  }
  })
```
but that didn't work either. Have you seen this issue before on here? Links would make me super happy

**Comment by slammyde7113** [comment]
Also I just skimmed through the closed issues and couldn't find anything relevant

**Comment by jordanallain** [comment]
`Product.remove({ _id: req }, function (err) {`

is the _id: supposed to be pointing to req?

**Comment by slammyde7113** [comment]
good point, I think I fudged up by mistake, lemme try without the req

**Comment by jordanallain** [comment]
well you need something there, does the req object have an _id in it?

**Comment by slammyde7113** [comment]
I dont think the req has anything in it because its a delete request. Am I sending this wrong?
```
curl -X DELETE \
  http://localhost:4741/products/5951976290fe850d650ae4c1 \
  -H 'authorization: Token token=B3vDp2Ay310wxNjPx5EMecMSFmqnUnmnD98yeaLnsjs=--FXJqlTfi/3Xoj15rjF8wZhbMTHN2tkNZaN5ej+WAG4U=' \
  -H 'cache-control: no-cache' \
```
I thought since the products/:id would return a single product it wouldnt need to have parameters for the remove function

**Comment by jordanallain** [comment]
if req has nothing in it why are you using it?

**Comment by slammyde7113** [comment]
If any of you guys have some free time, I would really appreciate sitting down with one of you to fix this. I can't really do anything else on the back end until I can get this done. I'm gonna keep trying to find solutions on my own in the meantime.

**Comment by payne-chris-r** [comment]
What does your code look like now?
Have you referenced the examples controller?
```js
const destroy = (req, res, next) => {
  req.example.remove()
    .then(() => res.sendStatus(204))
    .catch(next)
}
```

**Comment by payne-chris-r** [comment]
Also, please close your other issue. #337

**Comment by tvcrawley** [comment]
@slammyde7113 Please update this issue with the solution and close!
