### ISSUE TITLE
AWS upload / download questions

### ISSUE THREAD

**Issue by MarcyNash** [ga-wdi-boston/group-project#345]
1. Uploading a file to s3 - we have the code from Mike and we're thinking it will be a cut and paste operation? 
2. Googling around I saw that aws has a command line interface. If files are being uploaded and downloaded from the frontend, is using the frontend an option? 
3. Am also looking for an npm option to run on the backend for downloading.
4. Security - if we have access to our files via the s3 url, does this make things secure?
5. I did see an issue about aws permissions for download (GET)

We're in Tremont conference room until 4

**Comment by BenGitsCode** [comment]
Please break these down into questions, I'm not sure what _specifically_ you're asking for in this issue. 

What have you tried, concerning upload/download to AWS?

**Comment by MarcyNash** [comment]
We're in the process of testing the upload now. Will open another issue for the download.

For uploading files, I would like some help with the aws secrets. For local testing, do we each use our own aws secrets / buckets. The upload code should get it from our .env file. 

From the public server (Heroku) do we pick one of our aws accounts?

**Comment by BenGitsCode** [comment]
It's up to you, but I'd recommend choosing one AWS bucket to use for your project. You may want redeploy separately _after_  presenting so that you each have your own working copy deployed.

How you pick is up to you, but for simplicity I would just pick one account and stick to it throughout development.

**Comment by MarcyNash** [comment]
Thanks Ben!
