### ISSUE TITLE
Trouble Configuring Datatable Editor Window

### ISSUE THREAD

**Issue by constaac** [ga-wdi-boston/group-project#348]
Datatables and editor has successfully been integrated into our project. The editor extension for datatables is designed to pop up a modal type window to prompt the user for an edit. The edit functionality exists, but the window isn't displaying properly.

You can see an example of this on our deployed page:
https://squad-three.github.io/squad-three-front-end/

I have an open thread on the datatables forum, but havn't found the solution to the issue.
The thread shows the developer's suggestions for me, but most integrations of datatables/editor use script/link tags rather than NPM, making the implementation much more complicated than need be. I realize it's a bit ridiculous, but I'm so deep in the rabbit hole that I just want to get it working. 

Here is the thread on the forum: 
https://datatables.net/forums/discussion/comment/113392#Comment_113392

The data tables file structure looks like this:
http://imgur.com/a/oP0Vi

The editor extension is a licensed plugin, so its the only aspect of datatables that isn't offered as an NPM package. I am using the npm packages for datatables itself, DT buttons, and DT select (two extensions required to use the editor). Installing and requiring those extensions works as expected. 

This is what my requires look like as it stands:
```
require('datatables.net-bs')
require('datatables.net-buttons')
require('datatables.net-select')

require('./dataTables.editor.js')
// require('./editor.bootstrap.js')
```

The commented require is my attempt at the dev's most recent suggestion in the thread. All the styling is being handled by a link tag in the HTML:
```
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.dataTables.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/select/1.2.2/css/select.dataTables.min.css"/>
```

Any suggestions?

**Comment by constaac** [comment]
Repo if necessary - https://github.com/squad-three/squad-three-front-end

**Comment by MicFin** [comment]
I would HIGHLY recommend thinking about what @payne-chris-r said in https://github.com/ga-wdi-boston/team-project/issues/341
> Is this required to getting your project across the line?

If you need to integrate a JS and CSS library that is not an NPM package then take a look at this previous issue and my commits showing how to integrate one.
1.  https://github.com/ga-wdi-boston/capstone-project/issues/573
2.  https://git.generalassemb.ly/ga-wdi-boston/browser-template/commits/add-cssmap 
(note how I load the css.  Not as `<link>` tags in the `<head>` of the document.  I rename them as `.scss` files and import them to `index.scss`)

But I can not stress enough that if it is not a requirement for your project then you may be wasting time on a feature that will hurt you more than help you.

PS great job posting a well explained issue on the datatables message board!

**Comment by tvcrawley** [comment]
@constaac Update?

**Comment by constaac** [comment]
I didn't get the editor window working completely, but it functioned. I was able to require the datatables file like so:

```require('./dataTables.editor.js')```

And then creating a new editor instantiation:

``` const editor = new $.fn.dataTable.Editor(...)```

Then finaly:

```
$('#main-table').DataTable(blInitParams.mainTableParameters(editor))
```

Where the function as the Datatable argument returns:

```
ajax: {
      url: config.apiOrigin + '/bucket',
      headers: {'Authorization': 'Token token=' + store.user.authNToken}
    },
    select: 'single',
    dom: 'Bfrtip',
    buttons: [
      {extend: 'create', editor: editor},
      {extend: 'edit', editor: editor},
      {extend: 'remove', editor: editor}
    ],
    columns: [
      {data: 'description'},
      {data: 'category'},
      {data: 'location'},
      {data: 'duration'},
      {data: 'cost', render: $.fn.dataTable.render.number(',', '.', 0, '$')},
      {data: 'status'}
    ]
  }
```
