### ISSUE TITLE
iam trying to add image to my front end 

### ISSUE THREAD

**Issue by isharma-sharma** [ga-wdi-boston/group-project#351]
`````
<div class="container">
  <div class="row">
    <div class="col-sm-4" >
      <div class="panel panel-primary" >
        <div class="panel-heading">BLACK FRIDAY DEAL</div>
        <div class="panel-body"><img src="./assets/scripts/styles/images/image1.png" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer">Buy 50 mobiles and get a gift card</div>
        <button id="test" type="submit" class="btn btn-info btn-block" class="adtocart">add to cart</button>
      </div>
`````
the image is not showing up i have checked my path also
then i tried by uploading the images at imgur.com and then added the url at <img> tag still not working
```
geting below error at my console
````
localhost/:135 GET https://placehold.it/all-free-download.com/free-photos/download/tulip-flowers-highdefinition-picture-01_166861.html 404 (Not Found)

**Comment by BenGitsCode** [comment]
Is your client repo updated on github?

**Comment by BenGitsCode** [comment]
It looks like you're trying to link to a local asset, that is not github.

**Comment by isharma-sharma** [comment]
i make it work my imgur

**Comment by BenGitsCode** [comment]
You have it working, with an imgur link?

**Comment by isharma-sharma** [comment]
i was making adding the link that is referencing to the imgur website not to the that image

**Comment by isharma-sharma** [comment]
yes
