### ISSUE TITLE
Schrödinger Software deployed app

### ISSUE THREAD

**Issue by EricLScace** [ga-wdi-boston/group-project#356]
[public website](https://squad-three.github.io/squad-three-front-end/)

[back end repo](https://github.com/squad-three/squad-three-back-end)

[front end repo](https://github.com/squad-three/squad-three-front-end)

**Comment by jordanallain** [comment]
thanks @EricLScace ! mind closing this issue?

**Comment by EricLScace** [comment]
Closed, along with the 1-on-1 request issue. Thanks.
