### ISSUE TITLE
Requirements question: file bucket

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/group-project#358]
The concept for our app is that this file bucket is to be used by a marketing team that is reviewing and working on creative to be used on their site, magazine, etc. 

The project requirements seem to indicate that only the owner of a file may edit or delete it. However, given the use cases for our app, any logged in user should be able change the tags on a file (new, pending, complete). 

Would it be acceptable to allow this? 

If it is not acceptable, then follow up question. May we expose the owner in the api response so this could be used to filter down the edit/delete options to only the files that the current user owns?

**Comment by jordanallain** [comment]
changing a tag wouldn't really be editing the file though, correct? that sounds more like meta data associated with the file.

**Comment by artpylon** [comment]
I previously received approval from another instructor that editing the tags was sufficient for the file edit requirement.
 
Also, I can't think of how editing the file itself would make sense for the file bucket app. The app stores a file on s3, an image or a text file. To edit the file itself would be uploading a new file.

**Comment by payne-chris-r** [comment]
I hear what Jordan is saying. I think it's ok for anyone to modify the tags. A user should be able to  change the title of the file, but I agree that changing the file seems like you probably just want to delete that file and upload a new one.

To answer your original question, yes, that is acceptable to change the tags, but the owner should be the only one that can change the title, and delete the file. 

Make sure you take a look at `editable` in examples controller it should help you with your problem

**Comment by artpylon** [comment]
Alright, to confirm:

1. All logged in users should be able to edit tags 
2. File owners should be able to edit file names
3. File owners should be able to delete files 

Will look at editable in examples controller next.

**Comment by payne-chris-r** [comment]
Yeah, that sounds cool.

**Comment by artpylon** [comment]
So, follow-up question. I can certainly make title editable only on the backend, but I'd also need to know whether to display this option to the user in the frontend. 

For this, I guess I could return the owner ID of the current user on sign in and in the index response so that I could then only show title edit where there is a match. Is that acceptable?
