### ISSUE TITLE
GET request authentication issue

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/group-project#360]
So I required authentication in order to make an index GET request but after I sign-in I get a 401 unauthorized error.  The index GET request DOES work with a curl script but not in the browser.

Code:
controller -
```{ method: authenticate },``` 
server response -
```GET /files 401 28.888 ms - 27
GET /files 200 64.113 ms - 317```

**Comment by jordanallain** [comment]
can you post some relevant code?

**Comment by ghost** [comment]
Issue fixed, added user token information to the index request
