### ISSUE TITLE
connection closed

### ISSUE THREAD

**Issue by ryanwk** [ga-wdi-boston/group-project#369]
We're getting this error when we try to sign up or in on the front end. Our console logs inform us that our request makes it to the UI but the request is not successful. We've seen connection refused when the server isn't running, however, our servers are running. We haven't seen this connection closed error before and we have been googling to no avail. 

error:
jquery.js:9566 POST https://localhost:4741/sign-in net::ERR_CONNECTION_CLOSED

tried:
curl requests to see if we could sign up and in from the back end. Those worked so the problem seems to be stemming from the front end. 

```js
const onSignUp = (event) => {
  event.preventDefault()
  console.log(event.target)
  console.log('testing')
  const data = getFormFields(event.target)
  api.signUp(data)
    .then(ui.signUpSuccess)
    .catch(ui.signUpFailure)
}
```
```js
const signUp = (data) => {
  return $.ajax({
    url: config.apiOrigin + '/sign-up',
    method: 'POST',
    data
  })
}
```

**Comment by benjimelito** [comment]
Are you sure that you have your Mongo database running? I would check this first

**Comment by ryanwk** [comment]
Yes, the server's running via nodemon

**Comment by benjimelito** [comment]
Sorry, not the node server - your Mongo server. You can check to see if it's running by using `brew services list` in the command line. If you don't see `mongodb` listed when running this command, you can start it by running `brew services start mongodb`

**Comment by ryanwk** [comment]
```js
development: 'http://localhost:4741'
```
http was https 

Thank you guys!
