### ISSUE TITLE
Minor merge conflict

### ISSUE THREAD

**Issue by jbculbertson** [ga-wdi-boston/group-project#371]
Hi there,

Somehow, I have a merge conflict on my local branch that others on my team don't.  Its related to the initial commits that we made on our master branch (accidentally) to change the README.    Over the weekend, I was able to work through this because we knew the conflict was unimportant.  Could someone please help us work through resolving this?

**Comment by payne-chris-r** [comment]
Is this good?

**Comment by jbculbertson** [comment]
My conflict still exists (dev branch is xx commits ahead of master, 2 behind), but we can't get it to surface again.  We told Ben we would grab him when we get the issue to show again

**Comment by payne-chris-r** [comment]
dev branch ahead of master isn't really a merge conflict. It's probably just a fact? It's not something worth worrying about unless it shouldn't be!

**Comment by jbculbertson** [comment]
Dev branch is ahead of master, but at the same times its two commits behind

**Comment by scottyscripts** [comment]
Any updates on this issue @jbculbertson ?

**Comment by jbculbertson** [comment]
Chris walked us through resolving this minor conflict
