### ISSUE TITLE
Team 4:1 request

### ISSUE THREAD

**Issue by jingrid** [ga-wdi-boston/group-project#372]
Hello!
We're assigned the CMS project.

Our ERD: https://wireframe.cc/Umsvqb

Wireframes: http://i.imgur.com/eV00Y1t.jpg

http://i.imgur.com/LWOh3XC.jpg

**Comment by cpearce31** [comment]
All set to close after meeting with @benjimelito?

**Comment by jingrid** [comment]
Yup!
