### ISSUE TITLE
500 internal server error when loading index

### ISSUE THREAD

**Issue by jingrid** [ga-wdi-boston/group-project#375]
Trying to load Blogs on my localhost, it was working, but now it just gives 
{
"error": {
"message": "Blog.find is not a function",
"error": {}
}
}

The Blog.find is in my controller for Blogs, which I haven't changed.

**Comment by cpearce31** [comment]
Can we see the controller code?

**Comment by jingrid** [comment]
Fixed it!

We were trying to create a nested schema, and having curly braces in module.exports was throwing it off.
