### ISSUE TITLE
cannot load css 

### ISSUE THREAD

**Issue by jingrid** [ga-wdi-boston/group-project#379]
I keep getting the following error
![screen shot 2017-08-08 at 10 34 13 am](https://user-images.githubusercontent.com/28785731/29077084-3baea482-7c25-11e7-8555-a4d645c43fda.png)

html is as follows:
```
    <head>
      <title></title>
      <script src="vendor.bundle.js" type="text/javascript" charset="utf-8" defer></script>
      <script src="bundle.js" type="text/javascript" charset="utf-8" defer></script>
      <script src='https://cdn.tinymce.com/4/tinymce.min.js'></script>
        <script>
        tinymce.init({
          selector: '.text-editor'
        });
        </script>
    </head>
```

**Comment by scottyscripts** [comment]
Why are you using inline JavaScript in HTML?! eww. Also this comment is in browser-template.   

```
<!-- Do not add `script` tags-->
```
Is there an npm package for the plugin you are trying to use?

**Comment by scottyscripts** [comment]
Also how are you using this plugin??

**Comment by jingrid** [comment]
The page loads correctly on Parth's computer, and all he did was npm install. 

I've npm installed as well.

We're using it to allow users to add blog posts and pages.

**Comment by jingrid** [comment]
fixed via cloning repo again, npm installing again
