### ISSUE TITLE
lost my jquery library?

### ISSUE THREAD

**Issue by 3point14guy** [ga-wdi-boston/group-project#380]
I am getting a linter error: '$' is not defined. (no-undef)

I am getting this error in all my events and api files.

Google search suggests that something happened to my library or I am not requiring in the correct order.  I feel it is the first possibility as I didn't make any changes to the script tags in the template.

package.json has jquery listed as a dependency.

**Comment by jordanallain** [comment]
did you npm install?

**Comment by 3point14guy** [comment]
I did.

**Comment by scottyscripts** [comment]
If you guys added a script tag to index.html for datatables, this could be causing the issue. I highly suggest linking to datatables using the npm package and not by linking to it in index.html. https://datatables.net/download/npm

**Comment by 3point14guy** [comment]
Ok.  That script is currently commented out on the branch I am working on.

**Comment by cpearce31** [comment]
Did commenting it out make the error go away?

**Comment by 3point14guy** [comment]
That wasn't clear. It has been commented out the entire time.

**Comment by payne-chris-r** [comment]
In what file are you getting that error, and do you have script tags in your index.html?

**Comment by 3point14guy** [comment]
This is a linter error in my events.js and api.js files.

**Comment by 3point14guy** [comment]
The issue is because the files I am working on were no in my scripts folder.  Moved files and error went away!

Thanks guys!!
