### ISSUE TITLE
Sending an array in a patch request using get-form-fields?

### ISSUE THREAD

**Issue by bradleyden** [ga-wdi-boston/group-project#384]
We have our back end built to expect a nested array for a field in our "orders" collection, and I'm not really sure how to send this in a PATCH request. I'm currently using get-form-fields to send the data to the patch request, but when I use jQuery to set the value of a field to the desired array and then check the data that is being sent in the request, the array is formatted like so:

orders[products]:59887fbc58fa7b1e22d29176,5

when it should look more like this (with product id and quantity as the values):

[ [ 59887fbc58fa7b1e22d29176, 5 ] ]

and this is causing an internal server error.

Is there any way to send more complex datatypes like arrays via get-form-fields, or is there another way I should be approaching this?

Thanks!

**Comment by cpearce31** [comment]
Can you post the code where you use `getFormFields`? I think I've run into this issue before and I believe it had to do with calling it on the wrong thing.

**Comment by bradleyden** [comment]
```javascript
const onUpdateOrder = function (event) {
  event.preventDefault()
  const data = getFormFields(this)
  api.updateOrder(data)
    .then(ui.updateOrderSuccess)
    .catch(ui.updateOrderFailure)
}
```
The get form fields is being called on the correct form, and the values that are just strings or text are being passed like I expect, but the field that is being passed an array seems to remove the array formatting.

**Comment by jordanallain** [comment]
not totally understanding the workflow here. can you help me wrap my head around it?

you have a text field where the user enters an id number of a product they want and you are trying to push that id into a nested array to send to the API?

**Comment by bradleyden** [comment]
It's actually a little simpler than that, I have a variable called shoppingCart that is a nested array of all items in the user's cart organized like this: [[item1_id, item1_quantity], [item2_id, item2_quantity], etc.]

What I'm trying to do is pass this variable into an AJAX request via a form field using jQuery so that when this form is submitted, this array will patch over the empty array in the order. Does that make sense?

**Comment by cpearce31** [comment]
How are you attaching that array to the form field?

**Comment by bradleyden** [comment]
I can't post the exact code at the moment because we are in Outcomes, but I'm using jQuery like this:

$('#updateCart-products').val(shoppingCart)

Where shoppingCart is the name of the variable holding the array.

**Comment by bradleyden** [comment]
I'm going to close this issue because I've moved on from trying to use get-form-fields. I'm still having trouble with getting a complex nested data type to be properly interpreted by mongoose, but that's a different issue.
