### ISSUE TITLE
Question on Stripe

### ISSUE THREAD

**Issue by mak1323** [ga-wdi-boston/group-project#385]
I have a question about Stripe. How much are we supposed to integrate this? Are we supposed to have our order post to the api and from there post to stripe (which is what we have been trying to do)? Or are we over thinking this and should simpy have the front end send two api requests, one to the api with a record of the user, the amount on the transaction, and a record of the order number then send a second request to the stripe api, so it processes the card there and the tokens and such don't have to touch our api?

The second part seems a bit simpler, and since right now we aren't having customers be required t save credit cards, it seems easier so we dont have to save the token.

Not sure what route to take.

**Comment by payne-chris-r** [comment]
Kind of both? Mostly the first one. You get the 'payment token' or whatever it is from stripe on the front end, and then use it to process the payment on the backend. 
Use Stripe method of inputting a cc and getting back an authorization token/payment token (I forget what it's called). Make the POST request to the backend for order.
Once you have the order, (**optionally make sure price and quantity are 👍 **), process payment, save order to db, return response, if any of it fails, barf. If payment 👍  and save order 👎 , return payment?

**Comment by payne-chris-r** [comment]
You definitely DON'T want to save CCs to the db. That's the benefit of stripe.

**Comment by mak1323** [comment]
For future peoples:

You must the process card(stripe api)
Retrieve token(stripe api)
Process payment(stripe api)
If that is all successful, then make a record of the transaction on your api. (your api)
DO NOT SEND TOKENS TO YOUR API
