### ISSUE TITLE
Question about Back End Readme.md

### ISSUE THREAD

**Issue by kailinc** [ga-wdi-boston/group-project#386]
The situation is that I am writing the readme.md for the back end. One of the action is uploading a file. I am not sure if it is possible to upload a file with a curl script. Should I not include curl scripts for that part or should I explain how uploads are created in the API?

**Comment by benjimelito** [comment]
I think you're fine not including a `curl` script to upload a file for the back end readme. Although `curl` scripts are really nice for anyone testing or using your app, I don't believe they are required in the project guidelines.

**Comment by kailinc** [comment]
thanks for clearing it up @benjimelito
