### ISSUE TITLE
cannot update Blog, getting 500 Internal Server Error

### ISSUE THREAD

**Issue by jingrid** [ga-wdi-boston/group-project#395]
Hello

We are trying to update a Blog, which only requires the blog ID, user auth token, and blog Title to be updated. This PATCH works in the back end with the cURL scripts. But doesn't work in front end. 

Here's what we have for events:
```
const onUpdateBlog = function (event) {
  console.log('onUpdateBlog in events working')
  event.preventDefault()
  const data = getFormFields(this)
  api.updateBlog(data)
    .then(ui.updateBlogSuccess)
    .catch(ui.updateBlogFailure)
}
```

API:

```
const updateBlog = function (data) {
  console.log('this is data ', data)
  console.log('this is data.blogId: ', data.blogId)
  return $.ajax({
    url: app.host + '/blogs/' + data.blogId,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}

```

Here's the data object that's passed when calling to api:
`{submit: "Update Blog", blogId: "599b5dd32522b577e7b92bbf", title: "asdf"}`

Not sure why we keep getting the 500 error.

**Comment by jordanallain** [comment]
Should the data object you are sending have an outermost key of blog that points to the object that holds the ID ?

```js
data:  {
    blog: 
    {
      blogId: "599b5dd32522b577e7b92bbf",
      title: "asdf"
    }
  }
```

something like that?

**Comment by jordanallain** [comment]
actually, if you said that the curl script worked that probably isn't it. does the URL look right that the request is going to?

**Comment by Fcarrion001** [comment]
You were right Jordan the problem was with how we named it in the html. 
We named it "blogId" and "blogTitle" when it should have been blog[id] and blog[title]
As a result the data was being sent in a form that was unacceptable to the API
update is now successful after these changes
