### ISSUE TITLE
Unable to connect to server once deployed

### ISSUE THREAD

**Issue by mak1323** [ga-wdi-boston/group-project#396]
Setting up my deployment for front end and bckend. On testing, running into error
```
vendor.js:9723 XHR failed loading: POST "https://gentle-woodland-80342.herokuapp.com//sign-up".
```
When trying to post, not sure why this is .

My config file is double checked and looks like this:
```js
'use strict'

const config = {
  apiOrigins: {

    production: 'https://gentle-woodland-80342.herokuapp.com',
    development: 'http://localhost:4741'

  }
}

module.exports = config
```

my api request looks like this
```js
const signUp = (data) => {
  return $.ajax({
    url: config.apiOrigin + '/sign-up',
    method: 'POST',
    data
  })
}
```

The error is clearly showing a double // between the path and the url, but I don't know where to look for this after the config and the api request come back clean.

This is a cloned copy of team project.

**Comment by jordanallain** [comment]
the double slash is not preferable but likely isn't the issue. if you are using the same API but a different client does your API know about this new client and that it should accept requests from it?

**Comment by mak1323** [comment]
Both the Api and the front end are clones with the deployed backend set to the new app on heroku. I'm not sure where to look for that info. Everything on the front end is looking hunky dory and set to the new backend and new deployment.

**Comment by jordanallain** [comment]
you need to set the CLIENT_ORIGIN to your personal github.io page if you haven't already.

**Comment by jordanallain** [comment]
you can do this from the command line with heroku config set or on the heroku dashboard on their website.

**Comment by mak1323** [comment]
Had run the command and set it to 'https://mak1323.github.io'. I just changed it to 'https://mak1323.github.io/fencer-front-end' and the new error is:
```
XMLHttpRequest cannot load https://gentle-woodland-80342.herokuapp.com/sign-up. The 'Access-Control-Allow-Origin' header has a value 'https://mak1323.github.io/fencer-front-end' that is not equal to the supplied origin. Origin 'https://mak1323.github.io' is therefore not allowed access.
```

**Comment by mak1323** [comment]
Set the origin to the original, 'https://mak1323.github.io' but made sure there wasn't a / at the end. New error is 400. SO woo new error, running tests seeing where this goes.

**Comment by mak1323** [comment]
Ok error solved. 

Problem was when I did set the config I set it with a / at the end of it so debugging front code wouldn't find it. Fixing it in heroku dashboard was best method.
