### ISSUE TITLE
Team 1 on 3

### ISSUE THREAD

**Issue by ChrisAK** [ga-wdi-boston/group-project#400]
Our team is all set to have a meeting to go over planning stuff as well as talk about a few things we're not sure on.

**Comment by danman01** [comment]
@ChrisAK Are you available at 10 or 10:30 to have a meeting?

**Comment by danman01** [comment]
@ChrisAK or actually, @ieatyanyans already met with you all?

**Comment by iEatYanYans** [comment]
@danman01 Yes

**Comment by danman01** [comment]
Closing this as it's on wrong queue and has been addressed
