### ISSUE TITLE
Issue with creating/uploading files

### ISSUE THREAD

**Issue by ChrisAK** [ga-wdi-boston/group-project#401]
So we can upload things from the console and it will create a `file` document in the api. What we seem to be struggling with is getting data from the front end to the back

This is our ajax request:
```const upload = function (data) {
  console.log(app.user.id)
  return $.ajax({
    method: 'POST',
    url: app.host + '/files',
    headers: {
      Authorization: 'Token token=' + app.user.token
    },
    data: data,
    contentType: false,
    processData: false
  })
}
```

This is the route in our controller where we seem to be getting stopped:
```const create = (req, res, next) => {
  console.log('got here 1')
  const fileUploaded = {
    path: req.file.path,
    body: req.body.file.title,
    user: req.user._id
  }

  console.log('fileUploaded')

  awsUpload(fileUploaded)
  .then((s3Response) => {
    return File.create({
      url: s3Response.Location,
      title: s3Response.Key,
      tags: req.body.file.tags.split(''),
      _user: req.user._id
    })
  })
  .then((fileUploaded) => res.status(201).json({fileUploaded}))
  .catch(next)
}
```

We get to the `console.log('got here 1')` every time but we never hit `console.log('fileUploaded')` so I can only assume we run into an error when the object `fileUploaded` is made/populated/created.

**Comment by danman01** [comment]
Closing this as it's also [here](https://git.generalassemb.ly/ga-wdi-boston/team-project/issues/289)
