### ISSUE TITLE
Read of created survey in custom URL problems

### ISSUE THREAD

**Issue by LaurisaNeuwirth** [ga-wdi-boston/group-project#64]
(1) survey not displaying in the url at all
(2) some trouble linking the url in the webpage

**Comment by jrhorn424** [comment]
When/if you resolve this, please let us know what the problem was!

**Comment by LaurisaNeuwirth** [comment]
@jrhorn424 Yes definitely. Working on making that render a live survey instead of just the JSON in that unique url. I will add in the code and errors to make this a more robust issue as well.

**Comment by jrhorn424** [comment]
Any resolution here?
