### ISSUE TITLE
Using .then() with AJAX

### ISSUE THREAD

**Issue by rchezrutt88** [ga-wdi-boston/group-project#72]
Hey guys! We're wondering about using the promise interface with our ajax requests. For instance, could we do something like this?:
```
let signIn = function(userData) {
.ajax({
POST userData
}
}
let signUp = function {
.ajax({
POST
}).then(signIn(responseData)
}
```

**Comment by jrhorn424** [comment]
That's an interesting question. It looks like recent version of jQuery may support `.then()` as a method call. It's important to know that you **may not** be dealing with native Promises, so you'll have to rely on jQuery documentation to figure this out. http://www.htmlgoodies.com/beyond/javascript/making-promises-with-jquery-deferred.html

http://api.jquery.com/deferred.then/

**Comment by gaand** [comment]
Or you could use the xhr promise lesson as a template and use native promises for sure.

**Comment by J-Weeks** [comment]
@rchezrutt88 http://stackoverflow.com/questions/5436327/jquery-deferreds-and-promises-then-vs-done
