### ISSUE TITLE
Need modelling help

### ISSUE THREAD

**Issue by jpfriedman18** [ga-wdi-boston/group-project#73]
Trying to model purchases for eCommerce app. We need a purchase to include an array of objects, each containing an item ID (referencing an item) and quantity, however we are worried that what we have created so far is too complicated. What we have so far:

```
const purchaseSchema = new mongoose.Schema({
  items: [{
    _itemId:{
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Item',
      required: true
    },
    quantity: Number
  }],
  _userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  completed: Boolean
}, {
  timestamps: true,
  toJSON: { virtuals: true },
});
```

**Comment by jpfriedman18** [comment]
Also we are unsure of how to access the price attributes of each object in order to calculate the total price virtual for a purchase

**Comment by J-Weeks** [comment]
Do you have an ERD / any other models?

**Comment by jpfriedman18** [comment]
We have an Item model and a User model. A User will have many purchases, which are made up of many items.

**Comment by J-Weeks** [comment]
Sounds like you're thinking in relational database terms

**Comment by jpfriedman18** [comment]
Now we have:
```
'use strict';

const mongoose = require('mongoose');

const purchaseSchema = new mongoose.Schema({
  items: [],
  _userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  completed: {
    type: Boolean,
    required: true,
    default: false
},
}, {
  timestamps: true,
});


const Purchase = mongoose.model('Purchase', purchaseSchema);

module.exports = Purchase;
```

**Comment by J-Weeks** [comment]
what are your other models now?

**Comment by gaand** [comment]
Do items have attributes?

See http://mongoosejs.com/docs/schematypes.html and http://mongoosejs.com/docs/subdocs.html to start.

**Comment by J-Weeks** [comment]
@jpfriedman18 was this issue resolved?  If so please close, else please ask more followups.
