### ISSUE TITLE
nodemon: module error

### ISSUE THREAD

**Issue by MFBrewster** [ga-wdi-boston/group-project#74]
When I try running nodemon, I get the following error:

```
~/wdi/projects/the-fridge-backend (file-mcr)$ nodemon
[nodemon] 1.9.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `./bin/express server`

/Users/michaelbrewster/wdi/projects/the-fridge-backend/node_modules/mongodb/lib/server.js:242
        process.nextTick(function() { throw err; })
                                      ^
Error: connect ECONNREFUSED 127.0.0.1:27017
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
[nodemon] app crashed - waiting for file changes before starting...
```

I was having a similar issue running nodemon during one of the class lessons. Matt was helping me with it, and I don't know if we ever got to a solution. 

At first, this error said that I didn't have express installed, so I ran ```npm install --save express``` and ```npm install```, and after that I got the error I quoted above. Any help would be much appreciated.

**Comment by gaand** [comment]
It's likely that mongodb isn't running (mongodb's default port is `27017`).

You can check with `ps ax | grep mongo`.

I believe the `launchctl` commands listed near the end of the output from running `brew info mongodb` will start mongodb when your laptop starts.

**Comment by MFBrewster** [comment]
Running ```mongod``` fixes it. I will run the ```launchct1``` commands and keep you posted about results, but for now I will close the issue
