### ISSUE TITLE
Saving CSS and HTML to back-end?

### ISSUE THREAD

**Issue by rchezrutt88** [ga-wdi-boston/group-project#75]
We're confused about the best approach for saving and retrieving HTML and CSS to our database. 
My general idea for how a CMS should work is that, for a sign-in user, when they visit a page they own, they should see a nested window view that displays their page and on the side a toolbar with options for changing styling. 
Ok, fine. So the question is, should we be saving specific content the user creates (user updates the title, a patch request is made to the title field of their blog model) or should we be saving all the raw HTML (styling and content) within the window view to one HTML field of their blog model? 
Does this make sense?

**Comment by gaand** [comment]
Probably a little of both, although I would look into a markdown processor so you can avoid raw html/css (although some css might be okay).

You need to restrict some of what your users store or your site is likely to become a source of virii.

**Comment by rchezrutt88** [comment]
@kpie89 @dumplingpuff

**Comment by J-Weeks** [comment]
@rchezrutt88 Did @gaand reslove the issue? If so please give the solution and close. If not please feel free to ask a follow up.

**Comment by rchezrutt88** [comment]
We are going to use a "WYSIWYG" web editor--specifically, https://www.tinymce.com/--and save the generated html with inline styling to a string field on our back end. No CSS.
