### ISSUE TITLE
4 on 1 for planning

### ISSUE THREAD

**Issue by jdamiron** [ga-wdi-boston/group-project#77]
@jrhorn424 @MattB-GA-Boston @gaand @J-Weeks 

Attached are wireframes and user stories to plan out our project. We are looking to have a 4 on 1 to speak on guidance and get some questions answered.

[wireframesandplanning.zip](https://github.com/ga-wdi-boston/group-project/files/171388/wireframesandplanning.zip)

**Comment by MattB-GA-Boston** [comment]
I'm free to meet with you guys, if you want.

**Comment by MattB-GA-Boston** [comment]
Wireframes look good - it seems like you've been thinking about templates as you've been drawing.

Do you guys have an ERD yet?

**Comment by jdamiron** [comment]
@MattB-GA-Boston yes, want me to upload it?

**Comment by MattB-GA-Boston** [comment]
Yes, please.

**Comment by jdamiron** [comment]
![img_0900](https://cloud.githubusercontent.com/assets/16493127/13746874/dcfd3210-e9cb-11e5-8b77-cd5d42d1d757.JPG)

**Comment by jrhorn424** [comment]
How are these entities related? @jdamiron

**Comment by jdamiron** [comment]
Pages has many entries, they associate to each other using their ID's. We are trying to think of the entities using a non relational database.

**Comment by jrhorn424** [comment]
Just because the database is non-relational, doesn't mean the data isn't related. I can meet with your group in a few minutes.

**Comment by jrhorn424** [comment]
Spoke with the group about using Mongoose reference types, as well as safe HTML input, and display using a Handlebars filter. @jdamiron Please close if this addresses your original request.
