### ISSUE TITLE
(GIT) staged and committed wrong file. (not pushed to Github)

### ISSUE THREAD

**Issue by erdesi90562** [ga-wdi-boston/group-project#78]
I accidentally staged and committed a file to my local branch. I have NOT pushed to git hub.
What is the proper workflow to remove the extra file?

* I have googled and found answers but am unsure if they are in my best interest.

**Comment by gaand** [comment]
If the only contains the one file, it's probably easiest to revert that commit.

**Comment by gaand** [comment]
Commit. And if it's the last commit.

**Comment by J-Weeks** [comment]
@erdesi90562 was this resolved? If so please close.

**Comment by erdesi90562** [comment]
I used a different method. Yes it was resolved.
