### ISSUE TITLE
1on1 for file uploading questions

### ISSUE THREAD

**Issue by apalmer0** [ga-wdi-boston/group-project#79]
Had some questions I was hoping I could talk through quickly with someone... right now I'm trying to figure out the steps between clicking the upload button and having my file appear in AWS and in my app. It seems to be working right now but I'm not sure how. Specifically - 
- why does my AJAX call take forever to complete (looking like 5 min, currently)?
- why does a image model get created even though the AJAX call fails?
- what data is coming through my formData?

**Comment by J-Weeks** [comment]
@apalmer0 sorry I thought this was a leftover from this weekend that didn't get closed.  Do you still need assistance with this. I see that you wanted quick help and was working on this about 4 hours ago, any progress/ remaining questions?

**Comment by apalmer0** [comment]
All good. I've pushed a little beyond where I was but I'd still like to sit down and review my code and plans for the remaining deliverables, esp before I leave tomorrow afternoon. Today or tomorrow morning are both fine, whatever works. 

Thanks!

**Comment by J-Weeks** [comment]
Cool, lets meet tomorrow morning and I'll go over what you have and what else needs to be done. This should give you more time to make progress.  If you'd rather meet today though I'm fine with that as well.

**Comment by apalmer0** [comment]
sounds good. in the meantime, could i ask a question about aws credentials? i'm trying to delete an object from my bucket but i keep getting an 'access denied' message... when was access ever granted? how do i authorize myself?

**Comment by jrhorn424** [comment]
@apalmer0 Mind filing a separate issue for that? Thanks. Feel free to leave this open until you have the meeting you requested.

**Comment by apalmer0** [comment]
sure

**Comment by apalmer0** [comment]
@J-Weeks lets meet tomorrow at 930?

**Comment by J-Weeks** [comment]
@apalmer0 sounds good

**Comment by J-Weeks** [comment]
Met, clarified instructions for file bucket project.  Discussed strategies in how to visually represent file system.  Discussed structure of how to store tags.  Talked pros/cons of aws client/api side uploads. 

Action items: tabled reach features for later. Will meet again upon return from trip.
