### ISSUE TITLE
Localhost 3000 hangs after post, posts won't display until after nodemon reset

### ISSUE THREAD

**Issue by jenweber** [ga-wdi-boston/group-project#81]
We have a create from the front end that works (posts to mongo and S3). However after the post, if you refresh localhost:3000/files it just hangs with the refresh arrow spinning. If I shut down nodemon and restart it, my posted content is available and visiting localhost3000 doesn't hang anymore.

As far as I can tell, our promises all have a res,rej. And we've tried adding .then(() => mongoose.connection.close()); in different places (above and below catch, in the controller, in the awsS3Upload function, in both) but that didn't seem to make a difference.

Controller:
```
const create = (req, res, next) => {
  let file = Object.assign(req.body.file, {
    title: req.body.file.title,
    description: req.body.file.description,
    filename: req.file.originalname,
  });
  console.log(file);
  awsS3Upload(file.filename, file.title, file.description)
    .then(file => res.json({ file }))
    .catch(err => next(err))
    .then(() => mongoose.connection.close());
};
```

awsS3Upload calls this:
```
let awsS3Upload = function(filename, title, description){
  console.log(filename, title, description);
  return new Promise((resolve, reject) =>
    fs.readFile(filename, (err, data) =>
      err ? reject(err) : resolve(data)
    )
  ).then((data) => {
    let file = { data };
    console.log(fileType(data));
    file.type = fileType(data) || {
      ext: 'bin',
      mime: 'application/octet-stream',
    };
    return file;
  }).then(awsUpload)
  .then((awsS3Response) => {
    console.log("awsS3Response called");
    console.log(awsS3Response);
    return File.create({ location: awsS3Response.Location, title: title, description: description });
  }).then((file) => { // model instance created and saved
    console.log('Success!');
    console.log(file);
  }).then(() => mongoose.connection.close())
  .catch(console.error);
};
```

**Comment by J-Weeks** [comment]
does it log ``` console.log('Success!');
    console.log(file);
```

**Comment by J-Weeks** [comment]
Sorry my computer is autoclosing

**Comment by jenweber** [comment]
yes it logs success

**Comment by jenweber** [comment]
Here is the full console log following a post:
{ title: 'file', description: 'file', filename: 'dumplings.jpg' }
dumplings.jpg file file
{ ext: 'jpg', mime: 'image/jpeg' }
awsS3Response called
{ ETag: '"2c9e4e50ad385314d1713e8847e76f97"',
  Location: 'https://jwexpress.s3.amazonaws.com/2016-03-14/ed37317d0b18914cfdafe353144ecef0.jpg',
  key: '2016-03-14/ed37317d0b18914cfdafe353144ecef0.jpg' }
Success!
{ _id: 56e6ecc848c723ce73fe6f5f,
  description: 'file',
  title: 'file',
  location: 'https://jwexpress.s3.amazonaws.com/2016-03-14/ed37317d0b18914cfdafe353144ecef0.jpg',
  createdAt: Mon Mar 14 2016 12:54:32 GMT-0400 (EDT),
  updatedAt: Mon Mar 14 2016 12:54:32 GMT-0400 (EDT),
  __v: 0 }
POST /files/ 200 430.060 ms - 2

**Comment by J-Weeks** [comment]
So logging but not closing the connection. hmmm, let me read your code closely and look into this.

**Comment by MattB-GA-Boston** [comment]
@jenweber Can you share the server logs?

**Comment by jenweber** [comment]
@MattB-GA-Boston  is that something different than I shared above?

**Comment by MattB-GA-Boston** [comment]
@jenweber Sorry, missed the `POST` at the end. I'll assign myself to this.

**Comment by MFBrewster** [comment]
The problem was that after our awsS3upload script, we were running ```.then(() => mongoose.connection.close());```, which is code we took from the demo repo. This was severing our connection to nodemon, so no other back end processes were hitting the server after that line of code ran. After we deleted that line, the server stopped "hanging" (server was not actually hanging, but the connection was being severed).

**Comment by MattB-GA-Boston** [comment]
@jenweber Since this issue is resolved, can you please close it at your nearest opportunity?

**Comment by jrhorn424** [comment]
@jenweber When you return, please close. Thanks!

**Comment by jrhorn424** [comment]
@gaand Do you think this is something that can or should be addressed in the multer presentation?
