### ISSUE TITLE
3 to 1 discussion on model-controller relationship for the Survey app

### ISSUE THREAD

**Issue by Knguyen21** [ga-wdi-boston/group-project#82]
Hello team,

Currently our backend survey app has 3 models (users, surveys, responses). Inside the surveys model, we have attributes for title, questions and answers, however we're debating whether to add another model called **questions** that would be associated the survey. Consequently, we would have to remove the  surveys models attributes--questions and answers--and move to the new questions model.

We would like to have some feedback whether if proceeding with this change is good for our project.

**Comment by J-Weeks** [comment]
So in this new model it would be Users, Surveys, Responses, Questions?

What attributes would each of these have and how would you associate them?

**Comment by Knguyen21** [comment]
Yes, this new organization would be Users, Surveys, responses, and Questions.

A user creator has many surveys. Surveys have many responses and questions. the public survey takers have many responses. 

**Users would have the following attributes:**
email: string
password: string

**Surveys would have the following atttributes: **
Title: string
Description: string
Connected w/ user by user_id

**Responses would have the following attributes: **
answer: string
connected w/ survey by survey_id  OR question_id??????

**Questions would have the following attribute: **
Question: string
Answers: string, number
connected w/ survey by survey_id

**Comment by J-Weeks** [comment]
This sounds like more or a design decision for you and your group to make @jrhorn424 or @MattB-GA-Boston please feel free to give an opinion here as well.  What are the benefits of the new structure you are proposing, what are the disadvantages?  How does mongodb store data and what is it good for?

**Comment by Knguyen21** [comment]
@erdesi90562 @msyao-github

**Comment by jrhorn424** [comment]
You're thinking in terms of relational databases. Think in "documents" instead. Do questions need to exist outside of a survey? Are responses any different than surveys themselves?

Think in terms of an analog solution... if you had to do this with paper, how would you accomplish the task?

**Comment by jrhorn424** [comment]
I'd like to speak with @gaand briefly before scheduling a meeting with your group.

**Comment by Knguyen21** [comment]
Thanks Jeff!
