### ISSUE TITLE
A sign-in with the wrong password is still successful - template issue?

### ISSUE THREAD

**Issue by jenweber** [ga-wdi-boston/group-project#83]
We confirmed that this same problem is present in other group's work, so I think this is an issue with the template.

If a user signs in (after signing up), they can enter anything they want for the password and the login will be successful. If the username does not exist in the system, the sign in fails as expected.

**Comment by MattB-GA-Boston** [comment]
Bug in the User model's `comparePassword` method, but it's already been fixed in the `express-template` repo.

Here's the correct code:
```
userSchema.methods.comparePassword = function (password) {
  let _this = this;

  return new Promise((resolve, reject) =>
    bcrypt.compare(password, _this.passwordDigest, (err, data) =>
        err ? reject(err) : data ? resolve(data) : reject(new Error('Not Authorized')))
    ).then(() => _this);
};
```
