### ISSUE TITLE
Sign In/Up functionality not working

### ISSUE THREAD

**Issue by ajordon** [ga-wdi-boston/group-project#84]
Our group has sign in and sign up working correctly. Plus I have rebased my code to the most recent branch. Im still encountering errors when I sign in and sign up.

```
"{"error":{"message":"insertDocument :: caused by :: 11000 E11000 duplicate key error index: express-template.users.$username_1 dup key: { : null }","error":{"code":11000,"index":0,"errmsg":"insertDocument :: caused by :: 11000 E11000 duplicate key error index: express-template.users.$username_1 dup key: { : null }","op":{"updatedAt":"2016-03-14T19:13:18.000Z","createdAt":"2016-03-14T19:13:18.000Z","passwordDigest":"$2a$10$OdGhRbZ4GgzRvu6Mx/75.euUXo47ZcoupaqqVVvldEj7FbrAkVDjq","email":"c@c.com","token":"eRqto/jNxxkuim/hauZBGw==","_id":"56e70d4e24c955122ed4aa1c","__v":0}}}}"
```

**Comment by J-Weeks** [comment]
have your tried to look this up first? http://stackoverflow.com/questions/24430220/e11000-duplicate-key-error-index-in-mongodb-mongoose

**Comment by ajordon** [comment]
While using the curl scripts I created a user with a value of null and was not able to create anyone new. I removed my users from my db and now it works.
