### ISSUE TITLE
Running out of storage

### ISSUE THREAD

**Issue by jdamiron** [ga-wdi-boston/group-project#87]
My computer is running out of memory and doesn't allow me to run mongod, it specifies it needs atleast 3500 MB. If I can't run mongod, I can't connect to the database, disallowing almost all features based on signing in.

**Comment by jrhorn424** [comment]
Storage, or memory?

**Comment by MattB-GA-Boston** [comment]
Shrunk the Windows partition; I'm making a GParted Live Disk so that he can increase the size of his Linux partition.

**Comment by jrhorn424** [comment]
@MattB-GA-Boston Was this resolved yesterday or is it ongoing?

**Comment by J-Weeks** [comment]
@jrhorn424 I can answer this for @MattB-GA-Boston He had to leave early yesterday so this was not completed.  @jdamiron planned to complete this process today.

**Comment by MattB-GA-Boston** [comment]
Moved and resized the partition.
