### ISSUE TITLE
Handlebars: trouble using array index in data-id

### ISSUE THREAD

**Issue by jpfriedman18** [ga-wdi-boston/group-project#89]
We are trying to list all items in the user's current cart and include a button for each item that allows the user to remove it from the cart. The list of items in the cart is passed as an array to this template:
```
<div>
  {{#each items}}{{> cart-item}}{{/each}}
</div>
```
The cart-item helper is as follow:
```
<div>
  <span>{{name}}  ${{price}}</span>
  <span><button type="button" class="btn btn-danger btn-xs remove-from-cart" data-cart-item-id="{{NEED_INDEX_HERE}}">X</button></span>
</div>
```
This displays properly if the data-cart-item-id property is not included on the button. However if it is included and passed an array index, we receive the following error:

```Uncaught TypeError: __webpack_require__(...).call is not a function```

So far we have tried using {{@index}} in the data-id, which according to the Handlebars docs should provide the index of the item in the array, but we receive the error. We have also tried adding an index attribute to each item object in the cart, then passing it as {{index}} to assign the data-id to that value, but we receive the same error. We do not receive the error if passing something else, e.g. {{_id}}, however we need the index to be a data attribute on the button so that we can know which item in the cart array the user wants to remove.

**Comment by jrhorn424** [comment]
Would you mind linking to the documentation you've referenced?

**Comment by jrhorn424** [comment]
Also, are you certain that `items` references an array? Can you test it and provide evidence?

**Comment by jpfriedman18** [comment]
Docs: http://handlebarsjs.com/builtin_helpers.html
do cmd-f and search for @index

**Comment by jpfriedman18** [comment]
also saw a few references on stackoverflow confirming use of @index

**Comment by jpfriedman18** [comment]
Solved: Had to use @key instead of @index. Even though items is an array, we think that since each item is an object, @key is required. In any case, @key gives us the value we need.
