### ISSUE TITLE
A "global" my app object for storing url, user token, page, etc.

### ISSUE THREAD

**Issue by rchezrutt88** [ga-wdi-boston/group-project#90]
This is an old, old issue that has cropped up in every project but which I still require clarification on. 
How the hell do I create a "myApp" object that is both readable and writable from every file in my front-end? Now I have a my-app.js file that looks like this: 
```
const myApp = {
  BASE_URL: 'https://localhost:3000',
};

module.exports = {
  myApp,
}
```
and I'm requiring this file in every other file in my project where it's needed and storing it to a "myApp" variable. I'd like the user-actions file to be able to both read and write to this object and then I'd like the page-actions file to be able to do the same. 

How is this best accomplished?

**Comment by J-Weeks** [comment]
Have you tried asking your classmates or looking it up?

http://www.sitepoint.com/understanding-module-exports-exports-node-js/

**Comment by MattB-GA-Boston** [comment]
Why does it need to be global? Why not just create a module and load it where you need that data?

**Comment by MattB-GA-Boston** [comment]
Or better yet, use good separation of concerns in your application so that only one module actually needs that info.

**Comment by jrhorn424** [comment]
@rchezrutt88 You've created a configuration module before. Do so again.

You don't "save" any changes to disk. The file isn't readable and writable. The object in memory is.

**Comment by jrhorn424** [comment]
If you have any specific questions, feel free to ask them.

**Comment by rchezrutt88** [comment]
Okay, so I have it set up like this now: 
in my-app.js:
```
module.exports = {
  BASE_URL: 'https://localhost:3000',
};
```
Now in user-actions.js:
```
const myApp = require('./my-app.js');

let signUp = function(e) {
  e.preventDefault();
  let formData = new FormData(e.target);
  $.ajax({
    url: myApp.BASE_URL + '/sign-up',
    method: 'POST',
    contentType: false,
    processData: false,
    data: formData,
  }).done(function(data) {
    console.log(data);
  }).fail(function(jqxhr) {
    console.error(jqxhr);
  });
};
```
Now it shows that I'm making a POST to the right url but I'm still getting an error on the front-end with no feedback from the back-end.

**Comment by jrhorn424** [comment]
> Now it shows that I'm making a POST to the right url but I'm still getting an error on the front-end with no feedback from the back-end.

Can't help without an error message.

**Comment by rchezrutt88** [comment]
Deleted an s from http. 

Works now.

I'll show myself out.
