### ISSUE TITLE
Updates were rejected because the tip of your current branch is behind...

### ISSUE THREAD

**Issue by rchezrutt88** [ga-wdi-boston/group-project#93]
Per git workflow protocol, I updated my local development, rebased my feature on top of it, and then attempted to push my feature branch to my remote feature branch...and I got this. What's going on? What's the right way to deal with this? 

I know for a fact that my local feature-branch is what I want--not whatever is on the remote. Is this a case where it's appropriate to force push to my feature branch?

**Comment by J-Weeks** [comment]
Well why is it out of sync? Are you sure that you're not going to steamroll anything on your development branch?

**Comment by jrhorn424** [comment]
When you rebase, this happens. It's a normal message to receive.

This is the only time its OK to use `git push --force`.

**Comment by rchezrutt88** [comment]
"When you do this thing, this thing that you did, that thing, that thing that happened to you, always happens. And that's normal."
My kind of answer. 
CLOSED.

**Comment by rchezrutt88** [comment]
@dumplingpuff is having this same problem. Want him to see this thread too.
