### ISSUE TITLE
Want to have index and index an item by current user

### ISSUE THREAD

**Issue by dumplingpuff** [ga-wdi-boston/group-project#94]
Hi, 
In our project we are getting all pages ever created for our blog but for index.  I also want the functionality of getting all the pages for the current user.  I was thinking of doing this in the back end and creating a new constant in the pages controller to do this, but my coding smell is going off saying this will be messy.     What would be the best way of going about this?  Is there another solution in the backend I could use or should I try manipulating the data in the front end?

Thanks,
The Dump Dump Puff

**Comment by J-Weeks** [comment]
Write the messy code, get it to work, the refactor it to make it better.

**Comment by dumplingpuff** [comment]
So I see Antony's api is setup so the wiring routes holds 
```
  const actions = [
    { path: `/${controller}`,     method: 'get',    name: 'index', },
    { path: `/${controller}/:id`, method: 'get',    name: 'show', },
    { path: `/${controller}`,     method: 'post',   name: 'create', },
    { path: `/${controller}/:id`, method: 'patch',  name: 'update', },
    { path: `/${controller}/:id`, method: 'delete', name: 'destroy', },
  ];
```
should I add custom path, link it with 'get' method and then reference it to a custom function I will create?

**Comment by J-Weeks** [comment]
No, you shouldn't have to alter the wiring.

**Comment by jrhorn424** [comment]
If you want to change how `index` behaves, consider putting an `if` statement somewhere inside the action body to change the query that is used to build the response. You can trigger different branches based on whether someone is logged in, for example.

**Comment by dumplingpuff** [comment]
I'll try to figure it out. Thanks for the advice.

**Comment by dumplingpuff** [comment]
Rob and I are working on it.  I'll re-open if there is another road block.
