### ISSUE TITLE
s3 delete: 500 Access Denied

### ISSUE THREAD

**Issue by MFBrewster** [ga-wdi-boston/group-project#96]
In our file controller, I'm trying to delete from aws s3 at the same time we remove the metadata about the file from the database. Here is the whole controller (no separation of concerns yet):

```js
const destroy = (req, res, next) => {
  let s3 = new AWS.S3();
  let search = { _id: req.params.id, _owner: req.currentUser._id };
  File.findOne(search)
  .then(file => {
    if (!file) {
      return next();
    }
    return file.location.split('.com/').pop();
  }).then((awsKey) =>  ({
      Bucket: 'bucketimgoinghome',
      Key: awsKey,
  })).then((params) =>
    new Promise((resolve, reject) =>
      s3.deleteObject(params, (err, data) =>
        err ? reject(err) : resolve(data)
      )
    )
  )
  .then(() => File.findOne(search).remove())
  .then(() => res.sendStatus(200))
  .catch(err => next(err));
};
```

When I try to delete a file from the browser, the server response is 500 and the error message is as follows: ```"{"error":{"message":"Access Denied","error":{"mess…```. Is there something to do with my .env file? Do I need some kind of authorization header in my params for the s3.deleteObject function? Any guidance would be much appreciated.

**Comment by J-Weeks** [comment]
Take a look at this for some suggestions:

https://github.com/ga-wdi-boston/group-project/issues/85

**Comment by MFBrewster** [comment]
The comments on that issue solved my problem, thanks for pointing me in the right direction!
