### ISSUE TITLE
Search bar question

### ISSUE THREAD

**Issue by nwilcox11** [ga-wdi-boston/group-project#97]
We are trying to integrate a search function, we have a working route on the back end that we have had success with a curl request.
On the front end the ajax request is returning a 500 error.  What we are sending with the search form is coming back undefined.

```
routes.get('/search', 'items#searchByName');
```

```
const searchByName = (req, res, next) => {

  let searchName = normalizedName(req.body.name);

  Item.find().then(items => items.forEach((item) => {
    let name = item.name;
    let lowerCaseName = normalizedName(name);

    if (lowerCaseName.includes(searchName)) {
        res.json({item});
    }

  })).catch(err => next(err));

};
```

```
let searchItem = function (e) {
  e.preventDefault();
  let item = new FormData(e.target);
  $.ajax({
    url: myApp.BASE_URL + '/search',
    type: 'GET',
    headers: {
      Authorization: 'Token token=' + myApp.user.token,
    },
    contentType: false,
    processData: false,
    data: item
  }).done(function(data) {
    console.log(data);
  }).fail(function(fail) {
    console.error(fail);
  });
};
```

**Comment by jrhorn424** [comment]
The error is in your client. You need to debug your AJAX request (verb, URL, data, headers, etc).

**Comment by nwilcox11** [comment]
Between the ajax and the form there is a problem.  I will report back

**Comment by jrhorn424** [comment]
Try not using FormData. If you use FormData, you have to use multer on the target endpoint. There were issues earlier this week that covered it. There is a branch on `js-template` with a fix. @gaand Posted a diff somewhere in slack within the last 7 days or so.

**Comment by nwilcox11** [comment]
We made those changes, I am making a mistake somewhere else.  I'm hunting...

**Comment by J-Weeks** [comment]
@jrhorn424 form data gets across, the req is an empty object similar to the sign in issue, curl works, ajax doesn't seem to.  re: sign in issue @gaand ?

**Comment by J-Weeks** [comment]
res.query :(

**Comment by nwilcox11** [comment]
Solved! 

Had to access the res.query which was a hash.  Had to pull out the key and pass it through to the query on server side.

Client side, instead of using form data.  Used jQuery to access the search and send the request.
