### ISSUE TITLE
Removing script tags from HTML in handlebars

### ISSUE THREAD

**Issue by kpie89** [ga-wdi-boston/group-project#98]
We are trying to remove script tags in the html that is being rendered by our handlebars templates. 

Currently, we are just using triple handlebars i.e 

```
{{{entries}}} 
```
Which renders the raw HTML and processes the HTML tags. But we are aware that this would be unsafe if an unsavory person were to put script tags in their blog. 

I have found several options online... 

There is the option of using Handlebars.registerHelper such as 

```
Handlebars.registerHelper('strip-scripts', function(context) {
    var html = context;
    // context variable is the HTML you will pass into the helper
    // Strip the script tags from the html, and return it as a Handlebars.SafeString
    return new Handlebars.SafeString(html);
  });
``` 
But I'm unsure how to implement this. 

Some people are saying to use a regex that would remove script tags such as 

```
/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/
```

But again...not sure how to implement. Do you know of how we should implement these or have any ideas about plug-ins for this problem?

**Comment by J-Weeks** [comment]
Tabled unnecessary.

**Comment by kpie89** [comment]
Would still love some insight into this issue.

**Comment by gaand** [comment]
```js
'abcbdbebf'.replace(/b/g, '');
```

**Comment by J-Weeks** [comment]
https://imgflip.com/readImage?iid=40516894

**Comment by J-Weeks** [comment]
![readimage](https://cloud.githubusercontent.com/assets/10408784/13835202/03a45338-ebcc-11e5-9633-4f1ce9b4a6c2.jpg)

**Comment by jrhorn424** [comment]
@kpie89 Was this resolved?

**Comment by kpie89** [comment]
Have a good idea of our next steps. Thanks. Closing issue.
